### ISSUE TITLE
New MCP Detector viewer AM App for RSXS endstation

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1014]
The RSXS endstation on REIXS now has an MCP detector operational.  Feizhou would like a way to view the image, since SPEC and EDM can't handle this, I suggested an AM app.  

There are also two ROIs associated with the detector, and we'd like to be able to set the associated PVs by dragging on the image. 

I think I can handle most of this - I'll need to bug @dretrex for some help on the image ROI stuff, and eithe @davidChevrier or @dretrex on getting a barebones shell AM (without dataman?) started.  It should be straight forward.

**Comment by davidChevrier** [comment]
Time Estimate: 3 hours
