### ISSUE TITLE
StripTool2 crash on remove variable

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1019]
After removing a variable, ST2 crashes as soon as you either close the Edit Variable window, or select a different variable within that window on:

```STVariableCollection::setSelectedVariable	STVariableCollection.cpp	159	```

which is:

```disconnect( selection_, SIGNAL(descriptionChanged(QString)), this, ...```

My uneducated guess would be that remove isn't updating ```selection_```, and it's pointing to an ```STVariable``` that isn't.

**Comment by dretrex** [comment]
This will become meaningless because we'll replace it.

**Comment by helfrij** [comment]
:)
