### ISSUE TITLE
REIXS Crash bug...  in GSE?

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1022]
User reported AM crashed while rapidly closing a large number of open scans.  Also, when AM restarted, stored sample positions were corrupted.

/home/reixs/beamline/programming/REIXSBeamline-build-Debug/../acquaman/source/application/AMCrashMonitorSupport.cpp:131
sigaction.c:0
??:0
??:0
??:0
??:0
??:0
/home/reixs/beamline/programming/REIXSBeamline-build-Debug/../acquaman/source/ui/dataman/AMDataSourcesEditor.cpp:35
/home/reixs/beamline/programming/REIXSBeamline-build-Debug/../acquaman/source/ui/AMVerticalStackWidget.cpp:27
/home/reixs/beamline/programming/REIXSBeamline-build-Debug/../acquaman/source/ui/dataman/AMGenericScanEditor.cpp:286
??:0
??:0
??:0
/home/reixs/beamline/programming/REIXSBeamline-build-Debug/../acquaman/source/application/REIXS/REIXSMain.cpp:57

**Comment by davidChevrier** [comment]
Time Estimate: 5 hours
