### ISSUE TITLE
AMSampleCamera::createMoveToSampleAction may not move to top left corner

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1037]
Users this week found that it's possible for the function to move to the bottom right corner (actually outside of the sample). After a little poking around they found that it depended on which way the box was drawn (top left to bottom right, or vice versa, or otherwise). Kudos to them for figuring it out. Looks like the offending line is 1283:

QVector3D currentPosition = getPointOnShape(shapeData, shapeData->shape()->at(0));

which appears to grab the first element in the shape which is a QPolygonF. I'll have to do a little extra work here to figure out which element in the polygon we should be using, but I expect that it will fix the problem.

**Comment by dretrex** [comment]
Should this be flagged as on the radar and closed?  We will be upgrading this system and we'll want to make sure that this is taken into account, but in terms of the state of this particular issue, should we close it out?

**Comment by iainworkman** [comment]
This no longer applies to the upgraded version of the SGM application. Closing out.
