### ISSUE TITLE
Move to Sample Action Sometimes Needs a Double Tap

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1049]
Since the movement is calculation based, the further the move is relative to the current position the more error there is. Sometimes when moving from one side of the plate to the other you need to issue a second command to get it to go right where you want it. I think I can alter the action to take this into account.

**Comment by dretrex** [comment]
With the new SGM upgrade, should be close out this issue?

**Comment by davidChevrier** [comment]
Yes
