### ISSUE TITLE
REIXS XAS scan naming issue

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1085]
Auto naming seems to be putting an "Unnamed" in the middle of the sample name for some reason.

**Comment by dretrex** [comment]
Is this a sample naming problem or a scan naming problem?

**Comment by epengr** [comment]
Is appearing in scan names, could originate from sample names, but I suspect not. I may have been unclear (imprecise) above.

**Comment by iainworkman** [comment]
Stole this off you @epengr, as I had a good idea exactly where it was.

**Comment by dretrex** [comment]
Done in #1411.  Time estimate?

**Comment by iainworkman** [comment]
30 minutes
