### ISSUE TITLE
IDEAS AM crashes on startup

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1097]
I think I already figured this out, but I'll actually fix it tomorrow. 

```AMXRFDetailedDetectorView::minimumEnergySpinBox_``` is null and it crashes when dereferenced.

It's null because it's new'd in ```AMXRFDetailedDetectorView::buildEnergyRangeSpinBoxView()```, which is called from ```AMXRFDetailedDetectorView::buildDetectorView()```, but  ```IDEASXRFDetailedDetectorViewWithSave::buildDetectorView()``` calls straight back to ```AMXRFBaseDetectorView::buildDetectorView()```, so this never gets new'd.  

@dretrex, I assume that the best course would be to modify ```IDEASXRFDetailedDetectorViewWithSave::buildDetectorView()``` to call ```AMXRFDetailedDetectorView::buildDetectorView()```instead, ripping out the redundant calls within it?

No rush, I want to get this up and running by the end of the week.

**Comment by davidChevrier** [comment]
@epengr Time Estimate?
There's a resolved pull request for this in #1139

**Comment by epengr** [comment]
took 15 minutes?
