### ISSUE TITLE
Some exposed controls aren't available to exporter ($control[])

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1100]
They are all in the REIXSPhotonSource AMCompositeControl group, 

These report [??] when their name is place in a $control[] for export:
ringCurrent_, epuPolarization_, epuPolarizationAngle_, monoMirrorTranslation_, monoGratingTranslation_

The other controls in REIXSPhotonSource, and the rest of the beamline are fine...

**Comment by epengr** [comment]
Ah...  so it not only has to be a control, but it has to be in the scanInitialConditions to be available in teh exporter.   That explains why no one else cared about this issue...

Thanks!

**Comment by dretrex** [comment]
Done in #1400.  Time estimate?

**Comment by iainworkman** [comment]
1 hour
