### ISSUE TITLE
BioXAS: add BioXASPseudoMotorControl.h / .cpp to the BioXAS Common project

### ISSUE THREAD

**Issue by XuetaoLiu-S** [acquaman/acquaman#1106]
the  BioXASPseudoMotorControl.h / .cpp should be added to the BioXAS Common project

**Comment by davidChevrier** [comment]
@XuetaoLiu-CLS Time Estimate?

**Comment by XuetaoLiu-CLS** [comment]
it took minutes to move the codes around :)
