### ISSUE TITLE
AMExporter File Names

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1113]
I've just found that there's a possibility to export files with names that are unacceptable. Apparently, there's nothing stopping people from forming scan names that have unprintable characters in them and when it comes time to export, the file names have a "?" in them and don't work properly (can't be copied, etc). 

I'm going to put in a last-ditch check on file names at export time to make sure that all of the characters are, in fact, printable. If they are not, I will remove the character rather than replace it.

**Comment by dretrex** [comment]
Finished in #1135.  Time estimate?

**Comment by davidChevrier** [comment]
Time Estimate: 3 Hours
