### ISSUE TITLE
AmExporter needs precision control 

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1116]
Needs to inclement new precision control options.

**Comment by dretrex** [comment]
This will require an addition to AMExporterOptionGeneralAscii where it will need to add precision and format getters and setters. It will also require properties to be added for database loading and a default set to normal double conversions (i.e. 'g' and 6).

**Comment by dretrex** [comment]
Finished in #1134.  Time estimate @davidChevrier ?

**Comment by davidChevrier** [comment]
Time Estimate: 1 hour
