### ISSUE TITLE
AMFileWriter needs precision control

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1117]
Looks like there's a similar problem happening in the AMFileWriter classes. It appears that everything is being saved as a double and getting default g-6 precision. The reason this wasn't identified in the past is that numbers less than 1 million get printed as floating point and look like integers. 

I need to do something quickly about this for the ascii type filewriter, and it's likely that we'll have to take the time now to do something for a binary filewriter (particularly because the doubles which are actual doubles are also getting a precision value that may be too low and binary would actually save the full precision available).

**Comment by dretrex** [comment]
This was finished in #1133.  Time estimate @davidChevrier?

**Comment by davidChevrier** [comment]
Time Estimate: 1 hour
