### ISSUE TITLE
Develop BioXAS main mono controls

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1118]
Developing the BioXAS Main mono class and related views/classes.

**Comment by helfrij** [comment]
Added:
- new bioxasMainCommon.pri file to manage Main beamline class files. 16ddfbdec91c0ea4e44bde18f04385fd9f3bbe4b
- new BioXASMainMonochromatorControl class, borrowing heavily from BioXASSideMonochromatorControl. 7c6cc460299c8f09c89c694265f2032252ca954d
- new BioXASMainMonochromator class, borrowing heavily from BioXASSideMonochromator. ca0d8414fcf4e3c29a752fff494126e8bd7c89ef 05428929b16764843d26a21bd6984898c3515623
- new BioXASMainPersistentView class, borrowing heavily from BioXASSidePersistentView. a9a521233d8e33f488121ad19a6804482e151724 19f751a345932ef891c24227d15f3a82abdce4d1

**Comment by XuetaoLiu-CLS** [comment]
@helfrij 
You might need to change the BioXASToolSuite as well. It won't show mono motors since nothing will be returned when calling `BioXASMainBeamline::getMotorsByType()` for `BioXASBeamlineDef::MonoMotor`

**Comment by helfrij** [comment]
Ooops, I'll remedy this. Thanks for the headsup, @XuetaoLiu-CLS.

**Comment by helfrij** [comment]
Altered:
- restored accidentally commented out references to mono motors in BioXASMainBeamline. 062935b070df3e27ed07871cc1fe6e0bd27225b4

Added:
- button to BioXASMainPersistentView that initiates the crystal change procedure when clicked. 361a7035bfe83e1d7bedcdd0f5d7d8110a5881c2
- short and long descriptions of each action in the combined crystal change action, in BioXASMainMonochromator class. These will be used in the action view for the crystal change. d612f2ceec57c867c39f000167cce7e7c189695f
- new BioXASMainMonoCrystalChangeView class files. 07b9ff78ccfe5c4f28d401fc14cd02e798e03e2a 783bb515b8f5daa1789be81e6106744fd8204969

@XuetaoLiu-CLS, with these changes I don't expect BioXASToolSuite to be affected at all, once the pvs used in each of the Side and Main mono classes are confirmed.

**Comment by XuetaoLiu-CLS** [comment]
@helfrij yes, you r correct. The `BioXASToolSuite` should work properly with the new changes.

**Comment by helfrij** [comment]
Merged in work completed in #1152. The main monochromator class has been developed and now has three separate view classes: energy control editor, crystal change status display, and the crystal change control view. @dretrex, would you mind going over the changes and design with me when you're free?

**Comment by helfrij** [comment]
I've just created a pull request for this issue (#1244) to start the process of incorporating the tools developed into master. Once this process is complete, it's possible to close issues #737 and #898 as well.

**Comment by davidChevrier** [comment]
@helfrij @dretrex 
I just pushed up an edit to this branch. I made a few minor changes to BioXASToolSuite
Now all of acquaman_suite builds on my machine.

**Comment by dretrex** [comment]
Time estimate?  Same comment as #898.

**Comment by helfrij** [comment]
This project is tricky to come up with a time estimate on. It started a long time ago and lots of work went into researching how best to do this, and trying different ideas out. The time spent actually building the final iteration would be a few weeks. I can give you a number, but I have to admit it would mostly be made up.

**Comment by dretrex** [comment]
If you can remember, maybe list out how long each version or time spent designing?  If not, it's not a big deal.  The metric is only useful if we are confident in the times we state.

**Comment by helfrij** [comment]
Time estimate: 2 months
