### ISSUE TITLE
Acquaman performance testing for increasing number of channels

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1119]
The BioXAS team are concerned about Acquaman performance as the number of input channels is increased--between 30 and 200 channels are the number of interest.

**Comment by helfrij** [comment]
I spoke to Ian and passed on @dretrex's suggestions. A Vortex detector will be set up, then performance tests can be run using increasing number of regions of interest.

**Comment by helfrij** [comment]
@dretrex @davidChevrier has this issue been taken care of, with the work you've done recently?

**Comment by dretrex** [comment]
Yes and no.  Yes in the sense that there was a specific request made and we delivered an answer about it.  No in the sense that we have never done a real test with that many channels.  I'd say we can close it out and if we run into performance issues down the road we'll tackle them then.
