### ISSUE TITLE
BioXAS file format exporter

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1120]
The BioXAS team are interested in exporting scan data to a file format that is compatible with EXAFSPAK. I think this can be accomplished by creating a subclass of AMExporterGeneralAscii, once the new file format requirements are understood.

**Comment by dretrex** [comment]
You are 100% correct.  You can then add some options to the scan configuration to save which exporter the user wants to use (I'm sure some will use EXAFSPAK, some will want to use Athena).  There are many examples in other scan configurations/views for reference.

**Comment by dretrex** [comment]
Done in #1436.
Time Estimate: 10 hours
