### ISSUE TITLE
REIXS sidebar shows 0 for TFY signal

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1121]
Always.  The PV BL1610-ID-2:mcs04:fbk works...  actually, XAS scans work...  It's probably just pointing to the wrong mcs channel or something. Should be trivial.

**Comment by dleacock** [comment]
@epengr , 

void REIXSSidebar::onTFYCountsChanged(double counts)  on line 144 isn't connected to anything as with the other functions on line 84.  I'm not sure if the TFY is connected through other files, I couldn't see anything. Just an idea.

**Comment by epengr** [comment]
That sounds about right.  It's likely something silly like that.  Thanks.

**Comment by dleacock** [comment]
Added a connection to read TFY Count

517d387399e742285cb21b

**Comment by dretrex** [comment]
Does this just need to be tested @dleacock ?

**Comment by dleacock** [comment]
Yes, it does. I never got a chance to try it.

**Comment by epengr** [comment]
We can test it, but since I need to turn off an ion pump before turning on the channeltron (TFY detector), I'd prefer not to do so while the other end station is in operation.  Are you around Monday?

**Comment by dleacock** [comment]
I'm working overnights for the next two weeks so unsure when Id be able to
come in during the day

**Comment by dretrex** [comment]
Due to the nature of the fix, @epengr, you could just test it on Monday and post the results of the test here for @dleacock.

**Comment by dretrex** [comment]
Reminder bump!

**Comment by epengr** [comment]
How can you remind me of something that I never noticed to begin with?

Yes, I'll test it tomorrow as I'm setting the endstation up for some measurements overnight anyways.  I'd offer to test it during the night while Dave's here, but I have a tight schedule of measurements to get though in one shift already.

**Comment by epengr** [comment]
That being said, "the nature of the fix" is that it's a minor convenience issue, and it can wait until Dave, the endstation and I are free at the same time so that he can see he work tested...

I'm fine either way.

**Comment by dleacock** [comment]
No one should ever come in at midnight to test two lines of code I wrote. That's my motto.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by dretrex** [comment]
This was done in #1289 (by accident).  Time estimate @dleacock?

**Comment by dleacock** [comment]
Approx 1 hour.
