### ISSUE TITLE
SXRMB EXAFS Scan Failure

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1131]
A user at SXRMB had a scan fail to cancel today. The reported error code was 262004. The user reported that the scan finished collecting data and then went into the clean up mode. The clean up seemed to hang and she left it alone for over 10 minutes. When she tried to cancel the error popped up.

I had to use the "Force Quit Acquaman" from the File menu so we could restart the program.

The only items in the SXRMBEXAFSScanActionController::createCleanupActions() call are dealing with the scaler. However, these are all controlMoveActions, so I really think they should have timed out. I'll try to look at the scanActions database to see if I can find any clues and I'll pass them along to @XuetaoLiu-CLS

**Comment by davidChevrier** [comment]
A second failure in a row appears to shed new light on the problem. @XuetaoLiu-CLS could you give a quick report on what you saw when you were down there?

**Comment by XuetaoLiu-CLS** [comment]
After the second failure, the computer is locked. We couldn't login as it keeps saying that the session is too short (10s) due to system failure or no disk space. We had to reboot the computer. After computer started, we were able to login as "SXRMB".

Both hanged scans have empty data files (all the user data files and the exported data files). 

Then we tried to rerun the scan without adding to workflow and it works. 

(maybe sth wrong with workflow? Will try it on Monday)

**Comment by davidChevrier** [comment]
I really doubt it has anything to do with the workflow ... or AMActionRunner::workflow() anyway.

Whether you click the "Add to Workflow" button to the "Start Scan" button, the scan will be run in the workflow in either case.

**Comment by dretrex** [comment]
Also, it doesn't seem weird to me that they could re-run the scan.  The scan meta data is in the user database, not in the generated ascii files.  To me, this seems like something eats file handles, never gives them back and if that OPI has been running for months without being rebooted, all kinds of quirky behaviour starts.  The only thing that is troubling to me is that we didn't seem to stop on file open failure.  Unless the computer was so messed up that it thought it had opened the file but couldn't do anything with the stream.

**Comment by davidChevrier** [comment]
Options for checking on the file size are:
In the QFile itself using the fileWriter
Using QFileInfo to check on that file
Using a QProcess to check the output of an "ls" command

**Comment by davidChevrier** [comment]
@XuetaoLiu-CLS Time Estimate?

**Comment by XuetaoLiu-CLS** [comment]
4 hours?
