### ISSUE TITLE
BioXAS pseudo motor tool writes to motors on close

### ISSUE THREAD

**Issue by beaured0** [acquaman/acquaman#1151]
Sometimes when closing windows on the BioXAS pseudo motor tool very large values are written to the setpoint pvs sending motors to their limits.

The tool suite has been disabled until this is resolved.

**Comment by davidChevrier** [comment]
Hey @beaured0 @XuetaoLiu-CLS 

What's the stuff in CLSPseudoMotorControl about "delayMove"? Can you guys explain that to me?

**Comment by dretrex** [comment]
See the following commit:  https://github.com/acquaman/acquaman/commit/e434f9368064c68496fe963b493d7fa21cf2daec

It was something I had to add in to get the pseudo motors to work at all inside of AM apparently.

**Comment by XuetaoLiu-CLS** [comment]
My understanding is that when the real motor is  moving, the pseudo motor won't move right away if we want it to move again.

________________________________________

**Comment by dretrex** [comment]
It has to do with the fact that CLS pseudo motors push on every motor in the group regardless of whether all motors are part of the move.  This then causes some issues with move statuses coming in at wrong times and causing scans to hang up.

**Comment by davidChevrier** [comment]
@XuetaoLiu-CLS @dretrex @beaured0 

A quick look at that code makes me think it's the culprit. The bool delayMove_ isn't initialized in the constructor. If we got a movingChanged at any point before we do a move() or stop() ourselves, there's a chance that it would just go somewhere since delayMoveSetpoint_ isn't initialized either.

**Comment by dretrex** [comment]
And that's why we have code reviews now!

**Comment by dretrex** [comment]
Done in pull request #1155.  Time estimate @XuetaoLiu-CLS?

**Comment by XuetaoLiu-CLS** [comment]
Finished in minutes. Tested for half an hour
