### ISSUE TITLE
Create controller-type class to streamline BioXASMainMonoCrystalChangeView

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1152]
Related to the development in #1118. I think this is a necessary change, but I don't want to mess too much with the code that's working (technically) and being tested on the beamline. The best way to go about this is to create a branch off #1118 and integrate later on, correct?

**Comment by dretrex** [comment]
Yes, branching off of #1118 is the correct way to go about it.  Do you have a plan for how to take what you have and changing it to your new paradigm?  If you would like some help feel free to post it here or come find me.

**Comment by helfrij** [comment]
Added:
- new class BioXASMainMonochromatorCrystalChangeControl.
78244f7

**Comment by helfrij** [comment]
Altered:
- crystal change control previously used a boolean isRunning_ to record whether or not a crystal change action was presently running. This has been replaced with a State enum to allow for more complicated states: None, Initialized, Running, CompleteSuccess, CompleteFail. a3943feb1586b1c1af1ca33f5bdac786d5bc1faa

- major revision of control view class. 10fed50770d44e4bf0ef6ddd05074cac76d8b46c

Added:
- 'running' and 'success' displays to the control view.1e91a1256fe8d9b7566cb9c69f1ac5106dc01275

- new class BioXASMainMonochromatorCrystalChangeView and added to the persistent panel. 8374759f607d46850a9106e96191ff2f78806f72 a2b8e51925de10ad26268b6a9aa20d2a9043a11a 827406b880f3fa70adbe6fd2e9d07e7426ed8c81

- new getters in BioXASMainMonochromator for the slits closed and paddle out controls, so the mono crystal change view can report their values. 4886ddd6bd10cb789a5ee13dc20f85c68342ed54

- slots that update mono crystal change view elements in response to mono signals, and an updateView() public slot that performs a force-refresh. e18177a62811faea7cbee4e8013f131f02e4541b 1374dd0504d631115b692bfc8f049d815ab35cea

Altered:
- Removed the restriction that the mono region be either A or B in order to perform a crystal change; when None is encountered, it now assumes the destination region is A. This allows a crystal change to be performed when the mono was left in a funny state when the last crystal change was incomplete. This should be addressed differently in the future--ideally, the user should be asked which they'd like the desired state to be. 776ecce2f3ed063f00ecbd53d10ddaca89a8dec5

- Removed the lines of code in the crystal change control that would cause the control state to be automatically reset to 'None' or 'Initialized' once an end state was reached (CompleteSuccess, CompleteFail). This was meant to assure that the results from the previous crystal change did not impact the next crystal change, but instead caused problems with the control view displaying incorrect information to the user. Instead, I've implemented a reset() public slot in the control class, which resets the control state on-demand. 0be7eac686c316f569c6469e6995ada8389c8acf 9c7a935af8f1fd33dcc1149407e914c6354aa34e

**Comment by helfrij** [comment]
There have been problems with the bragg motor position not matching up with where the mono is actually at (determined by physical inspection). 

I am able to continue beamline testing by setting the hard-coded crystal change position value in BioXASMainMonochromator to the bragg motor position that fulfills two conditions:

1. the mono is visually at 55deg.
2. the 'at crystal change position' pv changes value. 

Yesterday, this position was 66deg and crystal changes were completed successfully. Crystal changes have been performed successfully today, but the position has jumped up from 66deg to 80deg.

**Comment by helfrij** [comment]
Edit: 92deg.

**Comment by davidChevrier** [comment]
@helfrij on the note of the motor position not matching the physically inspected position, I recal @beaured0 mentioning something about that mono losing 10 degrees (was that the number?) when rotating through the crystal change reason. Might that have something to do with this?

**Comment by helfrij** [comment]
Yup @davidChevrier, I believe this is related. The difference is about 10deg every time it happens (the jumps are 11deg, 14deg, and 12deg so far). The jumps don't seem to appear with every crystal change, however.
