### ISSUE TITLE
SXRMB: Scaler view can't set Dwell Time

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1153]

**Comment by dretrex** [comment]
Have you seen this behaviour?  Unless the PV name was given incorrectly, there shouldn't be a way to not be able to set the dwell time.

**Comment by XuetaoLiu-CLS** [comment]
@dretrex I think the PV name might be incorrect. I talked with Quanfeng this morning about this. I need more testing.

**Comment by davidChevrier** [comment]
This is not an issue. This was a misunderstanding about how the scaler, synchronized dwell time, and AM work.
