### ISSUE TITLE
Plot scaling issues?

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1154]
I haven't quite nailed this down, but the plots in the GSE  for live scans are...  misbehaving.  I've noticed this on REIXS and IDEAS, it's not quite the same.  I've seen it in REIXS XES scans, and IDEAS XAS scans.  For example, plotting three sources during an XAS scan, normalized, they don't normalized correctly unless you fiddle with turning sources on and off and switch view modes.  

This could be missing signals in the analyzed data sources, or it could be Mplot?

Need to investigate.

**Comment by davidChevrier** [comment]
Might be related to the range not being updated in some of Darren's optimizations. @epengr when @dretrex gets a chance he'll look at this.

**Comment by dretrex** [comment]
Done in pull request #1171.  Took about an hour.
