### ISSUE TITLE
AM1DCalibrationAB normalization glitch

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1158]
I have to investigate further, but the edge jump normalization seems to have a glitch where it where it will happily normalize by a negative value when the tail of the scan is lower than the start.  This can cause some wild swings during the pre-edge, and can invert the odd EXAFS spectra.  

Also, the plot axis aren't updating properly, there may be some missing signals.

**Comment by dretrex** [comment]
@iainworkman @XuetaoLiu-CLS @helfrij this issue also belongs to IDEAS work.  It isn't flagged as such since the issue is on an AM class, but it was built for IDEAS.

**Comment by epengr** [comment]
Thanks @dretrex, no reason not to flag it as IDEAS since that's where this glitch shows up, but I use this AB on REIXS as well.   It's getting pretty slick - it may be of interest to others...

**Comment by epengr** [comment]
completed in #2059
