### ISSUE TITLE
IDEAS XAS setup tweaks

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1159]
A list of tweaks to improve user experience:

- [x] Make delta E spin box steps 0.5 eV instead of one.  The default is 0.5, and if you want to go to 1 eV, you can't use the spinners to get there.

- [x] Move XRF detector selection beside the XRF (analyzed data source) enable check box

- [x] Alert user if there a mismatch between selected detector, active regions and enabled data sources

- [x] Extend default near edge region to a more reasonable value

- [x] Add feedback on detector rate mode to XAS setup panel

**Comment by dleacock** [comment]
d038a88bbc314ba0ba51a15020ef4b6b5d3a01d5

**Comment by dleacock** [comment]
Added:
* Extended default near edge region to a more reasonable value. Now from -50 to 100 eV

8e63350d23bb8a255df97a64cfa8eb7282dee3a

**Comment by dretrex** [comment]
@dleacock, 0.5 eV single step is fine.

**Comment by dleacock** [comment]
* Moved XRF detector selection beside XRF enable checkbox

image: http://imgur.com/swcsbJ5

f5440befc115b5c4cfddb0efd7a85bd415d5b803

**Comment by dleacock** [comment]
Altered:
    * delta E spin box steps 0.5eV instead of 1.0eV
    * Moved XRF detector inside analyzed data source check box
Added:
    * Extended default near edge region
    * Add feedback information

54f4af351bc9f5d2cc21c972ac5f1c5cdb649be7

**Comment by epengr** [comment]
I've been poking around and bugging Ru, and here's the PVs that we should need to add for the 13-element detector:

`dxp1608-B21-13:EnergyPkTime`

set  - ` dxp1608-B21-13:dxp#:PreampGain`
readback  -  `dxp1608-B21-13:dxp#:PreampGain_RBV`

where `#` is "1" through "12", unfortunately there are 13 now instead of 2...  I will need to work out a couple sets of values, one long `EnergyPkTime` and one short `EnergyPkTime` and a set of 12 `PreampGain` values corresponding to each

@davidChevrier & @dretrex - Ru suggested using clsSave to record and set these sets of values.  This would be the obvious CID way to handle it, but I wonder if there isn't value in AM doing this too?  Can AM call a shell command?  If I use clsSave to grab the calibrated setting sets then AM would just all the appropriate "clsSave -r [file]" shell command to change the detector settings.  This makes it much easier to update the values - no hard coding.
Thoughts?

**Comment by dretrex** [comment]
This was done earlier in #1441.  Can you do a time estimate @dleacock?

**Comment by davidChevrier** [comment]
Time Estimate: 3 hours
