### ISSUE TITLE
IDEAS Vac stage motor control issues

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1160]
The AMMotorGroupView for the IDEAS vac stage motor on the new Sample alignment panel has some issues.  Up is down, and it seems to have a 100 mm soft limit that's problematic.  Needs testing and tweaking.

**Comment by epengr** [comment]
100mm limit was just the spinBox max.

AMMotorGroupView / AMMotorGroups don't seem to have a provision for reversing the movement direction...   @davidChevrier, am I missing something?  I believe that I could add this to  AMMotorGroupView quite easily.

**Comment by epengr** [comment]
@davidChevrier, Nevermind.  Might be a feature to consider in the future - for now, I've just changed the slop in the motor controller.    No one actually reads off the physical scale anyways, they don't need to match.

**Comment by dretrex** [comment]
That motor slop, always getting in the way!  In terms of reversing direction or something like that.  The mythical pseudo motor classes I'm making would probably be where that would be set.  Then there would be a motor group view that would take pseudo motors.

Since this seems to have wrapped up this issue, I'm going to close it.  How long did it take you to come up with your solution?

**Comment by epengr** [comment]
I spent more time fiddling with limit switch positions and slop calibration than I did "coding".  And what I did do was mostly looking for features that weren't there.

AMMotorGroupView should have the ability to determine which button is the positive direction, since that can change with the camera angle...

20 minutes?

**Comment by epengr** [comment]
Completed in #1195

**Comment by dretrex** [comment]
Maybe, but it's really just a visual representation of the motor.  The motor defines the direction.

**Comment by epengr** [comment]
Hmmm, but one may want to stick with a meaningful reference frame for the motors actual setting directions.  Use the right hand rule, and such, to decide which way is positive.  But if you have a camera looking down a negative axis, it'd be nice to have the left arrow button move the stage left on the screen without having to redefine left at a hardware level.

**Comment by dretrex** [comment]
I suppose.  If that was the case, you'd need to have multiple instantiations of the motor group view for each way of looking at it.

**Comment by epengr** [comment]
Well, yeah... If you move the camera. I was more of fixed camera perspective versus global coordinate system...
