### ISSUE TITLE
Crash browsing open scans

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1162]
This seems to be the most common remaining crash bug on both REIXS and IDEAS, clicking on open scans in the sidebar and poof...:

Ever-so-helpful crash report:
```
/home/ideas/beamline/programming/acquaman/source/application/AMCrashMonitorSupport.cpp:132
sigaction.c:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
/home/ideas/beamline/programming/acquaman/source/application/IDEAS/IDEASMain.cpp:56
```

**Comment by davidChevrier** [comment]
See #1156

**Comment by epengr** [comment]
Really? Sorry for the spam bug report...  I may need a vacation.

**Comment by dretrex** [comment]
It might be different, but the solution we're going to be taking is in issue #1156.  But you probably do need a vacation :P
