### ISSUE TITLE
Add to IDEAS ScanInitialConditions

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1176]
Add more information to Scan Initial Conditions to IDEAS XAS scans, and change default exporter setup to include that info:

Sample Slits
Sample positions
Sample stages
etc...?

**Comment by dleacock** [comment]
31267b5da895c5631060b066a5432f564ef5dc60

**Comment by dleacock** [comment]
@epengr @dretrex  Is there more you'd like me to add?

**Comment by dretrex** [comment]
Since there is so much in there now, can you reformat it so that it isn't a huge single string?  Just to help with readability.

**Comment by dleacock** [comment]
50d9a4242d1e7634a9b3ae866ed7803e32460002

**Comment by dretrex** [comment]
Looks good.

**Comment by dretrex** [comment]
Can you make a pull request for this now?

**Comment by epengr** [comment]
that should be good, thanks!

**Comment by dretrex** [comment]
Done in #1489.  Time estimate?

**Comment by dleacock** [comment]
A few minutes
