### ISSUE TITLE
Bad dynamic indexing in AMDataView

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1179]
There is a bug where it seems like the wrong scan is getting updated thumbnails.  From what I can tell, a scan will start and have the currently running or blank thumbnail then after it finishes, the updated thumbnail is given to the _previous_ scan (i.e. properModelIndex-1).  I specified dynamic in the title because if you close down AM and then boot it back up again all the thumbnails appear correctly.

**Comment by iainworkman** [comment]
Closing as rolled into a general refactor. See #1214
