### ISSUE TITLE
Update sort filter widget when proxy model is updated programatically

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1187]
As discovered by @dretrex  is #1068 if you set a filter on the proxy model from the program then the filter widget doesn't update to reflect this. It should.

**Comment by iainworkman** [comment]
I also noticed when testing this that clicking a run on the left doesn't update the run checkbox in the widget.

**Comment by iainworkman** [comment]
Altered:
- AMBrowseScansView ~ Now passes pattern and column to the sortFilterWidget as well as the model.
- AMSortFilterWidget ~ Now can have the filter pattern and column set programatically. Allows us to keep the widget in line with the proxy.

6554765d362a777545ecf0b0490e488b96365bb2

**Comment by iainworkman** [comment]
Altered: 
- AMBrowseScansView ~ Now passes requests to set the run ID to the filter widget as well as the proxy model. Keeps the display of filtered runs consistent with that in the left hand tree of runs
- AMSortFilterScansWidget ~ Exposes the ability to set the selected Run programatically.

55a92e4e1a41234d96931a987454343050c3fb4a

**Comment by dretrex** [comment]
Done in #1197.  Time estimate @iainworkman?

**Comment by iainworkman** [comment]
About 3 hours

-----Original Message-----
