### ISSUE TITLE
Generalize XRF scans

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1191]
Since all the XRF scans behave in the same way.  They can and should be generalized.  They would greatly benefit from a more out of the box implementation.  This would likely come with a new file loader, but that won't be too bad as it will be able to reuse almost everything from the existing one.  Or this could be a good opportunity to test out making our own binary file loader?  Thoughts @davidChevrier?

**Comment by davidChevrier** [comment]
I'm all for trying this one out as binary. quint32 with no compression, here we come! Still, a substantial improvement over ASCII text.

**Comment by dretrex** [comment]
This is getting closer to being a real priority due to #1376.  @XuetaoLiu-CLS, this is the issue I was mentioning earlier.  You don't need to worry about it, but I wanted to flag it since we were talking about it earlier.

**Comment by dretrex** [comment]
Now that we are where we are at, the XRF scan controllers should use the CDF file loader.

**Comment by dretrex** [comment]
Or HDF5 when we switch to it.

**Comment by dretrex** [comment]
Time Estimate: 30 minutes

**Comment by dretrex** [comment]
Done in #1928.
