### ISSUE TITLE
BioXAS XRF scan controller reads data too early

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1192]
Since it takes a while for all the data to make it into all the data sources, we are unfortunately missing all the new data when using it to acquire.  We need to implement a system, similar to what has been implemented with the scaler, that will wait for all the data sources to monitor before sending the acquisition done signal.  Would this be best done in the detector or the scan controller @davidChevrier?  My guess would be the detector.

**Comment by davidChevrier** [comment]
@dretrex definitely in the detector. I'm guessing this might be easier to do once the element enable/disable is in the model. From that, we would know which MCA waveforms are supposed to be updating so we can know which ones to wait for.

**Comment by dretrex** [comment]
Work done in #1306.  Still needs testing.  Took about 4 hours so far.

**Comment by dretrex** [comment]
Done in #1306.  Took another day and a half.

Time estimate: 2 days
