### ISSUE TITLE
Create general mono class, ancestor to both Side and Main monos.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1204]
Even though both Side and Main classes already exist now and the number of subclasses isn't likely to get any larger anytime soon, I think this is a good idea. It simplifies the process of generalizing related classes, such as the crystal change software.

**Comment by helfrij** [comment]
Added:
- new, empty class BioXASSSRLMonochromator.

0908b42e56d04ab1687c60b78dc05842b6be6ce6

Altered:
- BioXASSSRLMono: added a significant number of new pure virtual functions. I think these requirements make sense and can be easily extended to BioXASMainMono eventually.
- BioXASSSRLMono: added nested classes that enumerate the state/status of important controls.
- BioXASSideMono: now a subclass of BioXASSSRLMono, implementing the class requirements as best as presently possible.
- BioXASSideMono: an update of variable and function names to make meaning more clear and reflect a better understanding of what's going on.

3a91106b06e94472d1c9c035d56eb46cec19daac

**Comment by davidChevrier** [comment]
Nicely done @helfrij 
Time estimate?

**Comment by helfrij** [comment]
Done in pull request #1212. Took 5 hours.
