### ISSUE TITLE
IDEAS sidebar too tall

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1209]
Barely.  It all fits on the screen only on the monitor without the OS menus.

**Comment by epengr** [comment]
Or...  just upgrade to a 32" 2560x1440 monitor...

**Comment by epengr** [comment]
It turns out that the persistent view (sidebar) was just expanding to fill the available space. Something else is driving the minimum AM window size to be slightly taller than the available screen real-estate.

@davidChevrier, @dretrex, @helfrij - Is no one else having issues with AM window sizing?  Can you shirk the window vertically at all?  I can't.  This would narrow the uncooperative widget to one of my scan configuration views if I'm the only one. Otherwise...

@iainworkman, is there a chance that this has something to do with the AMScanDataView?  I'm pretty sure that this issue just cropped up in the past several months.

**Comment by dretrex** [comment]
I think the culprit is the XRF detector view.  There is a lot of stuff in there.

**Comment by epengr** [comment]
Good call.  Confirmed.  Specifically the 13-el window.  That'd be when it cropped up...

**Comment by epengr** [comment]
Completed in #1272 
Took about an hour - mostly building and rebuilding to find the right sizes.
Also realized that the OPI in my office has a 1680x1050 monitor which makes such optimizations impossible.
