### ISSUE TITLE
Add AMControlWaitAction support to AMActionSupport.h

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1211]
I'm using a lot of control wait actions just now, and I think making them can be simplified by adding a buildControlWaitAction-type method in AMActionSupport. This would be almost identical to the existing buildControlMoveAction method.

**Comment by davidChevrier** [comment]
Very much agreed @helfrij 

@dleacock , would you have any interest in tackling this one?

**Comment by dleacock** [comment]
I'm in.

**Comment by davidChevrier** [comment]
Thanks @dleacock 
If you need a hand feel free to drop by.

**Comment by dretrex** [comment]
@helfrij great idea.

**Comment by XuetaoLiu-CLS** [comment]
@dleacock 
My changes with one helper function for `AMControlWaitAction` are in master now.

**Comment by dleacock** [comment]
Oh, ok.  Am I still doing this then? 


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by dretrex** [comment]
Yeah, if you could still do all the replacements that would be a great help.  You just don't need to make the static getter in AMActionSupport.

**Comment by dleacock** [comment]
I already wrote it last night but didn't commit it yet. I'll just delete it then and put his into effect. 


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by davidChevrier** [comment]
Sorry @dleacock 
We had a laugh at Monday's meeting when we were talking about the issue and @XuetaoLiu-CLS said he'd already done it in another issue. It should be in master now, but if you could apply it to all of the other instances that would be great. I see @XuetaoLiu-CLS sent you an email ... but apparently it was a day too late. My bust, I could have sent something more quickly.

**Comment by dleacock** [comment]
*Added AMActionSupport::buildControlWaitAction for
    BioXASSideMonochromator, SGMBeamline, SXRMBBeamline

c657452a87aa4346621f32bc8c96ffcb45b4969d

**Comment by dretrex** [comment]
Done in #1418.  Time estimate?

**Comment by dleacock** [comment]
Time Estimate: 1.00 hours
