### ISSUE TITLE
AMDataview double click beahvior

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1213]
Single clicking rapidly on two consecutive scans seems to be interrupted as a double click, which then opens those scans - annoying if you are trying to crtl-click select half a dozen scans.

Can the double click behavior be filtered, so that it only opens the selected scans if you click twice on the same thumb nail?

**Comment by dretrex** [comment]
It's probably just waiting too long for double clicks.  Or you should just not click so fast :P

**Comment by epengr** [comment]
Can't click slower...  Too much to do!

I don't wanna have to find the relevant Human Interface Guidelines, but I'm pretty sure that two rapid single clicks on two completely different objects/icons/items should never be interrupted as a double click.  Seems... wrong.

**Comment by iainworkman** [comment]
I had to manually implement the dc behaviour with a QTimer. I'll just reduce the timer window.

-----Original Message-----

**Comment by epengr** [comment]
I'm sure it works better than if I had manually implemented it :)

Thanks!

**Comment by iainworkman** [comment]
There are a few kinks with it. Storing an int lastClickedIndex_ would also not be a bad idea. Would certainly present the described behaviour of having a load happen on two rapid clicks on separate items.

**Comment by iainworkman** [comment]
Closing as rolled into a general refactor. See #1214
