### ISSUE TITLE
Refactoring the Dataview and associated classes

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1214]
[Pull request #1372]
There are still a few issues with the dataview, namely double clicking and thumbnail indexing. When looking at this issues it tends to come to light that they stem from a set of general smells, especially from the loading of data and the updating of data when signals are emitted from the database object. In light of this, rather than attempt to re-factor it piecemeal in order to solve a few issues separately, I'll just look at the whole shebang at once.

As such I'm going to close:
#909 - Drag & Drop Unavailable
#1213 - Double Click Behaviour
#1179 - Bad Dynamic Indexing of Thumbnails
...as the re-factor will aim at sorting out these problems.

**Comment by iainworkman** [comment]
Current issues that I can see, in general terms:
- The AMLightweightScanInfoCollection does ''A LOT''. It builds the collection from the database initially, it listens to all the changes coming in and updates its data based on these changes, and ultimately it stores all the scan infos. Really it should just do the last. A factory which does the initial bulk data load might be a good idea, but doesn't solve the issue of changes to the data while the system is running.
- Oh, Thumbnails. Why can't you just be good? I need to figure out either a robust way to ensure that the data in the collection is maintained for the thumbnails correctly, or radically alter the way they're stored.
- AMScanThumbnailView is still too big. I would suggest a single thumbnail class, an AMGridLayout which handles the layout stuff and then the AMScanThumbnailView itself.

**Comment by davidChevrier** [comment]
Thanks for looking into this and organizing it @iainworkman 
I definitely think you're on the right track here, let me know if there's anything I can do to help.

**Comment by iainworkman** [comment]
Changed mapping of AMLightweightScanInfos and Experiments to be *:* instead of 1:1

91b2f850c2b02d0c053d4a4ca1acb48139b4f748

**Comment by iainworkman** [comment]
Started on moving the loading of data from the database from AMLightweightScanInfoCollection to AMLightweightScanInfoFactory. At the moment just the initial bulk loading is working, the data reacting to updates in the database which live are still to be done.

d9da4ead0ddfb946221e0d094c8849f46e913023

**Comment by iainworkman** [comment]
Altered: 
- AMLightweightScanInfoFactory ~ Now properly implements loading of a single ScanInfo, as well as updated a passed ScanInfo reference to have the same information which is currently stored against it in the database. 
- AMLightweightScanInfoCollection ~ Now updates/adds scan info to the collection when an update/insert notification is received from the database on the AMScan_table

40431407f745b8fcdbe3c0984a935953d8972050

**Comment by iainworkman** [comment]
Added capture of signals from the database on item removal, addition and updating of an item to AMScan_table.

7b85b01b83bce6ec7af2292d020fa49310ecefd3

**Comment by iainworkman** [comment]
Added:
- New member variable in AMScanThumbnailView to track the row index of the last clicked thumbnail. Used to ensure that two consecutive clicks on different scan thumbnails within the double-click timer are interpreted as a double click.
 
Altered:
- Double click timer in AMScanThumbnailView is now 350ms rather than 500ms

21779a4

**Comment by iainworkman** [comment]
Noticed another bug regarding selection when testing the above:
Shift-click based multi selection works when going from a lower row index to a higher one, but not when going from a lower row index to a higher one. 
To reproduce: 
- Click a scan in the thumbnail view.
- Hold shift then click on a scan left or above the selected scan

**Comment by iainworkman** [comment]
Altered:
- AMScanThumbnailView ~ Shift-click now goes to lower row indices as well as higher

366f5aa

**Comment by iainworkman** [comment]
Removed a block of commented out code in AMScanThumbnailView and a couple of errant debugs

1ebd2cd

**Comment by iainworkman** [comment]
Drag and Drop and Experiments:
Added:
- AMLightweightScanInfo::addExperimentId(int) ~ Adds a given experimentId to the scans collection of experimentIds (prevents us having to pass around the list)
- AMLightweightScanInfo::experimentIds() ~ Added const to return. We don't need to add through this method anymore, so we can make it const.
- AMLightweightScanInfoModel::flags(QModelIndex) ~ Returns flags that indicate that Scans in the model have drag enabled (thumbnails aren't though)
- AMLightweightScanInfoModel::mimeData(QModelIndexList) ~ Returns AMDatabase access urls for all the scans in the provided QModelIndexList as QMimeData (used for drag and drop operations).

Altered:
- AMLightweightScanInfoFactory ~ Now sets a scans experimentIds using addExperimentId rather than getting the list and appending it manually.
- AMLightweightScanInfoFilterProxyModel::filterAcceptsScan() ~ Refactored to check if the experimentId is contained within the Scans list of ids, rather than a scan with a single experimentId.
- AMLightweightScanInfoModel ~ Constructor now sets supported drag actions to Copy, Link and Move
- AMBrowseScansView::addChildView() ~ Now sets the passed child view's dragEnabled to true and dropIndicatorShown to true.

7df522da3269a8376d2b6ee9ccca2cfe384a4ad3

**Comment by iainworkman** [comment]
Capturing additions to ObjectExperimentEntries:
Added:
- AMLightweightScanInfoFactory::scanIdForExperimentEntry(int, AMDatabase*) ~ Returns the id of the scan which is referenced in the entry if the ObjectExperimentEntries table with the provided id.

Altered:
- AMLightweightScanInfoFactory::updateSingle(AMIghtweightScanInfo*, AMDatabase*) ~ Fixed an issue where the experimentId list for the passed scan was not being updated.
- AMLightweightScanInfoCollection::onDbItemAdded(QString, int) ~ Now listens for additions to the ObjectExperimentEntries table and uses the AMLightweightScanInfoFactory to update the information for scans who have been added to an experiment.

903b421ddb00930dc6d22fe61decbd8cc10a92c5

**Comment by iainworkman** [comment]
Fixed drawing in AMScanTreeView:
Altered:
- AScanTreeViewDelegate ~ Now in cases where text needs to be elided the delegate just determines the text and passes it off it the protected function drawDisplay(...) which we get from QItemDelegate.

416a5d392a7ea648f71c49020692a465bbf3ba73

**Comment by iainworkman** [comment]
Removed comments which were added in commit 416a5d392a7ea648f71c49020692a465bbf3ba73

a74a7a1e544ea32e4d74729a6730cb2397fb496d

**Comment by iainworkman** [comment]
New UniformGridLayout:
Added:
- AMUniformGridLayout ~ New layout manager which arranges its children in rows , equally spaced, until another cell cannot fit in the row at which point it is automatically added to a new row. This will be used in AMScanThumbnailView.

f3f9ba0375f8ddcc232ceb9efbf1ac1d1f217536

**Comment by iainworkman** [comment]
Moving from AMScanThumbnailView to AMScanThumbnailGridView
- Moved from layout manager to geometry manager system:
    - Created class AMGridFlowGeometryManager ~ Manager geometry for a grid flow based view
    - Created class AMScanThumnmailGridGeometryManager ~ Specialization of AMGridFlowGeometryManager specifically designed for the AMScanThumbnailGridView
- Created class AMScanThumbnailGridViewItemDelegate ~ Custom item delegate for painting items in the AMScanThumbnailGridView
- Created class AMScanThumbnailGridView ~ The actual view that will eventually replace the existing AMScanThumbnailView
- Created class AMScanThumbnailGridInputManager ~ Class which encapsulates all the complicated flow logic required to work out how a given chain of interactions should be interpreted, then emits these as signals for the view to catch.

e8ea7e876d6ff2d6281637a66812d4c78a417a7d

**Comment by iainworkman** [comment]
Changes to input manager:
- Got most of the interactions working - and tested. Signals seem to be emitted in the correct sequence at the correct times

9e59f2e304ef216223fda3c1a55468333d89866a

**Comment by iainworkman** [comment]
Hover interaction logic for thumbnail view
- Added the logic to manage the hovering interaction which will switch between thumbnails for the thumbnail grid view

3a897727e7f80be56edd4b666cb15784d1dbc433

**Comment by iainworkman** [comment]
Thumbnail Geometry Bug

- Fixed issue with AMGridFlowGeometryManager::indexAt(...) which wasn't offsetting the point by the passed horizontal and vertical offset when doing coll

c82fee49f3c6313ada66d8bbab7e409a1384bcec

**Comment by iainworkman** [comment]
Thumbnail grid view (shift selection and layout):
- Added shift click logic to AMScanThumbnailGridView::onSelectionExtended(...)
- Altered grid and thumbnail sizes in AMScanThumnailGrometryManager
- Changed the signature of the input managers onSelectionRectangleEnded to just pass the selection modifier flags
- Changed the signature of the input managers onDragBegun, removing the itemIndex

1f2a2926a8f942d998141a5ef69540083c3e20f1

**Comment by iainworkman** [comment]
Fixed typo in AMScanThumbnailGridGeometryManager:
- Changed name of AMScanThumnailGeometryManager to AMScanThumbnailGeometryManager

7b1d0063f833dec947561231ad1fabf9e8f851d5

**Comment by iainworkman** [comment]
Formatting and Drag n Drop:
- Reformatted code in AMGridFlowGeometryManager because we're not writing JavaScript here
- Altered the drag and drop logic so that it now operates based on whether the item under the mouse was selected rather than whether there was an item un



6d6101f60842a201dcf133ab24dc6b2c78762616

**Comment by iainworkman** [comment]
Thumbnail Grid View rectangle selection:
- Added a rubber band to visualize the selection rectangle as it's drawn to AMScanThumnailGridView
- Changed the signal in AMGridViewInputManager for a rectangle selection ending to include the rectangle drawn
- Changed the indexAt function in AMGridFlowGeometryManager to contentIndexAt and added a cellIndexAt (content returns -1 if its in the margins between c
- Fixed a bug in (and managed to optimize in the process) indicesWithin function in AMGridFlowGeometryManager

e627e84fc3b73b501ffcba64edb3dff02aad06c1

**Comment by iainworkman** [comment]
Still left to do:
- [ ] Increment and decrement the current thumbnail being viewed
- [ ] Get the selected scan urls into the mime data for the drag

**Comment by iainworkman** [comment]
Mime data for Thumbnail Grid View:
- Added the mime data for the selected scans to the drag operation in AMScanThumbnailGridView

8784d76586f6d25f0855cd189cae2bd8299a7cf2

**Comment by iainworkman** [comment]
Run map loading in AMLightweightScanInfoFactory:
- Added static method to AMLightweightScanInfoFactory to load and return a map of scanIds to run name
- Added call to this method in constructor of AMLightweightScanInfoCollection which saves the info to a run cache
NOTE: There is no mechanism yet to refresh these when scans are moved between runs, or runs are added, while the system is running

4e429fcf6b6c5dd7a745a04558431cdbeba017c3

**Comment by iainworkman** [comment]
Addition of runs while system is open
- Added a set of signals and slots to AMLightWeightScanInfo* classes which signal that a run has been added to the database while the system is open
- Added slot to AMSortFilterScansWidget which refreshes the list of scans when a run is added"
[Issue1214 678701c] Addition of runs while system is open

678701c

**Comment by iainworkman** [comment]
Fixed thumbnail grid view refresh issue:
- Added functions dataChanged, rowInserted and rowsAboutToBeRemoved to AMScanThumbnailGridView to refresh the viewport when the underlying filter model is altered

1dcd610

**Comment by iainworkman** [comment]
Change thumbnails on hover: 
- Altered signal AMScanThumbnailGridInputManager::hoverMove to pass and x and y position within the view, rather than a deltaX 
- Added a map to AMScanThumbnailGridView which stores the current thumbnail index being viewed for each scan 
- Altered AMScanThumbnailGridView::onHoverMove to implement the required logic to update the current thumbnail index of the scan being hovered over 
- Altered AMScanThumbnailGridView::paintEvent to draw the current mapped thumbnail for a given scan

9d28097

**Comment by iainworkman** [comment]
Tidied up code for Issue1214:
- Fixed up formatting and removed debugs from:
  - AMLightweightScanInfo
  - AMLightweightScanInfoCollection
  - AMLightweightScanInfoFactory
  - AMLightweightScanInfoFilterProxyModel
  - AMLightweightScanInfoModel
  - AMScanThumbnailGridInputManager
  - AMScanThumbnailGridView
  - AMScanThumbnailGridViewItemDelegate
  - AMScanThumbnailView (this is the old one)
  - AMScanTreeView
  - AMGridFlowGeometryManager
  - AMSortFilterScansWidget
  - AMUniformGridLayout
- Added destructor to AMScanThumbnailGridView to clean up its resources
- Added virtual destructor to AMGridFlowGeometryManager to ensure it is cleaned up correctly when its subclass AMScanThumbnailGridViewGeometryManager is deleted"

99a5395

**Comment by iainworkman** [comment]
Continue cleanup and fixes of Issue1214:
- Removed AMUniformGridLayout ~ It didn't end up getting used for AMScanThumbnailGridView because of the MV system of Qt
- Altered AMBrowseScansView to now show the new thumbnail view in the first position
- Altered the name of the THUMBNAIL_WIDTH and THUMBNAIL_HEIGHT constants to CONTENT_WIDTH and CONTENT_HEIGHT to better reflect their purpose
- Explictly case double results of scaling to integers in AMScanThumbnailGeometryManager
- Tweaked sizes of content and cells in AMScanThumbnailGridGeometryManager
- Changed the index column returned to be 1 (scan name) instead of 0 (scan serial number) in AMScanThumbnailGridView::indexAt() ~ Fixed a bug where the thumbnail tooltip was just displaying the serial number
- Added a few 0 value checks to AMScanThumbnailGridView::onHoverMove to stop a very rare corner case where a divide by zero could occur
- Cleared the thumbnail map in dataChanged, rowInserted and rowAboutToBeRemoved in AMScanThumbnailGridView ~ Fixed an issue where removing thumbnails from a scan while the system was open was causing the wrong thumbnail to be displayed

9cb3ddd

**Comment by dretrex** [comment]
Done in #1372.  Time estimate?

**Comment by iainworkman** [comment]
About 80 hours.
