### ISSUE TITLE
SXRMB: add save feature for BrukeDetector data

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1215]
Users of SXRMB BL asked for a feature to save the spectum data  and the bruker data

**Comment by dretrex** [comment]
You did this already, right @XuetaoLiu-CLS?  What branch did you do it in?

**Comment by XuetaoLiu-CLS** [comment]
yes. I didn't get an opportunity to test it yet

**Comment by XuetaoLiu-CLS** [comment]
took about 3ds
