### ISSUE TITLE
Add createPowerOn/AutoSoftwareAction() functions to CLSMAXvMotor

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1216]
BioXAS Side has a requirement that the bragg motor power state be set to CLSMAXvMotor::PowerAutoSoftware in the scan controller cleanup actions. The power state must be set to CLSMAXvMotor::PowerOn before scanning, in the scan controller initialization actions. Both of these actions were created in BioXASSideMonochromator, but I think they are better placed in CLSMAXvMotor. Thoughts?

**Comment by dretrex** [comment]
I would agree.  All MAXv motors have this option.  The only thing that would need to be (potentially) added is the controls for those PV's.  I'm not sure if those PV's were added to the CLSMAXvMotor class.

**Comment by helfrij** [comment]
10 minutes.
