### ISSUE TITLE
Lock-up/Freeze/Crashes on REIXS... maybe

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1217]
Over the last week, there *may* have been four or more AM crashes the didn't leave crash reports.  

Two were phone calls in the middle of the night about the OPI completely freezing and users needing to be talked through restarting it.  

One was in the middle of the night last night, something going wrong mid XAS-scan such that a scan was left "currently scanning" and when it's status was fixed, the scan turned out to be empty.

And one was the second of 3 queued XES scans of mine on Wednesday that must have stalled or something, but a bad CDF file and an ASCII file with only a few counts were all there was to show for it.  I don't know what happened exactly, because when I came in to check on it the next users had already started because "it wasn't doing anything when he got there", whatever that means.

@davidChevrier, @dretrex, any thoughts on how to proceed?

**Comment by epengr** [comment]
For my part, I'm doing a complete clean build of everything.  I'm not 100% sure when that was last done, since it's a bit confusing with reixs_beamline.pro appearently being configured for shadow building from within Qt, but I see no that the doesn't apply to clsDeploy so those build files are elsewhere.

I'm now doing a clean debug build from within Qt. tomorrow I will run it from there and set up a workflow with a series of dummy XAS scans and sample moves and what-not and see what happens.  I can repeat the same the next day with XES scans, since they won't affect the users on the RSXS endstation.

**Comment by epengr** [comment]
@davidChevrier, @dretrex, Possibly of note:
While running a long workflow of 1 min XES scans, 
Xorg on OPI1610-201 runs at 70%-80% and AM at 15%-20%
Xorg on OPI2044-001 runs at 1%-4% and AM at 15%-20%

Current AM memory usage on OPI1610-201 is much higher too, at 80.4% versus 12.7% (both have 4 GB), but 1610 has been running a good hour longer.  In the time it took me write this post they're up to 83.7% and 16.7% respectively.  Now with 1 minute scans, this could be normal behavior, with so many GSEs open?  This would not be typical for users - but since we were running into issues with scan initialization I though lots of short scans may be better - this may be causing new issues.

**Comment by davidChevrier** [comment]
@epengr 
There should be an option to not launch scan editors in one of the menus. We use this with fast scans. It may cause other behaviors for your scans (not sure), but it would separate out memory issues from just having a lot of scans open.

**Comment by epengr** [comment]
Yes, I've seen that.  I'll make the change.

Also, if you didn't use -graphicssystem raster when you launched it in gdb, that would explain Xorg sweating so hard.

**Comment by epengr** [comment]
REIXS AM may have a memory leak...  I'm running 60s XES scans, and closing the GSEs occasionally.  Closing the GSEs doesn't free any memory, and the usage has crept up from 25% to 40% over the last hour.

**Comment by davidChevrier** [comment]
That may or may not be a leak. When memory is freed from an application, it's the responsibility of the operating system to figure out what to do. Most OSs, incluing SL5.4, will let the application keep the memory (as it expects that it will want more in the future). Until the OS sees that someone else needs the memory it usually isn't returned. The only way we can see if there really is a memory leak to is check with a program. If you want, you and I can set that up some time.

**Comment by epengr** [comment]
The bugs located and fixed in these commits:
0d7eded4a76c324791edf5b8d5727f7fe2bbeb7d
bdd8ba393f026014d375f9e8fa3dfb9abcb82877
may have resolved this issue. 

I'm closing this, and will open a new issue should more crashes appear.  There's still the rare (twice?) total system freezes, but with new OPIs on the way I think we should not worry about it until it happens on one of them (assuming AM is even to blame).

This took days of OPI time, a few hours of my time to keep dummy scans running whenever possible, and maybe an hour or two of @dretrex's and @davidChevrier's time to crush the bugs once found.
