### ISSUE TITLE
AMExtendedControlEditors aren't read-only when a read-only option is specified.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1218]
I tried to create a stack of control editors with the read-only status set to true in each constructor, and then used the setReadOnly(true) slot for each. The editors were not read-only in both cases.

Taking a look at the AMExtendedControlEditor class, I think the problem may be with the setHappy(bool) protected slot--it seems to write over any previous value of readOnly_ with the control's canMove() status.

**Comment by dretrex** [comment]
Done in #1336.  Time estimate?

**Comment by helfrij** [comment]
Two hours?
