### ISSUE TITLE
Create mono configuration view.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1223]
Want to create a place to collect widgets for viewing and configuring different mono properties. Of special interest just now are bragg motor properties: 
- the degree offset
- the encoder move type
- the move settling time. 

I expect the crystal change widgets will migrate from the sidebar to this view as well (#1118).

**Comment by helfrij** [comment]
Note to self: the items this issue was created to address are now complete. I did pull from Issue1118 in order to do this, so I think it's best to wait for Issue1118 to be incorporated into master before creating a pull request for this issue.

**Comment by davidChevrier** [comment]
Thanks @helfrij 
Time estimate?

**Comment by helfrij** [comment]
Time estimate: 2 days
