### ISSUE TITLE
Add bragg motor information to scan data

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1224]
We want to investigate some of the interesting features seen on some of the XAS scans performed on Side in November. There appear to be anomalies related to the bragg motor movement, and we'd like to collect more information to be sure.

For every point in a scan, want to add bragg motor info:
- number of move retries
- max number of move retries
- step setpoint
- degree setpoint
- physical bragg angle (...:Energy:EV:fbk:tr.K)

For every scan, some more bragg motor info:
- base velocity
- acceleration
- velocity

I think this requires adding instances of AMBasicControlDetectorEmulator to BioXASSideBeamline for each of the desired bragg motor AMControls, and then adding each to the AMDetectorInfoSet in BioXASSideXASScanActionController.

**Comment by dretrex** [comment]
You are correct.  You will need to make a control emulator for all values you wish to read and add them as exposed detectors.  VESPERS has a pretty extensive list of them that you can use for reference.

**Comment by helfrij** [comment]
I just noticed that I don't have buildNotes() available in BioXASSideXASScanActionController. VESPERS has build notes because the scan action controller inherits from the non-QObject class VESPERSScanConfiguration, and there is no existing BioXAS equivalent. Is this the recommended way to include basic information in scans @dretrex ?

**Comment by dretrex** [comment]
You will find that a lot of your scan configurations will require very similar information and what @davidChevrier and I have found is that having a <beamline>ScanConfiguration/ScanConfigurationDbObject combo helps a lot with that.  Since you currently only have the one scan configuration, you could tide yourself over with just having that method inside your BioXASSideXASScanConfiguration.

**Comment by helfrij** [comment]
A note to myself: this branch has all that can be implemented until the code review for #1244 is complete. Everything but the physical bragg is implemented in Side and ready to go. Then, will need to add everything listed above to Main.

**Comment by dretrex** [comment]
Done in #1254.  Time estimate?

**Comment by helfrij** [comment]
About 2 hours.
