### ISSUE TITLE
Add mono calibration widget to PersistentView.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1229]
@beaured0 thought it would be handy to have a widget that calibrates the mono energy, and likes what they have on IDEAS.

**Comment by helfrij** [comment]
Added:
- new private method to BioXASSideMonochromator, calibrateEnergy(). This method performs the calculation of the bragg offset needed in order for the current mono energy to match the desired mono energy.
- new public methods to BioXASSideMonochromator, setEnergyCalibration() and createSetEnergyCalibration(). Both use the calibrateEnergy() function to derive and then set the needed bragg motor angle offset.

Altered:
- The BioXASSidePersistentView class now includes a call to setEnergyCalibration() to adjust the mono energy calibration.

**Comment by helfrij** [comment]
Prelim beamline testing suggests that the methods work as they should. There will have to be adjustments made to account for the different regions that may be active at a given time, but I think this is best handled in a new issue.

**Comment by davidChevrier** [comment]
Time estimate?

**Comment by helfrij** [comment]
I don't think this one took too long. I think about 3 hours, with testing?

**Comment by helfrij** [comment]
Time estimate: 3 hours
