### ISSUE TITLE
AMExtendedControlEditorStyledInputDialog doesn't appear to display enum values properly

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1239]
I'd like to display an instance of AMExtendedControlEditor for an enumerated control. This editor uses the StyledInputDialog to prompt the user for desired control value information. The editor correctly displays the enumerated control values, but the StyledInputDialog defaults to displaying non-enumerated double values.

The control editor creates an instance of StyledInputDialog in its constructor, and always gives it an empty QStringList() for the enums. QDebug statements in StyledInputDialog::setEnumNames() appear to indicate that the enum information in the dialog is never updated.

The control itself returns true when asked isEnum(), and correctly returns enumNames() and moveEnumNames() when asked, so I think the problem is in how information is passed between the editor and the input dialog.

Related #1218.

**Comment by davidChevrier** [comment]
@helfrij 
Interesting. I have several of these on SGM and they seem to be working fine. I wonder what the difference is.

**Comment by helfrij** [comment]
My control is one that I've created, it's listening to a bunch of pvs and reports a value change based on that information. Could you point me in the direction of a working example on SGM? That might help me figure out if what I'm seeing is actually a problem with the view, or help me fix a problem with my control.

**Comment by davidChevrier** [comment]
Hmm ... I've only used those editors with controls that are related to enumerated PVs. The SGMSideBar has an AMExtendedControlEditor called gratingNC_ ... I know that it's using enumerated values.

**Comment by helfrij** [comment]
I've fixed the problem reported in #1118. It turns out that the enumChanged() signal is only emitted when the control is first constructed. The editor can handle this, but it doesn't look like the dialog can. I added a line that emits the enumChanged() signal every time the control value changes, and was able to see the correct behavior.

**Comment by davidChevrier** [comment]
Thanks @helfrij
