### ISSUE TITLE
Add Mono Bragg Angle to BioXAS Tool Suite

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1241]
The low level screen controls the mono angle, which is not actually the bragg angle. The bragg angle appears to be a combination of that angle and the M1 pitch. Beamline staff want a control editor for this in the pseudomotor screen.

**Comment by dretrex** [comment]
Done in #1242.  Time estimate?

**Comment by davidChevrier** [comment]
Time Estimate: 1 hour
