### ISSUE TITLE
Direct Casting in MotorToolMainScreen

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1243]
@XuetaoLiu-CLS , while I was adding some functionality to the pseudomotor part, I noticed that you've got some casts like:

CLSMAXvMotor * clsMAXvMotor = (CLSMAXvMotor *)matchedMotors[i];

Which should really be

CLSMAXvMotor * clsMAXvMotor = qobject_cast\<CLSMAXvMotor*\>(matchedMotors[i]);
if(clsMAXvMotor){...

Could you check through and fix these up?

Thanks

**Comment by dretrex** [comment]
Done in #1247.  Time estimate?

**Comment by XuetaoLiu-S** [comment]
Time Estimate: 10 minutes

**Comment by dretrex** [comment]
That's apparently an account :P
