### ISSUE TITLE
Beef up setXYZControl flexibility in BioXASSSRLMonochromatorRegionControl.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1248]
Subclasses of the general BioXASSSRLMonochromatorRegionControl use beamline specific controls by setting a bunch of child controls in the subclass constructor (setUpperSlitControl(), setLowerSlitControl(), setPaddleStatusControl(), etc.). There are some improvements that can be made with how this is done:
- the child controls should be reparented to the ancestor class in each setXYZControl() body.
- old controls should be removed from the list of child controls when replaced with new controls.
- if old controls belong to the parent, they should be deleted when replaced with new controls.
- each setXYZControl() should be able to successfully handle null arguments.

EDIT:
- old controls should be disconnected, also. Thanks @dretrex.

**Comment by dretrex** [comment]
And old controls should be disconnected.

**Comment by dretrex** [comment]
Done in pull request #1317.  Time estimate?

**Comment by helfrij** [comment]
Took about 30 mins.
