### ISSUE TITLE
Replace use of sender() with QSignalMapper in BioXASSSRLMonochromatorRegionControl

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1249]
The region control uses sender() in three places to make sure an action is cleaned up when it is finished running: onRegionChangeCancelled(), onRegionChangeFailed(), and onRegionChangeSucceeded(). From Qt docs:

> Warning: This function violates the object-oriented principle of modularity. However, getting access to the sender might be useful when many signals are connected to a single slot.
Warning: As mentioned above, the return value of this function is not valid when the slot is called via a Qt::DirectConnection from a thread different from this object's thread. Do not use this function in this type of scenario.

QSignalMapper can perform the same job as sender(), without these problems.

**Comment by dretrex** [comment]
Time estimate?

**Comment by helfrij** [comment]
About an hour.
