### ISSUE TITLE
Add bragg motor power options to XAS scan action controller initialization and cleanup actions.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1253]
Now that the CLSMAXvMotor interface includes a createPowerAction() method, the bragg motor power settings can be adjusted in scan initialization and cleanup actions. For initialization, the bragg motor power should be set to CLSMAXvMotor::PowerOn; in cleanup, to CLSMAXvMotor::PowerAutoHardware. These changes should be made to both Side and Main scan action controllers.

**Comment by helfrij** [comment]
@davidChevrier @dretrex 
I have a question about the scan initialization and cleanup actions, as written for BioXASSide (and probably Main too). I see that initialization actions are broken down into multiple stages and this seems to be relatively consistent across all AM beamlines: does each stage have a specific purpose? I'm just trying to find where it's best to squeeze in the bragg motor power settings.

**Comment by dretrex** [comment]
The main idea for initialization and cleanup actions is that there may be a bunch of things you need to do.  Typically, to ensure that you don't have things interfere with each other, every separate thing is its own level in an overall sequential list.  Unless there is a particular ordering that is important for those bragg motor power settings, I'd just add it to the end of the list.

**Comment by helfrij** [comment]
@dretrex thanks. Took 15 minutes.
