### ISSUE TITLE
Detector emulator default visibility

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1255]
From going over others pull requests and personally having a lot of emulators on VESPERS, I would like to change the default visibility (i.e.: ```setIsVisible(false)``` and ```setHiddenFromUsers(true)```).  Although I'm sure there are exceptions, I'm pretty sure that >90% of all emulators are "extra" information that should be saved in the file but not displayed like normal data.  What are others opinions on this?  The main and obvious pro to this is minimizing unnecessary and redundant code.  The primary con would be that you could conceivably be confused on why your detector wasn't being displayed because in general ```setIsVisible()``` and ```setHiddenFromUsers()``` are ```true``` and ```false```, respectively.

**Comment by epengr** [comment]
I don't see a problem, but then I may have one emulator on IDEAS, maybe?  And it's hidden anyways (dwell time, maybe?)

**Comment by dretrex** [comment]
Done in #1365.  Took about 20 minutes.
