### ISSUE TITLE
BioXAS Main segfault

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1256]
I pulled down changes from master, and BioXAS Main Acquaman will build successfully but not run. GDB indicates the error appears in CLSSIS3820ScalerView.cpp around line 146, where the channels are looped through to see whether the normal channel view or the dark current channel view should be displayed. The scaler view is created in the Main app controller with the enableDarkCurrentCorrection argument set to false.

**Comment by davidChevrier** [comment]
This rings a bell. I think there might be an issue where the ordering of when detectors, controls, and the scaler are instantiated causes a problem. Just a guess, I think it might be that a detector is set as the detector related to a channel, but at that point it hasn't been new'd yet. Again, just a guess. Hopefully it helps narrow things down a bit.

**Comment by helfrij** [comment]
Yup, you're totally right @davidChevrier. In the beamline class, setupDetectors() was being called after the scaler detectors were set, causing a problem down the line when the detectors are used in the scaler view class.

**Comment by davidChevrier** [comment]
Time Estimate: 20 Minutes
