### ISSUE TITLE
Update SSRL mono configuration view

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1263]
@beaured0 made a couple of suggestions for mono config view improvement:
- [x] add bragg velocity
- [x] add bragg velocity base
- [x] add bragg acceleration
- [x] remove bragg offset
- [x] add goniometer calibration widget
- [x] move energy calibration widget to here from the PersistentView
- [ ] ~~add separate bragg motor scan configuration settings.~~ (#1270)

**Comment by helfrij** [comment]
@dretrex @davidChevrier 
There are some properties that a user may want to set specifically for a scan, as opposed to just setting the value normally. I'm thinking here of some of the bragg motor properties that are exposed in this issue: the velocity, the settling time, the encoder movement type, etc. For example, we may play around with different encoder movement types, but want to be sure that it is always IncreaseOnly for a scan. Is there a way that certain settings can be stored in AM already, like in a scan configuration? And then set in the scan initialization actions?

**Comment by dretrex** [comment]
Hey @helfrij, in our experience, users don't care about that kind of technical detail.  It is usually only beamline scientists and other experienced users.  Come find me/us some time and we can chat about it, but for the time being I wouldn't worry about exposing that kind of information in a scan meant for users.

**Comment by helfrij** [comment]
Thanks @dretrex. The scan configuration settings will be handled separately (#1270), work for this issue is now complete.

**Comment by helfrij** [comment]
Done in #1271.

**Comment by dretrex** [comment]
Time estimate?

**Comment by helfrij** [comment]
About a day.
