### ISSUE TITLE
AMMotorGroupView is not always created the specialized AMMotorGroupObjectView

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1266]
We have two implementations for AMMotorGroupView. `AMMotorGroupView(AMMotorGroup *motorGroup, ViewMode viewMode, QWidget *parent)` will always create the generalized `AMMotorGroupObjectView` instead of the special implementation of `AMMotorGroupObjectView`.

**Comment by dretrex** [comment]
Done in #1267.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 30 mins
