### ISSUE TITLE
Add missing action getters to CLSMAXvMotor

### ISSUE THREAD

**Issue by dleacock** [acquaman/acquaman#1269]
Adding action wait getters to CCW and CW Limits.  If anyone can think of more that could be added, please comment. 

e3c9ef331c12761dedcca3a5804109e136c2359f

**Comment by dleacock** [comment]
e3c9ef331c12761dedcca3a5804109e136c2359f

**Comment by dretrex** [comment]
Done in #1289.  Time estimate?

**Comment by dretrex** [comment]
@dleacock, can you do a time estimate on this issue?

**Comment by dleacock** [comment]
Approx 1 hour
