### ISSUE TITLE
Create commissioning scan configuration settings.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1270]
As Side and Main go through the commissioning process, it may be useful to perform scans that change beamline settings that future users won't care about, like the bragg motor properties in #1263. 

If I understand correctly, @dretrex suggests the best way to implement this is to add widgets to the scan configuration view for scan values to be set, store the desired scan values in the scan configuration, expose the relevant controls in the beamline class, and add setting control values to scan initialization/cleanup actions.

Of particular interest right now are bragg motor settings--this issue will address implementing these settings.

**Comment by dretrex** [comment]
Almost, what I suggest is to expose the various controls of the mono via ```AMBeamline::exposedControls()```, then when you want to change the various controls (bragg motor settings of various types) then you would do that using the workflow.  This leaves a lot of the code outside of the scan initialization and cleanup actions.  These bragg motor settings are would then not be stored in the scan configuration but they would be populated inside the ```notes()``` that would be stored with every scan.

**Comment by helfrij** [comment]
- [ ] Add control getters to the CLSMAXvMotor interface:
  - EGU velocity
  - EGU base velocity
  - EGU acceleration

- [ ] Add controls listed above as beamline exposed controls.

**Comment by dretrex** [comment]
Done in pull request #1316.  Time estimate?

**Comment by helfrij** [comment]
It was a pretty quick fix, maybe 30 mins?
