### ISSUE TITLE
BioXAS SoftIOC Generator

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1274]
Since we will likely have to make a bunch of small IOC's for BioXAS, it would make sense to have a nice procedure that we can follow that does most of the work for all subsequent IOC's.

**Comment by XuetaoLiu-CLS** [comment]
@davidChevrier @dretrex @beaured0 @helfrij 
The following files are added for the Side Table SoftIOC under `/home/bioxas/beamline/programming/softIOC`:

To be installed in `ls /iocApps/07ID_BioXAS_BL/SideXAFS_BL/IOC1607-009/Acquaman`
`BL1607-6-I22_table_softIOC.db`   The DB file
`runBioXASSideTableCoordinator`  The script to run the coordinator app
`runBioXASSideTableCoordinatorDB`  The script to run softIOC for the coordinator DB

To be installed in `/iocApps/clsInitScripts/IOC1607-009`
`clsBioXAS_SideTableCoordinator`  The script to start the coordinator app automatically
`clsBioXAS_SideTableCoordinatorDB` The script to start the coordinator DB automatically

**Comment by XuetaoLiu-CLS** [comment]
This is NOT tested yet

**Comment by dretrex** [comment]
Hey @XuetaoLiu-CLS, do we need to do anything for this?  It turns out it wasn't as critical as we expected but we should still wrap it up.  Can you give a short update @XuetaoLiu-CLS?

**Comment by XuetaoLiu-CLS** [comment]
As talked on Monday's meeting, the horizontal motor is not movable yet. Waiting for David B's update for moving the table

**Comment by dretrex** [comment]
Is that related to this issue, which is more specifically related to the SoftIOC?

**Comment by XuetaoLiu-CLS** [comment]
Yes, it is related. This contains the coordinator and IOC app for endstation table.

**Comment by dretrex** [comment]
Right, but my question is does testing the actual motor reflect on anything for this issue?  Whether the soft IOC runs or not is the question isn't it?

**Comment by XuetaoLiu-CLS** [comment]
It might. There is a DB file, which has the definitions of the PVs.  If we found something is wrong when testing the real motor, we might need to change the PV definitions and the coordinators as well

**Comment by dretrex** [comment]
I think if that was the case then that would be part of #1304 and #1305.  This issue is only about having something deploy soft IOCs should we need them.  If all that is required is the testing of the motor I think we can close this.

**Comment by XuetaoLiu-CLS** [comment]
yeah. That will be ok. We can close this and leave #1304 and #1305 open

**Comment by dretrex** [comment]
Did you want to put in a time estimate for just the IOC generator aspect (if you can recall)?

**Comment by XuetaoLiu-CLS** [comment]
took about 4 hrs
