### ISSUE TITLE
Controlling Filter Farm

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1276]
Will likely need to create a soft IOC and then get the control inside of the BioXAS application.

**Comment by helfrij** [comment]
BioXAS application plan:
- [ ] create general class BioXASCarbonFilterFarm.
- [ ] create subclasses that manage the beamline-specific setpoint information--BioXASSide-, BioXASMain-, and BioXASImagingCarbonFilterFarm.
- [ ] create view that exposes the total filter thicknesses as options for a user to select, and provides feedback for whether the motor is in a correct position.

**Comment by helfrij** [comment]
I've created some preliminary classes for the filter farm controls, a Side implementation, and added views to the Side persistent panel. Unable to proceed with testing as the status pvs are not yet available.

**Comment by dretrex** [comment]
Done in #1307.  Some testing still required.  Time estimate?

**Comment by helfrij** [comment]
Time estimate: 3 days
