### ISSUE TITLE
Controlling and configuring the Harmonic Rejection Mirrors

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1277]
This will need to be put into an IOC where it maps real controls into concepts (likely anyway).  Then this configuration needs to be integrated into the BioXAS application.

**Comment by dretrex** [comment]
This one requires beamline staff to determine how they want it controlled.  Once that's the case, we can reassign the complexity and task it to someone.

**Comment by dretrex** [comment]
@helfrij, like we discussed in our meeting today, would you be able to expose the three motors used for controlling the harmonic rejection system?  A simple view with control editors for the two heights and the pitch should be sufficient for the time being.  Also, adding them to the exposed controls list for scanning would probably be beneficial for the time being as well.

**Comment by helfrij** [comment]
Yup, no problem. I see that the pv names are in the Side Beamline Motors application, so I can start work on incorporating them shortly.

**Comment by dretrex** [comment]
Done in #1324.  Time estimate?

**Comment by helfrij** [comment]
About an hour.
