### ISSUE TITLE
Integrate XIA filters

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1279]
Requires mapping various "In/Out" positions to physical thicknesses.

**Comment by helfrij** [comment]
- [ ] Create new control class for the device, similar to the carbon filter farm (#1276)
  - Map four individual filter controls to filter thicknesses.
- [ ] Create appropriate view.

**Comment by helfrij** [comment]
Development on the AM interface will be stopped until we learn more about what filters will be installed and how the control will be used. A mental note for later: work done so far has taken about two days.

**Comment by helfrij** [comment]
Spoke with the BioXAS scientists today and they requested a control view for the XIA filters that shows the In/Out status of each filter control, buttons to add/remove a given filter, and some kind of feedback for the total active filter thickness. We still don't know what the individual filter thicknesses are yet, but basic controls can be added.

**Comment by dretrex** [comment]
Done in #1315.  Time estimate?

**Comment by helfrij** [comment]
Probably about two days total.
