### ISSUE TITLE
Table coordination

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1280]
Will need to implement a way to control the table since this will need to be used when scanning the energy on the SSRL mono's.  This will involve an IOC that maps physical motors to pitch, roll, and height.

**Comment by XuetaoLiu-CLS** [comment]
For side table, there will: pitch, yaw, height, and lateral.

**Comment by dretrex** [comment]
Done in #1294.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
took about 8 hrs
