### ISSUE TITLE
Keithly 428 interface needs some more advanced features

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1283]
Currently, only the standard basic features are available from the current Keithly interface.  Need to add in some of the more advanced features.  Will likely need an advanced view since the advanced view will likely be overkill for most situations.

**Comment by helfrij** [comment]
A basic update for the Keithley interface:
- [ ] Add voltage bias and voltage bias enabled pv names to the class constructor.
- [ ] Create instances of the voltage bias and voltage bias enabled pv controls w getters.
- [ ] Create getters and setters for the value both pvs.
- [ ] Create new view (inherits from AMCurrentAmplifierView) that exposes advanced features.

Further updates:
- [ ] Change class constructor argument from (growing) list of pv names to single base pv name

**Comment by dretrex** [comment]
This has now been merged in #1296.  Time estimate @helfrij?

**Comment by helfrij** [comment]
Time estimate: 3 days
