### ISSUE TITLE
Implement detector stages

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1285]
Once the motors for the detectors are calibrated and we know how to use them safely, it should be very straight forward to directly incorporate them into the application.

**Comment by helfrij** [comment]
There's just one lateral motor associated with the detector stage. Incorporating it into AM should include:
- [ ] Adding new motor control to BioXASSideBeamline.
- [ ] Adding motor control to list of exposed controls.
- [ ] Incorporating motor control into BioXASSideXASScanActionController (?)

**Comment by dretrex** [comment]
Adding it to the scan controller should be unnecessary.  That is likely something that would be configured after putting in a new sample and then not moved on a sample by sample basis.  The only scenario I could imagine that could involve that is if there was a desire to automatically move the detector away from the sample at the end of a scan.

**Comment by dretrex** [comment]
Done in #1308.  Time estimate?

**Comment by helfrij** [comment]
About an hour and a half?
