### ISSUE TITLE
Create generic 1D and 2D scans for commissioning.

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1287]
Since commissioning requires a lot of scanning of motors that may never be moved again, having a generic scan tool would be highly useful for finding optimal positions.  Should be fairly straight forward since AMStepScanController can already handle arbitrary dimensions.

**Comment by dretrex** [comment]
Currently in #1291.  So far has taken two days.

**Comment by XuetaoLiu-CLS** [comment]
About 3 hours more of testing.

**Comment by dretrex** [comment]
Done now.  Essentially took 2.5 days in total.
