### ISSUE TITLE
Update BioXAS applications to use new startup file dialog.

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1288]
There is a cooler and sexier dialog prompt that BioXAS should be updated to use.

**Comment by davidChevrier** [comment]
With local/network synchronization?

**Comment by dretrex** [comment]
It's not necessary, but it would preferred.  I think it's universally true now that running locally is superior.

**Comment by dretrex** [comment]
Done in #1322.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
took about 2ds
