### ISSUE TITLE
Add missing action getters to IDEAS

### ISSUE THREAD

**Issue by dleacock** [acquaman/acquaman#1292]
Spoke to @epengr and got confirmation on needed action getters for the following AMActions. 

Action getters for:   samplePlatformVertical_,
                               samplePlatformHorizontal_,
                               vacuumSampleStage_, 
                               jjSlitHGap_, 
                               jjSlitHCenter_, 
                               jjSlitVGap_, 
                               jjSlitVCenter_

**Comment by dretrex** [comment]
Which action getters @dleacock?

**Comment by dleacock** [comment]
8a659659af42f810210806cb5e2c7e8bc22ab9a4

**Comment by dleacock** [comment]
d6067920d7f941a1f39da5199a9d7e982ace7168

**Comment by dleacock** [comment]
68818de57be65d58b92219fc2c897aa0963f53d4

**Comment by dleacock** [comment]
Time Estimate: 1.0 hours
Done in #1310
