### ISSUE TITLE
Simplify bragg calibration in BioXASSSRLMonochromator

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1295]
@beaured0 discovered that there is actually a pv that will perform the calibration for us, if the motor steps calibration slope is non-zero: ...:deg:setPosn. This pv performs the same calculation as the one that's explicitly used now, but is simpler code-wise. The steps slope should never be zero, so that's not a worry.

**Comment by dretrex** [comment]
Done in #1303.  Time estimate?

**Comment by davidChevrier** [comment]
Time Estimate: 0 hours
