### ISSUE TITLE
Acquaman: seperate the CLS specific files from the acquamanCommon.pri

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1297]
Seperate the CLS specific files from the acquamanCommon.pri project file

**Comment by davidChevrier** [comment]
Done in b4d81946fef83f3f07d0981507ff8153908a76ee

**Comment by davidChevrier** [comment]
@XuetaoLiu-CLS Time Estimate?

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 3 hours
