### ISSUE TITLE
Build convenience function for AMMainWindow

### ISSUE THREAD

**Issue by dleacock** [acquaman/acquaman#1318]
Adding a buildMainWindowPane convenience function.  Takes care of the squeezing and returns a widget that can be added to the main window. I'll take people as I add it to their beamline. 

- [x] BioXAS
- [x] SXRMB

...more to be added as I find them. Checkmark indicates approval from AM beamline rep. 

Added:
* AMActionSupport::buildMainWindowPane 
4a5a0d05edc4295b2ac21f029eaf53dba5a3cea6

* Missing header
aebf101128b1194ba37df1b75302faa4d111bae8

* More appropriate naming for returned groupBox, thanks @helfrij 
0e63568eb1aa94083a68548c36ba78664a67bc89

**Comment by dleacock** [comment]
@helfrij  I've added this function to your BioXASMainAppController.  

cab7fb0af01b65a3cb3581b5a503e81261b482c9

**Comment by dleacock** [comment]
Added:

* buildMaineWindowPane to SXRMB

fec406a7b1e0b2e3130124bbed1fd87f10d38019

**Comment by dleacock** [comment]
729268966259ba09809fa8c6596ea3b35e37712d

**Comment by dleacock** [comment]
62ecfce9bf14d76268052491c41bfbe3554e644f

**Comment by dretrex** [comment]
Hey @dleacock, no worries.  That is quite close, the only thing is I don't think you need that group box though.  It causes the top frame to not be at the very top of the widget area.

**Comment by dretrex** [comment]
Done in #1410.  Time estimate?

**Comment by dleacock** [comment]
Time Estimate: 5.0 hours
