### ISSUE TITLE
Add m2 screen in/out controls to Side and Main Acquaman apps

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1319]
This morning, the BioXAS scientists requested controls for the m2 screen be added to AM to help with finding the beam during beamline testing. Not sure what the pvs are yet.

**Comment by dretrex** [comment]
Are they just wanting to move the controls or do they want to scan them as well?

**Comment by helfrij** [comment]
Just move the controls, I believe.

**Comment by dretrex** [comment]
Alright.  Well, if they do want to scan them as well, we can just add them to the exposedControls().  Maybe add them to the exposedControls() anyway for the time being?

**Comment by helfrij** [comment]
Okay, that's a good idea.

**Comment by dretrex** [comment]
Done in #1320.  Time estimate?

**Comment by helfrij** [comment]
About half a day?
