### ISSUE TITLE
BioXAS Main crashes when 'Start scan' is clicked

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1321]

**Comment by dretrex** [comment]
Where does it crash?  Can you catch it in the debugger or gdb?

**Comment by helfrij** [comment]
Yup, I think it seems to point to an incorrect usage of AMBeamline::bl()->exposedControlByInfo().

**Comment by helfrij** [comment]
The control info list in the BioXAS Main scan action controller wasn't being properly populated, which I think was causing the crash. Adding the energy control to this list seems to have fixed the problem, done in commit 6143208.

**Comment by dretrex** [comment]
Thanks for fixing that up so quickly @helfrij!  Time estimate?

**Comment by helfrij** [comment]
Np. About an hour?
