### ISSUE TITLE
Add 'setControl' functionality to AMControlEditor

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1325]
It would be handy to be able to change the control in an AMControlEditor after the editor has been created. Right now, this is accomplished by deleting editors and creating new ones. This process can be streamlined with a 'setControl' option.

Similarly, AMExtendedControlEditor should implement this as well.

Some specific views that could benefit from this functionality:
- BioXASDBHRMirrorView
- BioXASXIAFiltersView
- BioXASCarbonFilterFarmView
- BioXASSSRLMonochromatorConfigurationView
- ...

**Comment by dretrex** [comment]
Done in #1329.  Time estimate?

**Comment by helfrij** [comment]
About three hours total?
