### ISSUE TITLE
Setting up Main scanning functionality on Side

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1327]
The beamline scientists would like to use AM to perform scans on Side to help with diagnosing mono problems. There is no scaler on Side to trigger measurements just now, so the workaround is to create scaler and current amplifier objects in BioXASSideBeamline with Main pv names. Additionally, the scan action controller improvements made for Main should be ported over to Side.

- [x] Update BioXASSideBeamline with Main scaler and Keithley pvs.
- [x] Create exposed detector emulators in BioXASSideBeamline for the Side mono energy setpoint and feedback.
- [x] Update Side scan action controller, incorporating the new energy detectors and adding the difference to the scan's list of analyzed data sources.

**Comment by dretrex** [comment]
Done in #1328.  Time estimate?

**Comment by helfrij** [comment]
About an hour?
