### ISSUE TITLE
Settling time for bragg motor in XAS scans

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1331]
The settling time for the bragg motor is implemented for moves made through control editors, however it does not appear to be in effect for moves in a scan. Not sure why this is.

**Comment by helfrij** [comment]
It's a little tricky to keep testing this while the scientists are running scans. @dretrex do you have any idea off the top of your head why this might be?

**Comment by helfrij** [comment]
Thanks for the help, @dretrex. Problem fixed in 58bc583.

**Comment by davidChevrier** [comment]
Time Estimate: 30 Minutes
