### ISSUE TITLE
SXRMB: when photon shutter is closed, the TEY HV controls should be turned off automatically

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1337]
When turning off beam, the TEY HV controls are turned off automatically. 
But when the TEY HV controls are turned on and the beam is lost, the TEY HV controls are not turned off. This is a security risk.

**Comment by dretrex** [comment]
Done in #1342.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 1 hour
