### ISSUE TITLE
SXRMB: Ambiant w/o gas chamber motor view dialog reponse to "Enter" key incorrectly

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1338]
In Ambiant w/o gam chamber motor view dialog, when typing in a value to try to move the motor and clicking "enter" key, the screen will be closed.

**Comment by XuetaoLiu-CLS** [comment]
Took about 1 ~ 1.5 hours to try different solutions

**Comment by dretrex** [comment]
Done in #1341.
