### ISSUE TITLE
REIXS: Add SR570 sensitivity to Beamline Infromation for XAS scans

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1340]
Add SR570 sensitivity to Beamline Infromation for XAS scans

**Comment by iainworkman** [comment]
@epengr Would you mind if I took a look at this issue?

**Comment by epengr** [comment]
Please do.  You've just done something similar with the last issue you tackled, but there may be an added layer of complexity in converting it to a human readable value - similar things are already done for the XES scanInitialConditions to extract meaning from the spectrometer motor positions, you may want to look at that.

**Comment by iainworkman** [comment]
Yeah, I did wonder what format the PV would return in and whether some enum conversion would have to be done. 
The other thing I noticed (from my naive perspective) was that the SR570s are not controls, and don't have a control info. My first look at this essentially involved creating read only pvs for the sr570 sensitivity readings in the beamline class, and then accessing their infos when setting the xas initial conditions.

**Comment by iainworkman** [comment]
With the above commit (e085a36) there were a couple of things I wasn't positive on:
- I basically got the name of the sensitivity pv from the CLSSR570 class. The code logic in there would seem to suggest that pv (with the :sens_put) will return the current sensitivity, but the _put suffix made me a little wary.
- From looking at the existing code there are two Sr570s, on for TEY and one for I0. Is that correct? If so I assume you wanted them both?

**Comment by epengr** [comment]
Yes, there are two SR570's that the XES endstation uses, I'd like them both.

There're a couple ways to grab the sensitivity.  getting sens_put will give you a vlaue, but I'm not sure of it's reliability.  There could be a synchronization issue.  I know @XuetaoLiu-CLS did some work with this and might know more.  

There's also

:sens:num but it seems to always give 0
:sens:unit which gives you a number

:sens_num which give you a magnitude
:sens_unit which give you the associated unit as a string (e.g. uA/V)

you can also grab the inverse as :gain:fbk

Maybe not so helpful...

**Comment by epengr** [comment]
Work merged into issue #1507, and completed in #1581.
