### ISSUE TITLE
SXRMB: when crystal change completed, auto move the the crystal theta and chi PV

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1355]
The Beamline staff asked a feature for crystal selection:
When the crystal selection is completed, it will be nicer if we can move the crystal theta pv and chi pv to preset values.

**Comment by XuetaoLiu-CLS** [comment]
Took about 15 mins

**Comment by dretrex** [comment]
Done in #1356.
