### ISSUE TITLE
Recovering old scan configuration, to use in new scan configuration

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1358]
The BioXAS team would like to repeat a past scan using an identical scan configuration. We've done some looking around, but we can't quite see how to view the explicit scan configuration of a past scan (and manually copy those settings to a new scan) or how to just run a scan using a past configuration. @davidChevrier @epengr @XuetaoLiu-CLS, do you happen to know if this is possible?

**Comment by davidChevrier** [comment]
Go to the data view and click on a scan (single click). Then you can show the configuration using the right click context menu or one of the icons on the both (mouse hover and it will have a help hint). 

David Chevrier
Systems and Information Technology Manager
Mobile

**Comment by XuetaoLiu-CLS** [comment]
@davidChevrier you are 25 seconds faster than me :8ball:

**Comment by helfrij** [comment]
Thanks guys!

**Comment by epengr** [comment]
@helfrij, that's actually an important point that I didn't make clear when I dropped by - make sure that you left (single) click on the scan that you want the configuration for to highlight it before you right-click to get the menu.  If you don't, it will show you the scan configuration for whichever scan is highlighted, completely ignoring exactly where you right-clicked.

**Comment by helfrij** [comment]
Good call, thanks @epengr! I'll pass that along.
