### ISSUE TITLE
SXRMB: Add HV channel 03/04 as IC0 and IC1

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1361]
- [x] Add IC0/IC1 HV control to the control view
- [x] For ambiant endstations, allow powering on the IC0 and IC1 HV controls automatically when configured
- [x] In the EXAFS scan configuration view, allow users to choose to power on HV automatically

**Comment by dretrex** [comment]
Done in #1363.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
30mins
