### ISSUE TITLE
SXRMB: add slit view

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1362]
SXRMB Beamline staff asked for a Slit view for SXRMB

**Comment by helfrij** [comment]
@XuetaoLiu-CLS is this related to what we spoke about earlier today, a view for the JJ slits?

**Comment by XuetaoLiu-CLS** [comment]
@helfrij Yes.

**Comment by dretrex** [comment]
Done in #1371.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
30mins
