### ISSUE TITLE
Create AMPseudoMotorControl-type class

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1366]
We've created a number of classes that use AMCompositeControl in a new way, to fulfill the same functionality as pseudomotors:
- BioXASSSRLMonochromatorEnergyControl
- BioXASSSRLMonochromatorRegionControl
- BioXASCarbonFilterFarmControl
- BioXASCarbonFilterFarmActuatorControl
- CLSJJSlitsBladesControl
- ...

It would be nice to have a general AMPseudoMotorControl class that these (and future) instances all inherit from that provides a standard template and handles some of the functionality they have in common.

This is related to work done in #1033.

**Comment by dretrex** [comment]
Done in #1380.  Time estimate?

**Comment by helfrij** [comment]
About two weeks?
