### ISSUE TITLE
SXRMB: add stop PV for Ambiant Table Height

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1367]
- [x] Add the BL1606-B1-1:AddOns:Ambiant:TableHeight:stop PV
- [x] Modify the SXRMBAddOnsCoordinator
- [x] Modify the SXRMB Ambiant Motor view to add a stop button
- [ ] Deploy softIOC db
- [ ] Deploy AddOns coordinator
- [ ] rerun the softIOC app and the coordinator app

**Comment by dretrex** [comment]
Done in #1368.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
took about 1.5 hrs
need test
