### ISSUE TITLE
REIXS: remove the ui files for REIXS Acquaman

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1374]
- [x] REIXSXASScanConfigurationView.cpp
- [x] REIXSSampleChamberButtonPannel.cpp
- [x] REIXSSidebar.cpp
- [x] REIXSXESSpectrometerControlEditor

**Comment by dretrex** [comment]
Can you remove all of them in this issue?

**Comment by dretrex** [comment]
You may want to consult with @iainworkman just in case you run into any pitfalls.

**Comment by XuetaoLiu-CLS** [comment]
took about 4 hrs

**Comment by dretrex** [comment]
Done in #1387.
