### ISSUE TITLE
SXRMB: some small bugs for SXRMBAcquaman

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1388]
- [x] SXRMB HV control view spinbox rang should be 0 ~ 300V
- [x] SXRMB JJ slit inbound/outbound revered
- [x] SXRMB Scaler view is always not visible

**Comment by XuetaoLiu-CLS** [comment]
took about 1 hr

**Comment by dretrex** [comment]
Done in #1389.
