### ISSUE TITLE
Expanding Scan System Documentation

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1392]
It is not obvious on first looking over the Scan classes what job each of them conceptually performs in the running of a scan on the beamline. In the interest of making this a bit clearer the documentation for the scan system should be clarified in their comments.

No code need actually be changed - just the documentation comments for the classes:
- [x] AMScan
- [x] AMScanConfiguration
- [x] AMScanController
- [x] AMScanActionController
- [x] AMScanAction
- [x] AMScanActionInfo
- [x] AMScanActionControllerScanAssembler

#1396

**Comment by dretrex** [comment]
Done in #1396.  Time estimate?

**Comment by iainworkman** [comment]
8.5 hours
