### ISSUE TITLE
SXRMB: Acquaman crashed because 4-element detector uses the wrong OCR/ICR PV

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1393]
4-element detector icr/ocr controls used the wrong PV name. it should be:
```
dxp1606-B10-02:dxp%1.ICR
dxp1606-B10-02:dxp%1.OCR
```

**Comment by dretrex** [comment]
Can you be more specific @XuetaoLiu-CLS?  How was it wrong?

**Comment by dretrex** [comment]
Done in #1395.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
took about 1 hr to diagnostic, 2 mins to fix and 30min to test
