### ISSUE TITLE
Add pseudomotor mirror controls to BioXAS Side and Main

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1397]
We'd like to be able to easily scan the M1 and M2 mirrors on BioXAS Side and Main. This can be accomplished by implementing AMPseudoMotorControls for the following properties:
- pitch
- roll
- yaw
- lateral
- height
- bend

These controls should be implemented for both M1 and M2 mirrors, on both Side and Main.

**Comment by dretrex** [comment]
Done in #1404.  Time estimate?

**Comment by helfrij** [comment]
Time estimate: 10 days.
