### ISSUE TITLE
AMScanAction copy constructor doesn't deep copy.

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1401]
The copy constructor of AMScanAction does not perform a deep copy on the contained AMScanActionInfo. 

A review needs to also take place into all the action subclasses to see if a similar error is occurring anywhere else.

**Comment by dretrex** [comment]
Look at #1396 for discussion on copy constructors and how their used in AM.

**Comment by iainworkman** [comment]
I did the review. Nothing else seems untoward.

**Comment by dretrex** [comment]
The rest of the copy constructors had proper createCopy()?

**Comment by iainworkman** [comment]
Most of them didn't have anything to copy other than primitive values.

**Comment by iainworkman** [comment]
Done in #1402 with a fix to master in e605801
Took 2.5 hours.
