### ISSUE TITLE
SGM Alterations while upgrade is in progress

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1403]
Tom wants some stuff working on the beamline while the physical state is in transition. This means some components might be missing at given points, and changes will need to be made to Acquaman on the fly to get stuff working during these times. 

While this branch will end up never being merged back into master, I'm going to keep track here of what's been/needs to be done.

I imagine this won't be the deploy branch at any point, so users might have to tolerate the 'wrong branch' warning. I could look at disabling that dialog for this branch too. 

@davidChevrier @dretrex  If either of you guys would like me to approach this differently, let me know.

**Comment by iainworkman** [comment]
- [ ] Step one. The physical shutters represented by VVR1611-4-I10-06, VVR1611-4-I10-07 and VVR1611-4-I10-08 are no longer present. Checks for them to be in the right position need to be removed from SGMBeamline::createBeamOnActions3().

**Comment by iainworkman** [comment]
- [ ] Step two. The front and back bypass valves were complaining that they couldn't move into position. Removed their control move action from SGMBeamline::createBeamOnActions3().

**Comment by dretrex** [comment]
Technically, VVR1611-4-I10-06, VVR1611-4-I10-07 and VVR1611-4-I10-08 are valves and not shutters.

**Comment by iainworkman** [comment]
Ahhh, okay. I was going off the variable names in the beamline class.

**Comment by dretrex** [comment]
That's fair. In general you can get an idea about what a Beamline component is based in its prefix.

- VVR is valve
- PSH is photon shutter
- SSH is safety shutter
- SVM is servo motor

Etc.

Sent from my iPhone

On May 21, 2015, at 1:13 PM, iainworkman <notifications@github.com<mailto:notifications@github.com>> wrote:


Ahhh, okay. I was going off the variable names in the beamline class.

**Comment by iainworkman** [comment]
Awesome. Good to know.

**Comment by iainworkman** [comment]
Now that the upgrade project is deployed this issue is not longer needed. Closing out.
