### ISSUE TITLE
Need to add the overall amount of time for scans using the iterations configuration view holder

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1407]
Since the number of iterations for a scan has been moved to the configuration view holder, we need to add a label that shows how long the entire set of scans will take.

Can I give this to you @XuetaoLiu-CLS?

**Comment by dretrex** [comment]
The label should be beside the iterations spin box in my opinion.

**Comment by dretrex** [comment]
Done in #1409.  Time estimate?

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 2 hours
