### ISSUE TITLE
BioXAS XAS scan estimated time display incorrect

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1408]
BioXAS XAS scan configuration totalTimeChanged() signal is connected to the dwell time spinbox, which is incorrect.

**Comment by dleacock** [comment]
d644b8599372609487acf5fe51619f8d5342050f

**Comment by dretrex** [comment]
Done in #1497.
Time estimate?

**Comment by dleacock** [comment]
Time estimate: Under an hour

**Comment by davidChevrier** [comment]
Actual time estimate: 2
