### ISSUE TITLE
Add veto PV toggle to REXIS XES Scans when pausing 

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1412]
The REIXS XES detector can't actually pause, but a veto line can be use to have it ignore all incoming counts - which amounts to the same thing.

I'd like the XES scan to toggle the OprVeto to '1' when the scan is paused and to '0' when it unpauses.

                    PDTR1610-4-I21-01:OprVeto       - turns veto on and off
                    PDTR1610-4-I21-01:Veto:state   - shows the current state of the veto

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 6 hours
