### ISSUE TITLE
Add setpoint option to AMBasicControlDetectorEmulator

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1421]
AMBasicControlDetectorEmulator reports the value() of a given control, but it's possible that someone might want to keep track of a given control's setpoint in a scan. This would be particularly useful for BioXAS, where they are running tests to see how closely an energy setpoint and feedback would match up.

**Comment by dretrex** [comment]
Done in #1431.  Time estimate?

**Comment by davidChevrier** [comment]
Time Estimate: 1 Hour
