### ISSUE TITLE
SGM Upgrade - AM <-> Hexapod Driver Interface

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1423]
We need the ability to communicate between the hexapod driver software and Acquaman in a way which fits in the existing Acquaman paradigm for controls. This will include:
- [x] Setting up a softIoc record for the hexapod
- [x] Adding a coordinator to the driver server to pass information from the controller to the softIoc
- [x] Polling the softIoc in AM

**Comment by iainworkman** [comment]
For reference the added PVs are:
HXPD1611-4-I10-01:X:mm
HXPD1611-4-I10-01:X:mm:fbk
HXPD1611-4-I10-01:X:status
HXPD1611-4-I10-01:Y:mm
HXPD1611-4-I10-01:Y:mm:fbk
HXPD1611-4-I10-01:Y:status
HXPD1611-4-I10-01:Z:mm
HXPD1611-4-I10-01:Z:mm:fbk
HXPD1611-4-I10-01:Z:status
HXPD1611-4-I10-01:U:deg
HXPD1611-4-I10-01:U:deg:fbk
HXPD1611-4-I10-01:U:status
HXPD1611-4-I10-01:V:deg
HXPD1611-4-I10-01:V:deg:fbk
HXPD1611-4-I10-01:V:status
HXPD1611-4-I10-01:W:deg
HXPD1611-4-I10-01:W:deg:fbk
HXPD1611-4-I10-01:W:status
HXPD1611-4-I10-01:stop

**Comment by iainworkman** [comment]
Still to do:
- Prioritized issues to get Tom up and running on commissioning scans:
    - Being able to set the velocity of the hexapod
- Being able to access the ancillary data through the epics interface:
    - Soft limits (get, set(?))
    - Perform reference move (?)
    - Get reference move status
- Being able to trigger a trajectory move through some sort of setX setY setZ setU setV setW ... Go! type system.

**Comment by davidChevrier** [comment]
The soft limits can be handled at the EPICS softIOC database file. You can use the DRVL (Drive Low, ie,, Low Limit) and DRHV (Drive High) to control these values. AM will automatically pick up on this and should set the AMPVControls accordingly.

Out of curiosity, what is the objective for the last point? What do they hope to get out of the trajectory move in the immediate future?

**Comment by iainworkman** [comment]
This isn't so much for the immediate future (that's just the velocity). I
just thought I might as well give it some thought at the moment.

Iain

**Comment by iainworkman** [comment]
Update on added PVs:
Added:
- HXPD1611-4-I10-01:velocity:fbk
- HXPD1611-4-I10-01:velocity
- Added EGU fields for the velocity and position feedback and setpoint PVs
- Added DRVH and DRVL fields for the position setpoint PVs

**Comment by iainworkman** [comment]
Time Estimate: 23 Hours
