### ISSUE TITLE
BioXAS Commissioning Issues

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1427]
A general place to keep track of some small issues users have noticed on BioXASSide.
- [x] Loop actions in the workflow seem to display 'repeat 3 times' by default, even if it has been set to a different number of repeats. The correct number of repeats is executed, however.
- [x] After setting up a commissioning tool scan and adding it to the workflow, if 'show scan configuration' is clicked from the workflow, an empty scan configuration is displayed--does not show the details that have been set.
- [x] After setting up a commissioning tool scan and adding it to the workflow, clicking 'show scan configuration' doesn't always cause the configuration to be displayed. The first click does show the configuration, but beyond that not sure.

**Comment by dretrex** [comment]
Done in #1428.
Time Estimate: 1 hour.
