### ISSUE TITLE
Add cryostat motors to Side.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1433]
The cryostat x, y, and z motors are now available and safe to move, so let's create some CLSMAXvMotor instances in BioXASSideBeamline for each. The controls should be exposed and able to be used in a scan. Create a basic AMMotorGroupView display for the controls and add to "General" view pane.

Sets up basic controls for #1278.

**Comment by dretrex** [comment]
Done in #1434.  Time estimate?

**Comment by davidChevrier** [comment]
Time Estimate: 20 minutes
