### ISSUE TITLE
Add display for the x,y coordinates of a clicked position in a 1D scan.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1444]
In a 2D scan, clicking on the scan view will cause the x, y, and intensity at that position to be displayed. We'd like to be able to add this functionality to the 1D scan view.

**Comment by iainworkman** [comment]
Merged in #1455.

**Comment by dretrex** [comment]
Since this appears to be all done, I'm closing this out.  Time estimate @helfrij?

**Comment by helfrij** [comment]
Time estimate: 2 weeks
