### ISSUE TITLE
Add ability to send motors to a given position by right clicking on scan data.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1445]
On VESPERS, a user can move motors to a given position by right clicking on a position in a scan view. The BioXAS team would like to see this in the BioXAS application as well.

**Comment by helfrij** [comment]
Will likely need to finish #1444 before this one can be tackled in earnest. (so sayeth @dretrex )

**Comment by dretrex** [comment]
This is possible to do now based on all the work @helfrij has done.  Maybe it can even be done in a general way that can be used across beamlines?

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 4 hours

**Comment by XuetaoLiu-CLS** [comment]
It can't be generalized at this moment. Maybe in the future...
