### ISSUE TITLE
Region control appears to be disconnected, causing energy control to appear disconnected.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1447]
This behavior appears from time to time, both on application startup and sometimes during an open application's lifetime: the region control appears to be disconnected, and never seems to recover connectivity. The solution thus far has been to restart the application, and usually the region control reports as connected again. 

Some minor tweaks can be made to the structure of the region control: it doesn't need to depend on the connect states of all of its children in order to report values. Decoupling the control from some of its children may help reduce the number of times the disconnect appears.

**Comment by dretrex** [comment]
Done in #1449.  Time estimate?

**Comment by helfrij** [comment]
Time estimate: 1 hour
