### ISSUE TITLE
Integrate continuous mode inside of AM rather than using the continuous PV

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1457]
Although known for a long time, it was made painfully clear on VESPERS that switching in and out of continuous seems to have a lot of issues with the scaler.  It should be implemented inside of AM and be an actionable request.  Necessary pieces for single shot and continuous mode are the following:

#### Continuous
- scan count = 0
- number of scans = 1
- start scan = 1

#### Single Shot
- scan count = what it was before switching to continuous (this is typically 1, but not guaranteed)
- number of scans = what it was before switching to continuous (also typically 1, but not guaranteed)
- start scan = 0

The "scanning" state and whether to turn it on or not may be part of the problem. This part may need a little investigation.

**Comment by helfrij** [comment]
Time estimate: 7 hours
