### ISSUE TITLE
Add GCS2 Commands to the Hexapod Server

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1458]
The Hexapod controller comes with a set of standard commands. Before any of the more complex work on arbitrary paths can be done we will need to have these initial commands in place and callable from the server.

Note: This was separated from an earlier master issue for the hexapod driver. As such many of the commits were tagged with #1422.

Copied from master issue by @dretrex:

Commands still left to do:
- [x] Move relative
- [x] Set low position soft limit
- [x] Get low position soft limit
- [x] Get on target state
- [x] Set high position soft limit
- [x] Get high position soft limit
- [x] Get position units
- [x] Set cycle time
- [x] Get cycle time
- [x] Set pivot point
- [x] Get pivot point
- [x] Get soft limit status
- [x] Set soft limit status (in but not working)
- [x] Get step size
- [x] Set step size
- [x] Set servo mode
- [x] Get servo mode
- [x] Get min commandable position
- [x] Get max commandable position
- ~~Set closed loop velocity~~ Can only be performed on optional A & B axes (which we're not using)
- ~~Get closed loop velocity~~ Can only be performed on optional A & B axes (which we're not using)
- [x] Set system velocity
- [x] Get system velocity
- [x] Virtual move

**Comment by iainworkman** [comment]
Time Estimate: 66 hours

**Comment by dretrex** [comment]
Done in #1463.  Time estimate?

**Comment by dretrex** [comment]
Ninja'd.

**Comment by iainworkman** [comment]
Hahaha
