### ISSUE TITLE
Hexapod driver controller abstraction

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1461]
In order to improve performance and to manage the controller in a cohesive manner from within the driver application it will need an class abstraction which can cache much of the information from queries, store its state and have a public facing interface for easily accessing the information (which then prompts the controller itself to run one of the many commands, or to consult its cache). The controller will also require a initialization and calibration procedure.

**Comment by iainworkman** [comment]
To reiterate the last point in the above commit:

The controller seems to be setting the MovingStatus of the axes to NotMoving before it performs the fine grain section of a given motion. What makes me think this is that the checks for the async move command are structured as follows:
- Check the movement status of the axes.
- If the movement statuses are Stopped, then check the current position of the axes.

I added a bunch of debugs into the second check, which would (for example) result in the following output:
```
MC1611-401 > MOV X 0
Destination:  0  Final position:  -0.000192  Difference:  0.000192  Check epsilon:  0.0001 
Is  0.000192  >  0.0001 
true 
Axis X did not reach its destination of 0 (stopped at -0.000192)
MC1611-401 > POS? X
X : 0
```
Note that these debugs only output when the movement status of the axes return as not moving, and yet the position of the X axis seems to change. Now it may be that just shrinking the tolerance for the position would fix the issue, but it would limit anything higher up in the system from being able to say for definite the position of the hexapod to within this tolerance we define here. If anyone in the @acquaman/acquaman-working-group  has any ideas or has encountered anything like this in another situation I'd be open to suggestions.

**Comment by iainworkman** [comment]
Time Estimate: 64.5 hours

**Comment by davidChevrier** [comment]
Actual estimate: 13
