### ISSUE TITLE
REIXS: Crash on grating drop box change

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1467]
I've pulled in master and built it for testing as I take some measurements today.  

In the spectrometer setup panel, the grating selector drop box doesn't recognize what grating is currently in place on start-up, and choosing any grating from the drop down seg faults on REIXSSpectrometerControlEditor line 261:

energyRangeLabel_->setText(QString("test"));//%1 eV - %2 eV (%3 eV)").arg(qRound(lowerE)).arg(qRound(upperE)).arg(qRound(upperE - lowerE)));

The label exists, the variables are valid...  Not sure.

**Comment by epengr** [comment]
The Grating Mask drop down doesn't cause a crash, but it also doesn't do anything...

**Comment by iainworkman** [comment]
Comes down to multiple definitions of the energyRangeLabel_, once in the header and then again in setupUi(). I'll push up a fix asap.

**Comment by epengr** [comment]
The grating mask drop box issue is likely due to the fact that nothing appears to connect to on_maskComboBox_currentIndexChanged, if you could check that out too, please.

**Comment by iainworkman** [comment]
Thanks @epengr. Connected that up, and I think that should solve it. Just running a clean build now, so will push up if that succeeds. Once that's done I'll make a PR, and you can pull down, test and merge into master if it all seems good.

**Comment by iainworkman** [comment]
Time Estimate: 90 Minutes

**Comment by epengr** [comment]
This looks good.  Please merge it so I can deploy this afternoon.

Thanks!

**Comment by iainworkman** [comment]
Done in #1469
