### ISSUE TITLE
Create XIA filter actuator controls

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1471]
The XIA filters are about to be installed on BioXAS Side. Right now the filters are controlled by actuator position, but it would be more useful to have controls that map an actuator position to an IN/OUT state. I'm thinking that creating a new BioXASXIAFiltersActuatorControl-type class would be a good solution, with implementations for all four actuators on Side. Keeping the control class general would allow a Main implementation later on to be pretty simple. Need to check some things before getting started:
- ask BioXAS team about what the filter thicknesses for each actuator are.
- ask @beaured0 about whether the actuator motors are safe to move around, and about IN/OUT-position mapping.

**Comment by epengr** [comment]
Keeping it very general would be ideal, IDEAS will be installing XIA filters soon too and would definitely steal your work...

**Comment by helfrij** [comment]
Update to the issue spec: the actuator controls as is are already mapped to IN/OUT positions, and the BioXAS team would like the ability to select the total filter thickness applied. 

Updated requirements:
- BioXASXIAFiltersControl that maps the IN/OUT positions of four actuators to a total active filter thickness.
- Filter thicknesses: 0.25mm, 0.5mm, 1mm, 10mm (effective beam stop).
- Combinations: 0.25mm, 0.5mm, 0.75mm, 1mm, 1.25mm, 1.5mm, 1.75mm, 10mm

@epengr, these basic requirements would work well for you if your setup is very similar: low-level controls map to IN/OUT positions, interest in total filter thickness, similar filter combinations/setup. Do you happen to know if this is the case? If there's enough in common, it might be worth developing a CLSXIAFiltersControl-type class instead.

**Comment by dretrex** [comment]
I agree that if it turns out there is enough in common we could probably implement a CLS version.  That would likely benefit everybody.  VESPERS also has some XIA filters.

**Comment by epengr** [comment]
Yes, basically the same.  The filter, as IBM has it set up, has stacked 25um Cu foils in the slots (1 foil, 2 foils, 4 foils, 8 foils), so you can have anywhere between 1-15 layers of foil in the beam path.

**Comment by helfrij** [comment]
Time estimate: 1 day.
