### ISSUE TITLE
XAS scans can(not) run backwards

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1474]
Likely related to #1399?

@dretrex, backwards XAS scans fail on REIXS in the worst possible way...

You can now set negative delta E's, the scans will run as you'd expect, the data will display as you'd expect, the thumbnail in the dataview looks right.  

BUT, the data file contains a long list of the first datapoint over and over.  This is not evident until you close and re-open a scan, or export the data.

Luckily, user only ran scans backwards for a couple of hours before they noticed...

At the very least, the delta E spinbox should be limited to positive values until backwards scans actually work...

**Comment by davidChevrier** [comment]
Solution for this issue will be to prevent future use of scanning backwards from the GUI rather than anything internal.

**Comment by epengr** [comment]
Completed in 90fe788e68ecaf8e197b96c19381b156a5cd5b68

Time Estimate: 5 minutes
