### ISSUE TITLE
Default print-to-file directory causes sync conflict

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1476]
AM crashed and there was a sync conflict when it was re-opened. It turned out to be a "print.pdf" in the network folder.  

It seems that a use wanted to print the screen and left the default option which was print to file into the network data folder.   When it didn't actually print they tried again and chose the actual printer instead of pdf, but didn't think to find a remove the unwanted pdf (who would?).  

The default print-to-file folder should be the exoprtData folder (I think), to avoid this (at 5 am on a Saturday...).

**Comment by davidChevrier** [comment]
Solution: Find a way to ensure the default path does not contain _userData_.

**Comment by mButlerDM** [comment]
Time Estimate: 4 Hours
