### ISSUE TITLE
First revision of SGM Application

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1478]
We need to get a first version of the new SGM Application up and going, in order that Tom can run a simple set of generic scans on the new endstation.

This will involve:
- Controls for:
  - [x] Energy
  - [x] Exit Slit
  - [x] Grating Selection
  - [x] Scienta Manipulator
  - [x] Scaler
  - [x] SR570
- Generic Scan:
  - [x] Config
  - [x] Controller
  - [x] Exposed Controls

**Comment by iainworkman** [comment]
Time Estimate: 5 Hours

**Comment by dretrex** [comment]
Since I was also there the whole time, I've added my time as well.  5 hours from myself and 5 hours from @iainworkman.
