### ISSUE TITLE
Generic Motor Group/View For 1-6 degrees of motion

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1487]
When setting up the new SGM myself and Darren noticed that the motor group and corresponding view copes well with up to 3 axes, but must be extended to do more (see AM4DMotorGroup, SGMSampleManipulatorMotorGroup). It would be nice if the group and corresponding view coped well with anything from 1 to 6 degrees of freedom across the 3 axes.

**Comment by iainworkman** [comment]
I have a proposal for this. It would mean one new class, and changes to the existing AMMotorGroupObject, MotorGroup and MotorGroupView.

## AMMotorGroupAxis
Designation::AxisDesignation (enum values XAxis, YAxis, ZAxis, Theta, Psi, Phi)
Units::QString (eg. "mm", "deg" etc.)
Control::AMControl*
Name::QString (eg. "Z", "Y", "Up", "Yaw", "In", etc.)

## AMMotorGroupObject
Name::QString (eg. "Sample Stage" etc.)
Axes:: QMap<AMMotorGroupAxis::AxisDesignation, AMMotorGroupAxis*>

##AMMotorGroup
GroupObjects::QMap<QString, AMMotorGroupObject*>

Formatting the view would take a bit more logic, but could be fairly easily worked out if implicit relationships were assumed between translational and rotational axes (ie. alpha rotates around z, gamma rotates around y and beta rotates around x)

**Comment by dretrex** [comment]
Looks really good to me.  If you want, you could potentially use pitch, roll, and yaw right in the enum since I think those terms are conceptually broader than their greek counterparts.

**Comment by iainworkman** [comment]
Time Estimate: 29.5 hours
