### ISSUE TITLE
Complete icon package

### ISSUE THREAD

**Issue by dleacock** [acquaman/acquaman#1495]
The yellow icon needs to be the same as the green and red one, meaning that it needs a transparent background and an "off" version.

**Comment by dretrex** [comment]
You don't need to assign an estimate for issues.

**Comment by dleacock** [comment]
e09933fc48b68467aabfb33aa45a0da102b19d8a

**Comment by dleacock** [comment]
Done.  Time estimated: Roughly an hour

**Comment by dretrex** [comment]
Done in #1498
