### ISSUE TITLE
REIXS AM crashes loading XAS scan into RIXS panel

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1504]
Current users not doing RIXS, not urgent.  

AM completely goes away as soon as you choose a scan form the browser.

I'm guessing that it's related to MPlot changes?  @helfrij, do you think that might be so?

I apparently have to rebuild before I can run it in debug, but I'll post more info as I have it.

**Comment by dretrex** [comment]
Does it generate a crash report?

**Comment by epengr** [comment]
@helfrij found it in a few seconds.  Hot fix in 30908d5980f040276ec7f1baee50a9c847cdb713

Thanks!
