### ISSUE TITLE
Update REIXS/IDEAS buildStandardExportOption

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1507]
There are now a default XAS export option that @XuetaoLiu-CLS added when setting up the auto exporter (thank you!).  However, it's head contains non-REIXS/IDEAS control info, and will need to be updated to with a meaningful header.  ("Actual Horizontal/Vertical Stage Position", which appear to belong to VESPERS.)

@XuetaoLiu-CLS, I noticed that SXRMB has this same header (and no controls by that name that I see), they may want it customized as well.

I can take care of REIXS.

**Comment by dretrex** [comment]
I believe I dealt with IDEAS in #1094.

**Comment by dretrex** [comment]
Could you double check for me @epengr to make sure?  If anything is missing I can easily add it there.

**Comment by dretrex** [comment]
@epengr, can you take a quick look at this?  Could you either modify how it should be displayed or let me know?  I'd like to close out this issue since I have handled the IDEAS side and don't want the issue to languish.

**Comment by epengr** [comment]
I was discussing this with Teak and now that I know how he'd like this handled, I'll tkae care of the REIXS side and get this closed out this week.

**Comment by dretrex** [comment]
Done in #1581.  Time estimate?

**Comment by epengr** [comment]
Time Estimate: 1 day
