### ISSUE TITLE
Binned down XES scans for REIXS

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1508]
I could be useful to further bin down some XES scans to improve statistics when resolution is not needed.

REIXSXESImageInterpolationAB is already changing the image size...  I think it would be relatively easy to give that AB the option of binning it down further.  The only trick may be adjusting the x-axis values correctly, but that should be relatively trivial.  

I will investigate.

**Comment by epengr** [comment]
Time Estimate: 5 hours

**Comment by epengr** [comment]
@dretrex - Left open, missing complexity, "Investigation required", not sure how to handle?

**Comment by dretrex** [comment]
I'll take off the Investigation Required tag and close it.  We'll then assign a complexity and estimate at the same time.
