### ISSUE TITLE
REIXS Scaler/XAS scan bad behavior

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1509]
AM crashed (twice), no crash reports were generated.  Once while and XAS scan was running, once when close an open GSE.

Related or not, from the first crash on, there has been an odd issue.  XAS scans were failing on init complaining about not being able to set the 'Mode' control because it was already moving.   The scaler was in "work-around" continuous mode for some reason (scanCount = 0, startScan =1).   

With some fiddling it became clear that this happened whenever a scan was completes/is cancelled  , during the clean-up actions I'm now getting an error moving the "Start/Stop" control (because it's in the state described above).

For now, I've created an EDM button that will kick the scaler out of this state that the user can hit between scans, so it doesn't need to be addressed this evening.

Could this be some conflict between the fixes that have been put in place for the scaler issues and the workarounds that I had in place?   I don't know why it has just cropped up like this though.

**Comment by epengr** [comment]
After some digging, and consulting @dretrex, suspect it's related to the behavior of CLSSIS3820ScalerModeControl::canMove() 

Some experimenting shows that it fails 100% of the time when starting an XAS scan if the scaler is in continuous mode with:
```
in [AMControlMoveAction3]: There was an error moving the control 'Mode' into position, because the control reported it cannot move.. Please report this problem to the beamline staff.
```

On completion of a scan, cleanup can fail occasionally with:
in [AMControlMoveAction3]: There was an error moving the control 'Start/Scanning' into position (Retry No, attempt 2 of 2). Target: 0 [choice]. Actual position: 1 [choice]. Tolerance 0.1. Reason: The move was externally re-directed to another destination... Please report this problem to the beamline staff.
```

**Comment by epengr** [comment]
I've found the cause:

```
initializationStage1->addSubAction(REIXSBeamline::bl()->scaler()->initializationStage1);
initializationStage1->addSubAction(REIXSBeamline::bl()->scaler()->createContinuousEnableAction3(false));
```
Removing the createStartAction3(false) action eliminates the problem.  Pushing on the same control twice and too fast I guess?  I appears that all beamlines XAS scan initialization actions do this, so either my scaler is slow or this hasn't been deployed elsewhere yet...

I'm not sure that removing it is the solution.  Does it really need to be there? Hmmm....

If not, I can extend the issue to remove it from all beamlines.

**Comment by epengr** [comment]
Could possibly move createContinuousEnableAction3(false) to stage2?

**Comment by helfrij** [comment]
@epengr I'm not sure if this is related, but on BioXAS there were also some problems with the scaler on scan initialization a while ago. A minor update to the scaler mode control (on master) and a simplification of the scaler initialization appeared to have fixed the problem there. Here are the scaler initialization actions in BioXASSideXASScanActionController:

`initializationAction->addSubAction(scaler->createContinuousEnableAction3(false));
initializationAction->addSubAction(scaler->createDwellTimeAction3(regionTime));
initializationAction->addSubAction(scaler->createStartAction3(true));
initializationAction->addSubAction(scaler->createWaitForDwellFinishedAction(regionTime + 5.0));`

Hope that helps.

**Comment by epengr** [comment]
Pushed up as hotfix in commit 4ba186eab6b7871b4eb82e1b1ca4574cf5927cdf

Tine Estimate: 2 hours

**Comment by epengr** [comment]
@helfrij, thanks, I'll keep that in mind if I run into any issues with the first data point being wonky (I've seen this, but not recently).   As I have it now, the scaler initialization is even simpler that what you have.
