### ISSUE TITLE
Open up other databases in read-only mode

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1514]
There is a need, particularly for BioXAS, to be able to look at other databases while the application is running.  Therefore, we need to be able to add a new set of scans to the dataview and make sure that they are not modifiable.  Depending on some investigation, this may be turned into a couple smaller issues.

**Comment by dretrex** [comment]
Steps involved:
- Opening other databases.
- Each database gets its own data view.
- Will need a way to connect the new data view signals in the app controller.
- Need to check if the database needs upgrades - fail if true.

Potential trouble:
- Modifying objects after being opened from the database.  Is there a read-only db object without going through the AMConstDbObject.
- AMDbObject modifications?
- Performance of the application or AMDataViews if multiple large databases are open at the same time.  @iainworkman could you comment on this based on your knowledge of the AMScanDataView system?

**Comment by dretrex** [comment]
Will likely need to update the app controller to have a set of extra QUrl slots to handle the extra databases because they all assume the user database.

**Comment by iainworkman** [comment]
In terms of actually obtaining the data, AMScanDataView has the database it will use injected into it on construction (and in turn it injects it into all the collection, model and factory classes below it). Therefore as long as you pass it the right read-only database it should just all work.
In terms of performance, we've talked about the amount of over caching done in the collection before, which causes slow performance on the larger user databases. I've not had a change to look at this with the SGM stuff, but I believe we would need to do some poking around in the collection and factory class to do more JiT loading, and not caching. I'm pretty certain the poor performance is down to size of memory footprint. This is something we should probably benchmark before doing any refactoring of the data view classes.

**Comment by dretrex** [comment]
So far I've worked on this for about 10 hours.

**Comment by davidChevrier** [comment]
Time Estimate: 18 Hours
