### ISSUE TITLE
Add pseudomotor contols to REIXS sample stage

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1521]
Add pseudomotors that allow the sample plate to be translated in the plane of the plate regardless of the angle.

**Comment by iainworkman** [comment]
I am working on something for the Hexapod at the moment which *might* make this a fair bit easier. It's still in production at the moment, and it's off in a sub-branch of the SGM Upgrade branch.

**Comment by epengr** [comment]
@dretrex, you mentioned that something similar has been implemented for the VESPERS sample stages - can you point me to it, or suggest how to go about it? Thanks!

**Comment by epengr** [comment]
Rolled into #1525.
