### ISSUE TITLE
Persistent or saved crosshairs for camera views

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1525]
REIXS will be moving to using cameras for samples alignment, so crosshairs that reset when the software restarts is problematic. 

This could just be a hard coded position.

**Comment by epengr** [comment]
Add a second camera view / tab to the alignment screen too.

**Comment by epengr** [comment]
@iainworkman, @davidChevrier 

Is AMSampleManagementPre2013Widget used by SGM?   The only place it appears outside of REIXS is as an include in SGM is a couple spots, but it doesn't appear to be used?

I'd like to modify it for REIXS (to have two side-by-side camera views), which is way easier if it's not shared...  If so, it technically should be REIXS and not AM, but I believe it's virtually depreciated already so...

**Comment by iainworkman** [comment]
I can't check this directly in Qt Creator just at the second, as I'm on the upgrade branch. First chance I get I will switch back so I can look over the code.

**Comment by epengr** [comment]
Time Estimate: 6 hours

**Comment by epengr** [comment]
Rolled #1525 into this issue since they both involved modifying the sample management panel.

**Comment by dretrex** [comment]
Did you reopen this due to comments from the pull request or because the scope of the issue changed?

**Comment by epengr** [comment]
Scope change.

**Comment by dretrex** [comment]
Done in #1549.  Time estimate @epengr?  This is different from the pull request time estimate.

**Comment by epengr** [comment]
I know it's different, I was just in the wrong place...
Time Estimate: 2 days
