### ISSUE TITLE
IDEAS Crash on startup - New motorGroupObject Issue?

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1536]
@iainworkman,

Just pulled down and build master on IDEAS.  It's crashing on startup now and I think it's related to changes you may to the sample stage motor groups.   No rush.

0	QMap<QString, AMMotorGroupObject*>::value	qmap.h	510	0x763c92	
1	AMMotorGroup::motorGroupObject	AMMotorGroup.cpp	844	0x760a7f	
2	AMMotorGroup::addMotorGroupObject	AMMotorGroup.cpp	858	0x760cc5	
3	IDEASBeamline::setupMotorGroup	IDEASBeamline.cpp	75	0x9e1a71	
4	IDEASBeamline	IDEASBeamline.cpp	41	0x9e1d07	
5	IDEASBeamline::ideas	IDEASBeamline.h	53	0x9db802	
6	IDEASAppController::startup	IDEASAppController.cpp	75	0x9db1bf	
7	main	IDEASMain.cpp	55	0x9dc4b8

**Comment by helfrij** [comment]
@epengr I notice that AMMotorGroup *motorGroup_ doesn't appear to be instantiated anywhere in IDEASBeamline.cpp. Could this be the problem?

**Comment by iainworkman** [comment]
Yeah @helfrij that would be the issue. Should be a quick fix. I'll get it pushed up ASAP @epengr .

**Comment by iainworkman** [comment]
Ah, @helfrij has already pushed a fix up. Thank you Jessie.

**Comment by dretrex** [comment]
Done in #1538.  Time estimate, @helfrij?

**Comment by helfrij** [comment]
Time Estimate: 10 minutes

**Comment by epengr** [comment]
Thanks all.   I should have caught that one, I was looking right at it.
