### ISSUE TITLE
IDEAS Detector Issues

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1543]
Notice app output:
```
Object::connect: No such slot IDEASKETEKDetailedDetectorView::onPeakingTimeBoxChanged() in ../acquaman/source/beamline/IDEAS/IDEASKETEKDetailedDetectorView.cpp:26
Object::connect:  (sender name:   'KETEK')
Object::connect: No such signal STPlotWidget::timeChanged(STTime *time) in ../acquaman/source/StripTool2/STWidget.cpp:55
Object::connect: No such signal IDEAS13ElementGeDetector::peakingTimeChanged(double) in ../acquaman/source/ui/IDEAS/IDEASXASScanConfigurationView.cpp:131
Object::connect:  (sender name:   '13-el Ge')
```

type mismatch I think, and it probably should be connecting to ```onPeakingTimeChanged()``` not ```onPeakingTimeBoxChanged()```, so that the dropbox is updated to reflect the current detector setting.

ALSO:  noticed problem on line IDEAS/IDEASKETEKDetailedDetectorView.cpp:44   0.2 should be 2.0!
I'd rather not contemplate how long it's been like that.  The whole file is attributed to @dleacock for the naming convention change, so I'm not sure...

**Comment by dretrex** [comment]
I fixed the connects in #1094.  I can check the value tomorrow as well and fix that as well.
