### ISSUE TITLE
Add Exit Slit Position control to new SGM Beamline

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1550]
Teak has requested he have access to the Exit Slit Position (feedback = PSL16114I1003:Y:mm:fbk, setpoint = PSL16114I1003:Y:mm:encsp, status = SMTR16114I1003:status, stop = SMTR16114I1003:stop) in the new SGM Acquaman. As far as I understand it this will require:
- [x] Adding a control to SGMBeamline for this PV, and adding it to the exposed controls.
- [x] Adding an AMExtendedControlEditor for the exit slit position to the persistent view.

@davidChevrier Would the above assumptions be correct?

**Comment by davidChevrier** [comment]
@iainworkman 
I think the PV/control you want is the one called exitSlit in the old setupControls() function.
It's something like SMTR16114I1003:Y:mm:fbk.
Otherwise, conceptually, you are correct.

**Comment by iainworkman** [comment]
Yep, just caught that one now when I added the other and it was just a 'tracking, not tracking' enum value. Added the new one now.
Thanks.

**Comment by iainworkman** [comment]
Time Estimate: 30 Minutes
