### ISSUE TITLE
XES data viewer stand-alone app

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1556]
Unless an offline AM (#127) is eminent, it would be helpful to have an offline viewer for XES data.   This could just import the exported 2D files.  It would basically be a simple text importer, MPlot (GSE?), and REIXSXESImageInterpolationAB hacked together.  

The only real issue that I see is dealing with calibration - the energy axis is calibrated using motor positions from the scanInitialConditions.  Options:
- The values can either all be exported and picked out of the text file
- start with uncalibrated data. 1/2 of what the app would be used for is calibrating data based on reference samples, so one could start with a completely calibrated energy axis.
- find a way to export the starting axis values in the 2D file

This would be a good time to set up an autoexporter for XES scans - it could just export the raw 2D ready to be loaded into this app.

Nice to haves:
- the ability to load multiple scans for comparisons
- batch application of curve AB parameters (associate .cfg files?), and export of spectra

This actually became significantly more complicated as I typed...

**Comment by davidChevrier** [comment]
#127 is the solution to this problem.
