### ISSUE TITLE
Create support classes for Energy requests into control outputs

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1560]
The first step to replacing the SGM mono application is to be able to do the mapping between Energy and grating choice to the real control aspects such as grating angle, undulator position, exit slit position.  This obviously needs to be able to go both ways where changes to underlying controls propagate back up to produce a new energy.  Since it should be capable of this, it should be able to detect if it is in a bad/error state (such as if someone moved the controls from a lower level and the application is no longer in sync).

There is probably an opportunity to develop a mapping between optimal grating/harmonic/stripe choices based on certain higher level decisions such as "Optimized for Flux" vs. "Optimized for Resolution".

**Comment by iainworkman** [comment]
Still to do:
- [ ] Would like to create a test project and move my test code over to there. It shouldn't live in the class itself, nor should it be called from SGMAppController, but I would like it to hang around at least until the energy controller is done.
- [ ] Need to pin down from Tom those corner cases which should produce errors, and warnings, then implement checks for them.

**Comment by iainworkman** [comment]
Had a discussion with Tom today regarding the concept of turning off/on grating tracking. At the moment the info class has a function for returning the energy produced by the current grating angle/translation, and another 2 functions to request a shift to a new energy. It seems obvious to me that undulator and exit slit tracking being off moves the grating to that energy, but does not optimize flux by shifting the undulator/exit slit. I am less clear about what the semantic meaning of energy for the class would be in the case that the grating tracking is off. @davidChevrier @dretrex Any thoughts?

**Comment by dretrex** [comment]
I don't think I fully understand your question.  After your conversation with Tom, did he bring up that he wanted grating tracking on/off to be an option?  Or is this just more of a curiosity?

**Comment by iainworkman** [comment]
The ability to turn the grating tracking on/off was an option in the old SGM AM. I was implementing all the tracking options, and couldn't quite understand what that one really meant.

**Comment by dretrex** [comment]
If I remember the conversation we (you, myself, and @davidChevrier) had when figuring this out, we agreed that that one didn't make sense and could be ignored until a sufficiently compelling reason for including it was presented.

**Comment by iainworkman** [comment]
Time Estimate: 64.5 Hours
