### ISSUE TITLE
Develop an EPICS IOC coordinator to control energy

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1561]
Once the mapping between energy and other parameters has been worked out, we will need to create an EPICS interface that allows changes to these values.  These should be standard high-level abstractions such as:

-------------------
- :Energy
- :Energy:fbk
- :Energy:status
- :Energy:stop

------------------
- :Tracking:Undulator
- :Tracking:ExitSlit

--------------------

As well as mapping the old AddOns grating and harmonic PVs to the new application.  This application will likely need to create its own unique base name so that it does not conflict with the existing application.

**Comment by dretrex** [comment]
@iainworkman, now that you've done some work on the other side of this, is this list missing anything you will need/want?

**Comment by iainworkman** [comment]
These seem fine for the first rev. If I encounter anything else while working on the pseudo-motor I'll let you know.

**Comment by dretrex** [comment]
Time Estimate: 1 hour

**Comment by iainworkman** [comment]
Time Estimate: 20 Hours
