### ISSUE TITLE
Continuous Motion Support

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1562]
Once the mapping of specific energies to lower level controls has been established, we'll need to provide support for continuous motion support.  This involves also being able to calculate the necessary velocities of the grating angle and undulator positions in order to scan the energy in a well behaved constantly increasing/decreasing manner.

Although many of the parameters will be constant and the same for the time being, this should include support for being able to set the __base velocity__, __velocity__, and the __acceleration__.

**Comment by iainworkman** [comment]
Time Estimate: 20 Hours
