### ISSUE TITLE
2b) Figure out the trapezoidal velocity profile

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1563]
Since the continuous motion mentioned in #1562 can never be at it's set velocity immediately, we will need to determine how the velocity profile varies across different parameter spaces.  This will mostly involve extensive testing once that piece has been completed.  Further investigation will be required in order to properly assess how tractable this problem is.

**Comment by iainworkman** [comment]
The work done on figuring out the nuances of both the undulator and the grating angle are both completed.

**Comment by dretrex** [comment]
I'm going to remove the "Investigation Required" label, would you be able to put a time estimate, @iainworkman?

**Comment by iainworkman** [comment]
Time Estimate: 28 Hours
