### ISSUE TITLE
Extend the EPICS energy application for non-standard choices

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1564]
Aside from the typical energy selection aspects of the monochromator, there are other aspects that will be required.  In no particular order, the following pieces will likely be a part of this extension:

- Switching to visible light.
    - Properly going back to position upon switching back from visible light.
- Create a set of warning PVs that can detect various error states of the monochromator.
- If possible, some mirror stripe coordination based on the reproducibility of moving those motors.
- Warnings due to the mirror stripe position.
- Undulator offset/detuning.

**Comment by iainworkman** [comment]
Much of this is done already, bar the visible light element. As such this is being rolled into #1567
