### ISSUE TITLE
Create a pseudo-motor control for moving the energy in AM

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1565]
Once all the math and properties are known, we'll need an AM control to move and coordinate all the pieces.  The first step will be doing single energy selections (analogous to most current controls).  It will contain a lot of the options and logic for "best case" moves mentioned in #1560 as those methods will be able to calculate what the best positions of the various controls are based on grating choice, optimized flux/resolution, etc.

**Comment by iainworkman** [comment]
Time Estimate: 35 Hours
