### ISSUE TITLE
2a) Extending the Energy pseudo-motor control to handle continuous movements

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1566]
Presumably, if the control developed in #1565 is well designed, this should hopefully be a rather straightforward extension of the control to handle the addition logic developed in #1562.  However, there is not a large knowledge base on generic continuous movement and this will likely involve a lot of ironing kinks out due to technical realities.

PR: #1704

**Comment by iainworkman** [comment]
Okay, so I've tested undulator motions coordinated with the grating angle over the three grating selections (forwards and backwards) and it is 'working'.

Performing rudimentary observations** on the motions have show:
- They seem to start at the same time. There is no obvious notable delay from either.
- The undulator seems to reach its target just before the grating angle. On all moves I tested this was 1s (+/- 0.2s) whether on a 10s or 20 move.

** cagetting the movement statuses of the undulator and grating angle, visually noting how synchronized they seem on start and then working out the delta time based on the epics outputs. I said rudimentary, didn't I?

**Comment by iainworkman** [comment]
To Do:
- [ ] Fix issue where the exit slit is being moved to the optimized position for the start, then the mean  position for the trajectory, wasting time.

**Comment by iainworkman** [comment]
To Do:
- [ ] Add energy trajectory PV to energy coordinator.
- [ ] Add widgets for energy trajectory to the SGMEnergyView.

**Comment by iainworkman** [comment]
Time Estimate: 36 hours
