### ISSUE TITLE
The JJ slit vertical controls on Side and Main do not have the same coordinate system.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1592]
On Side:
- As either control becomes larger, it is actually moving down.
- As either control becomes smaller, it is actually moving up.

On Main:
- As either control becomes smaller, it is actually moving down.
- As either control becomes larger, it is actually moving up.

The Main system is the preferred system for BioXAS, and the Side controls will be changed to adopt it. The JJ slit pseudomotor controls were built using the Side system, so they will have to be changed as well.

@XuetaoLiu-CLS @dretrex
I know that SXRMB uses the same JJ slit pseudomotor controls as used on BioXAS. Do you happen to know which system is used on SXRMB? 

There may need to be some additional changes to the general JJ slit pseudomotor controls that would allow for different coordinate systems to be used.

**Comment by dretrex** [comment]
I am unsure.  SXRMB might also have the same controls as the IDEAS JJ slits where they come with center and gap straight out of the driver. @epengr, my memory of your JJ slits is accurate, right?

In either case, if we could get the motor parameters that guarantee the behaviour we want we can update the system appropriately.  Can you paste the necessary parameters once you have them @helfrij?

**Comment by helfrij** [comment]
At the BioXAS meeting today, it was decided that the Side and Main JJ slits hardware orientation will be changed to the Side system (smaller values mean blade is moving up; larger values, blade moving down). This means that no Acquaman code will be changed, and SXRMB will not be affected.
