### ISSUE TITLE
Exporting Ge 32-el spectrum data to file, outside of scans

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1597]
The BioXAS team have been using the germanium detector on Side to help identify foreign material deposited on the M1 viewport. They have been using the detector interface in AM, manually acquiring data at a particular energy and examining the plotted results. They would like to be able to export the spectrum data to file.

**Comment by XuetaoLiu-CLS** [comment]
@dretrex I think #1191 can cover this request, right?

**Comment by dretrex** [comment]
Don't worry about it @XuetaoLiu-CLS.  I'm working on (and almost done) #1191 which will handle this issue at the same time.  Thanks for looking into it though!

**Comment by dretrex** [comment]
Er.  Yes.  I completely mis-read your comment.

**Comment by dretrex** [comment]
Handled in #1191.
