### ISSUE TITLE
REIXS XES image binning bad initial axis scale

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1605]
The changes to this AB result in the initial axis values for a new scan being incorrect.  With the binning set to 2 by default, the axis is initially twice as long as it should be.  Changing the binning value triggers a update and resolves the problem.

**Comment by dretrex** [comment]
Sounds like an initialization problem.

**Comment by epengr** [comment]
Why, yes.  Yes it does.

**Comment by dretrex** [comment]
Done in #1608.  Time estimate?  I accounted for mine inside the pull request.

**Comment by epengr** [comment]
Time Estimate: 3 hours
