### ISSUE TITLE
Add ability to set the control and detector selection options in AMGenericStepScanConfigurationView

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1606]
Right now, I believe AMGenericStepScanConfigurationView shows all controls and all detectors exposed in the beamline class. It would be handy to be able to have the option of showing only some of those controls/detectors, as necessary.

This would likely mean adding two additional constructor arguments, saving lists of currently displayed controls and detectors, and providing getters and setters for each of these lists.

**Comment by dretrex** [comment]
Good idea.  I think this would be the case of making another constructor with the extra options where the old constructor uses the full list.  Or defaulted arguments are a good option as well.

**Comment by helfrij** [comment]
Time estimate: 2 hours.
