### ISSUE TITLE
changes for AMPVControl required by Acquaman Data Server

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1616]
For AMDS, there are some changes on AMPVControl
- add AMWaveformBinningSinglePVControl
- add move(QString stringSetPoint) for AMPVControl

**Comment by dretrex** [comment]
Can you elaborate on the necessary changes?  We need to be really careful when modifying fundamental classes like AMPVControl to ensure no emergent negative behaviours rear their ugly heads! :)

**Comment by XuetaoLiu-CLS** [comment]
@dretrex I just listed the changes required seconds ago. It won't affect the current usages. We need to add a new class and a new overloaded function

**Comment by dretrex** [comment]
Haha, alright.  I'm just too quick! ;)

**Comment by XuetaoLiu-CLS** [comment]
https://github.com/acquaman/acquaman/pull/1658

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 0.5 hours
