### ISSUE TITLE
Disable scan state controls when they aren't able to be changed.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1628]
Brian B. attempted to pause a scan on BioXASMain, but the scan didn't actually pause. The application continued with the scan and it collected and exported the scan data, and then froze when the scan should have ended. The scan data can be viewed as normal when the application is closed and reopened.

**Comment by helfrij** [comment]
Talked to Brian B. more about this, and may likely be caused by one of two things:
- 'Pause' button was pressed during scan initialization
- scan was paused to change low-level bragg motor settings on EDM screen.

I was able to successfully reproduce the error by pressing 'Pause' during scan initialization. It looks like the application doesn't actually freeze, but in the workflow the scan still appears to be running and can't be stopped/cancelled. Application must be restarted to start other scans.

@dretrex, is pausing scans that are initializing something worth looking into?

**Comment by helfrij** [comment]
This was discussed at the BioXAS meeting this morning. A better solution right now is to disable pause/resume/skip buttons when they can't be used: during scan initialization and cleanup.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 3 days
