### ISSUE TITLE
Beam on/off controls for BioXAS

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1630]
It would be useful to have a pseudomotor-type control (or a collection of controls) for each of the endstation applications that keeps track of the current state of all beamline shutters as they apply to a particular endstation. The controls themselves may involve a little bit of logic, as there are a few different states to consider. Solution would require implementations for Side and Main only, but it may be useful to consider how Imaging would be implemented too. It would also be useful to have a way to visualize why a control is in a particular state, as a diagnostic.

<b>BioXAS</b> - on:
- all front-end photon and safety shutters open
- all Side, Main, Imaging valves open

BioXAS - off:
- if BioXAS - on conditions aren't met.
- if we wanted to turn all three beamlines off, would close PSH2.

<b>BioXAS Side</b> - beam available:
- BioXAS - on
- Side pre-mirror mask open
- Side pre-mono mask open

BioXAS Side - beam not available:
- if any BioXAS Side - available conditions aren't met.
- if we wanted to turn Side off, would close pre-mirror mask.

BioXAS Side - beam on
- BioXAS Side - available
- Side endstation safety shutter open

BioXAS Side - beam off:
- if any BioXAS Side - on conditions aren't met.
- if we wanted to stop beam, would close endstation safety shutter.

<b>BioXAS Main</b> - beam available
- BioXAS - on
- Main pre-mirror mask open
- Main pre-mono mask open

BioXAS Main - beam not available
- if any BioXAS Main - available conditions aren't met.
- if we wanted to make beam not available, would close pre-mirror mask.

BioXAS Main - beam on
- BioXAS Main - available
- Main endstation safety shutter open

BioXAS Main - beam off
- if any BioXAS Main - on conditions aren't met.
- if we wanted to stop beam, would close endstation safety shutter.

<b>BioXAS Imaging</b> - beam available
- BioXAS - on
- Imaging pre-mono mask open

BioXAS Imaging - beam not available
- if any BioXAS Imaging - available conditions aren't met.
- if we wanted to turn Imaging off, we could open the undulator to max gap.

BioXAS Imaging - beam on
- BioXAS Imaging - available
- Imaging endstation safety shutter open

BioXAS Imaging - beam off
- if any BioXAS Imaging - on conditions aren't met.
- if we wanted to stop beam, would close endstation safety shutter.

**Comment by XuetaoLiu-CLS** [comment]
@helfrij 
We have `AMAction3*createBeamOnActions() const` and `AMAction3*createBeamOffActions() const` functions in class `SXRMBBeamline`. I'm wondering whether we should make those two functions virtual functions in class `CLSBeamline`?

**Comment by helfrij** [comment]
@XuetaoLiu-CLS 
I think there is a ```createBeamOffActions()``` equivalent that's already virtual in AMBeamline: ```createTurnOffBeamActions()```. There is no 'beam on' version though. Maybe it's worth considering adding one to this class?

For this particular issue, the team on BioXAS want to have controls for varying degrees of 'on' or 'off'--they want to know whether there is beam in the SOE, whether it reaches each beamline POE, or whether it makes it past the front-end (for each of the beamlines). A total 'beam on' or 'beam off' action would probably be implemented as a move of one of these controls, once they're developed.

**Comment by helfrij** [comment]
This issue is for the implementation of the beam on/off controls for Side only.

Time Estimate: 1 month.
