### ISSUE TITLE
REIXS: In plane sample moves lose alignment if a limit is hit

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1634]
More or a conceptual bug than a software bug, but the in-plane moves need to be made aware of the "other" axis limits in some way, either to warn that the in-plane move failed or to prevent/stop one axis moving when the other is on a limit.

**Comment by dretrex** [comment]
Is this an AM issue or an underlying issue that you hope to solve using AM?

**Comment by epengr** [comment]
It's an issue with the way AM is using one button press to move two motors to keep the move in an arbitrary plane, but not paying attention to what happens after commanding the move.  (this was the feature added in #1525)

I'd say yes, It's an AM issue.

**Comment by dretrex** [comment]
Ah, okay.

**Comment by epengr** [comment]
@iainworkman, will this issue be eliminated when you implement #1852?  If so, it could be closed and rolled into that issue?

**Comment by iainworkman** [comment]
Should be. It can be closed.

Iain

**Comment by iainworkman** [comment]
Done in #1852
