### ISSUE TITLE
BioXAS XAS scan configuration time estimate doesn't correctly report estimates for scans going 'backwards.'

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1638]
For example, an XAS scan of the following region will be estimated to complete in -18 seconds.

Start: 10eV
Delta: -1eV
End: -10eV

The estimate should be a positive number. Also, should the value be 21?

**Comment by dretrex** [comment]
You are correct, is there some extra time added from something?  21 should be the time.

**Comment by dretrex** [comment]
This will be handled in #1399 which I will be working on shortly.
