### ISSUE TITLE
SXRMB: Change default voltage range for SR570

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1641]
There is a request to change the voltage range of the SR570's because the way they recommend users to setup their samples involves being a lower than the current setup (which I believe is 1.0V - 4.5V).  The new requested range is 0.1V - 2.0V.

**Comment by XuetaoLiu-CLS** [comment]
https://github.com/acquaman/acquaman/pull/1659

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 5 minutes
