### ISSUE TITLE
Add attempt move when within tolerance logic to Pseudo Motor

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1646]
The pseudo motor control ignores a move if it within tolerance, even if attemptMoveWhenWithinTolerance_ is set to true. Need to add a check for this in the pseudo motor's move() function.

**Comment by dretrex** [comment]
Hey @iainworkman, did we end up doing this inside of SGM upgrade?

**Comment by iainworkman** [comment]
Yes, this fix is in the SGM Upgrade

**Comment by dretrex** [comment]
That's what I thought.  I'm going to close this one out then.
