### ISSUE TITLE
Implement hasChild method in AMControl

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1647]
It would be handy to be able to query an AMControl for whether it has a given control as a child. 

This could be implemented by:
- if the control has no children: return false.
- if the control has children: iterate through children, comparing each child to the given control and additionally asking whether the child has the given control as a child. When the control is found or iteration is complete, return result.

**Comment by dretrex** [comment]
Based on your description, this is a `hasChild()` and `childAt()` kind of thing?

**Comment by helfrij** [comment]
I was thinking of just iterating through the list of children internally and returning the boolean for whether a particular control was found. But a childAt() method (and maybe a childCount()?) could certainly be added.

**Comment by helfrij** [comment]
AMControl already has childControlCount() and childControlAt() implemented. Do these existing functions address your concern, @dretrex?

**Comment by dretrex** [comment]
Yeah.  In light of the methods that exist already, would `hasChild()` just be `childControlCount() != 0`?

**Comment by helfrij** [comment]
I'd like hasChild to return true if a given control is present in the list of children (or in the list of a child's children): ````bool hasChild(AMControl* control)````

**Comment by dretrex** [comment]
Oh!  Yes, of course.  That makes a lot of sense.

**Comment by helfrij** [comment]
Time Estimate: 30 minutes.
