### ISSUE TITLE
Implement listening for LN2 detector dewer filling state

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1649]
BioXAS has an LN2 dewer on each beamline that fills using an automated system. Right now, that automated system causes the dewers to fill:
- at injection time
- when the dewer level is below 30%.

The automated system may transition away from using injections to trigger fills, and in that case extra measures should be implemented to prevent data collection during a dewer fill.
- Users shouldn't be able to start a scan while the dewers on a particular beamline are filling.
- A running scan should pause if the dewers start filling mid-scan.

I think this could be implemented by adding a control to the beamline class for the dewer fill status pv, and checking the value of this control in the app controller.

**Comment by dretrex** [comment]
The automatic refilling has been removed recently with not a lot known on when/whether it will be reinstalled.  Closing the issue out.  If it becomes an issue in the future we'll revisit the issue.
