### ISSUE TITLE
SGM Commissioning tool cannot see AmptekSDD data any longer

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1657]
A few weeks ago it was possible to see the XRF spectra for regions in a 2D map.  Now it is not.  Selecting the 'Show Spectra' dialogue and AmptekSDD checkbox shows a row of zeros for the XRF data.  Additionally, Acquaman will crash when selecting a different data channel after having selected AmptekSDD1 in a scan window.

**Comment by dretrex** [comment]
Hey @iainworkman, can you look into this for me?  It might be related to some of the changes I made or something else has slipped through the cracks.  Let me know what you find.

**Comment by iainworkman** [comment]
Yeah, I can look at this. Could you provide a brief description of how the usage of this is supposed to work. I'm not super familiar with this aspect of the application. Is there anything I need to do prior  to running the scan, and how do I view these once the scan is run?

**Comment by dretrex** [comment]
Open up a scan that @regiert has taken recently and click "Show Spectra".  It should pop up another window.  Click around on different places and you should see the XRF spectrum changing based on where you click.  For the crash, run in the debugger and see if the line number makes sense after it crashes.

**Comment by regiert** [comment]
After some testing, we noticed that the problem was gone for the test scans we were running.  Went back to the original measurement region and the problem was back.  Noticed that the scan where the Amptek data wasn't present was being run from higher values to lower values in position (13 to 9 mm in X, 4 to 1 mm in Y).  Switched the region to run from lower values to higher values (9 to 13 mm in X, 1 to 4 mm in Y) and the Amptek data is back.

I would say that this problem is related to the larger issue of scan orientation and data presentation which I believe is already a noted issue.

**Comment by dretrex** [comment]
Ah, yes.  It's on the list of things to be done by the end of the shutdown, but currently scanning negatively isn't supported in 2D scans.

**Comment by dretrex** [comment]
Since this is encapsulated in another issue I'm closing this one out.
