### ISSUE TITLE
Add ability to stop controls in motion on BioXAS

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1660]
Yesterday, Gosia moved one of the mirror bend controls and wanted to stop/cancel the move before the move was complete. This control can provide 'stop' functionality but is displayed using an AMExtendedControlEditor, where I don't believe there is an interface for stopping moves.

One potential solution could be constructing a basic widget from scratch that includes a display for the current value and a stop button. This solution could be specific for the mirror bend controls, or more general. Pretty straightforward.

Another solution could be finding a way to add this functionality to AMExtendedControlEditor that makes sense, for controls that can stop.

**Comment by dretrex** [comment]
I really like the second solution.  If we can make the control editors encompass the standard control functionality (move, value, status, stop, if they are available) then I think we'll come out pretty far ahead.  I think if we also provide a means of hiding them even if they are available, that would also be a nice, robust solution.

**Comment by helfrij** [comment]
Done in #1819.

Time estimate: 1 hour
