### ISSUE TITLE
New implementation of mirror controls for BioXAS Side and Main

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1665]
The mirror pseudomotor controls for BioXAS are interrelated: a move in height changes roll and pitch, and the roll and pitch don't return to the exact positions they were at initially. The risk here is that 'error' (eg the difference between where they end up vs where they started) in the positions of the secondary controls is compounded for a series of moves.

David B. suggested that a possible solution would be to use setpoints instead of control value feedback when creating and executing move actions.

EDIT:
Have discussed this problem a little more with David B. It may be possible to improve mirror control move behaviors by making a small change in BioXASMirrorMotor, changing the returned value of zPosition() to setpoint() instead of value() (or providing some way to choose which value is desired). We will try this out when the shutdown starts next week.

EDIT:
The difference between the achieved setpoint and the desired setpoint is the result of parasitic motion between the three mirror motors, and it is significant for these mirrors. The 'setpoint vs feedback' solution wouldn't be good enough. The plan now is to characterize each mirror with a set of unique equations using a laser tracker for changes in roll, pitch, height, and yaw. These equations would be implemented in Acquaman, and replace the current generalized controls. 

EDIT:
Discussed using Alan D.'s mirror equations in the BioXAS/Acquaman meeting this morning, these take the coupled motion into account when calculating roll, pitch, and height for these mirrors.

EDIT:
Alan D's mirror equations will be used to implement new controls for BioXAS. They are not ready yet, work can start once the equations are available.

**Comment by dretrex** [comment]
Is it that you can't trust the values or is that the motors don't always make it to the setpoint after you issue a move?
As a small point, rather than change `zPosition()` to return the setpoint rather than the value, I would have two options such as `zPosition()` and `zSetpoint()` and then changing the dependent functions to use the setpoint rather than the value.  This will minimize confusion in the future if you look back on it that similar functions have different implementations under the hood.

**Comment by helfrij** [comment]
In a meeting this week, it was determined that the error in the current equations isn't large enough to warrant more time spent on making these equations usable, for now. Further discussion of the mirror controls will be in a new issue.
