### ISSUE TITLE
Standards wheel not responding to move commands

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1670]
Ian C. noticed today that the standards wheel does not respond to move requests made through the standards wheel view, but the wheel motor will move when the request is made through the EDM screen.

I recently re-enabled the standards wheel (it was disabled previously) and changed the hardcoded elements in BioXASSideBeamline to reflect the currently loaded standards, so this problem could be related to those changes. 

Some notes:
- PV name for wheel motor appears to be correct, matches the EDM screen name.
- The Side standards wheel object connects.
- CLSStandardsWheel::moveToIndex() is correctly being called in response to changes made through the view.
- It appears that the wheel control is being issued a move request with the appropriate position, but no change reflected in the EDM screen.
- No timeout error (or any other error) appears when moves are initiated from the view, but an error with code 13007 appears when a move action is initiated from the workflow.
- The EDM screen seems to always reports the control to be at both CW and CCW limits. The control is implemented as a CLSMAXvMotor in AM, which would likely pay attention to these limit statuses.

**Comment by helfrij** [comment]
Reimplementing the wheel control as an AMPVwStatusControl appears to fix the problem. This implementation wouldn't listen to the CW/CCW limit statuses, while the CLSMAXvMotorControl interface does. I think these statuses were likely the source of the trouble.

**Comment by helfrij** [comment]
Time Estimate: 1 hour.

**Comment by dretrex** [comment]
I think this is something that we should talk to Dave B. about.  If the limits are always on, that is likely indicative of something wrong.  I'd prefer not to use this change until knowing for certain that it is the best way to go.

**Comment by helfrij** [comment]
Talked to David B. today. The motor is indeed malfunctioning if the limit statuses are showing "at limit"--there aren't any limits implemented for this motor. There is something wrong happening with the motor software, but not sure what yet. This wouldn't be caused by someone bumping or forcing the motor.

The lower-level motor software will be restarted, which is expected to return the control to normal. For Acquaman, I think it would be best to change the motor control back into a CLSMAXvMotor so we will be notified if something strange happens again.

**Comment by dretrex** [comment]
Great!  I am definitely in favour of this course of action.  Thanks for looking into it @helfrij.

**Comment by dretrex** [comment]
Due to this, we could probably close this issue since there are no actual changes that need to take place.  Is that correct, @helfrij?

**Comment by helfrij** [comment]
I jumped the gun when we first discovered the problem and published the initial change to AMPVwStatusControl, to get the control up and running quickly. Would either need to revert those changes or publish new changes before closing this issue out completely.

**Comment by dretrex** [comment]
Okay.  Either is fine.  Then close the issue and post a time estimate like usual.

**Comment by helfrij** [comment]
I've reverted to the previous version of CLSStandardsWheel, which uses the CLSMAXvMotorControl interface for the wheel control. (d0095c39d259f00319f87d738b241f0747b0acb5)

Estimate below is meant to include all time spent on this issue, including the original solution.

Time Estimate: 1.5 hours
