### ISSUE TITLE
Mapping bi-state controls to string values

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1671]
The BioXAS valves view (created as part of #1630) features columns of control editors for each of the valves on a particular beamline. Right now, all of the controls are instances of CLSBiStateControl and these editors display numbers for the current values of the controls, 0 -> 5. It would make reading information from this view more meaningful if the editors displayed a string representation for these values (Open, Closed, None, Error).

I think this could be accomplished by creating a class (BioXASBiStateControl?) that implements AMPseudoMotorControl and maps the current value of a CLSBiStateControl to its string counterpart.

It may also be possible to set enum names in CLSBiStateControl.

EDIT:
This issue may be solved by modifying CLSBiStateControl so that it inherits from the new AMEnumeratedControl family of classes.

**Comment by dretrex** [comment]
I think setting the enum names in CLSBiStateControl would be the better way to go rather than making a separate AMPseudoMotorControl.

**Comment by helfrij** [comment]
Done in #1931.

Time Estimate: 5 hours.
