### ISSUE TITLE
SGM data recorder needs to monitor fast and slow counts and other meta data

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1677]
In order to use pileup rejection, the fast and slow counts from the SDD123 need to be stored in the data file.  Other parameter data from each detector should also be made available for storage.  I suspect this is done for other silicon drift detectors around the facility, but it was not done for the Ampteks - although the number of fast and slow counts are read out from the detector, they were not stored in the data files.

**Comment by davidChevrier** [comment]
In addition to fast and slow counts there are some other pieces of "status data" (as the Amptek calls it) that we'll need to extract from the server.
