### ISSUE TITLE
1) Hexapod TTL Scalar Research

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1678]
1) We need to properly characterize the profile of the pulses obtained from the TTL signal we've acquired from the hexapod into the scalar, in order that we can properly coordinate the data with that acquired from the hexapod's recorded data (#1462).

**Comment by davidChevrier** [comment]
The "research" has been done. We can see those TTL pulses on the scaler. It seems to be fairly consistent. The rest of the work needs to be done in #1691

**Comment by davidChevrier** [comment]
Time Estimate: 4 hours
