### ISSUE TITLE
3) Amptek Continuous Data API

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1679]
In order to obtain continuous data from the Amptek's we will need some interface which we can implement in Acquaman to collect continuous data from a detector. There are some artefacts of continuous acquisition already within the AMXRFDetector/AMDetector hierarchy, such as  canContinuousAcquire(), but I believe the actual implementation of this does not yet exist.

**Comment by davidChevrier** [comment]
Time Estimate: 19 hours
