### ISSUE TITLE
6) AM Dataserver PV Implementation

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1681]
In order to provide the most flexibility for future uses of the data server it is necessary to have an implementation which can simply monitor specific PVs, buffer this data, and then provide access to it through the usual consistent data server interface.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 8 hours

**Comment by XuetaoLiu-CLS** [comment]
https://github.com/acquaman/AcquamanDataServer/pull/104
