### ISSUE TITLE
15) Continuous Scan Infrastructure (2D)

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1685]
Once the hexapod continuous movement and data retrieval are fully implemented it will be necessary to create an interface through which continuous 2d scans can be performed upon a provided generic control.

**Comment by iainworkman** [comment]
With the hexapod, is it the issue with it reporting done to early related to regular moves or the continuous moves? If it's the continuous moves is it reporting that the move is done before the actual motions have stopped, or before it is done retrieving the recorder data?

**Comment by dretrex** [comment]
Situation is as follows:
1) Do a normal move for the outer loop.
2) Do the setup for the continuous move. (part of inner loop)
3) Do the continuous move. (part of inner loop)

It is failing on step 2 because it tries to do the setup moves but don't do anything and time out because the controller says that the hexapod is already moving.

**Comment by iainworkman** [comment]
It may be something that has been introduced with the data recorder. I had to make some alterations with that to ensure that the moving state was not set to done until the recorded data was retrieved. It is quite possible that this had messed something up with the setting of movement states during moves in which the data recorder is turned off.

**Comment by dretrex** [comment]
Definitely possible.

**Comment by iainworkman** [comment]
You could possible turn the recorder off with a 
```caput HXPD1611-4-I10-01:recorder:active 0```
do a regular move with a terminal having
```camonitor HXPD1611-4-I10-01:X:mm:fbk HXPD1611-4-I10-01:X:status```
for the X Y and Z and see if there appears to be any cases where the status gets set back to MOVE DONE before all the feedbacks are done reporting.

I've tested this in the past but it is quite possible something has changed since.

**Comment by iainworkman** [comment]
If the wait action is 'fixing' the issue for now I would simply suggest leaving it in place for now, and I will have a look at it come Monday. From your description I imagine it will be easy enough to replicate with a loop action full of regular moves.
