### ISSUE TITLE
17) Time Evolution Strip Tool

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1687]
With the data server providing a generic interface for obtaining continuous data, it is required that an updated strip tool application be created which can visualize the continuous data to users. The following features would be a few of the general targets (though not necessarily for a first rev):

- The ability to select multiple servers which can be connected to.
- The ability to 'poll' the server with an introspection request so the sources which it provides can be displayed to the user.
- The ability to [connect to/disconnect from] data channels.
- The ability to visualize 1d lines and 2d maps in an evolving manner.

**Comment by dretrex** [comment]
Time Estimate: 30 hours

**Comment by dretrex** [comment]
Done in #1756.
