### ISSUE TITLE
18) Amptek Cooling Automation

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1688]
The ability for the cooling to be triggered on/off on the Amptek detectors is required, in order that they can be prevented from damage should the windows break during a venting procedure.

**Comment by regiert** [comment]
Turning off the cooling and the HV would be a better way to prevent damage
to the detector.  This would be analogous to powering down the preamplifier
but leaving the DP5/PX5 electronics running.  This is an option in the
DPPMCA software provided by Amptek but I am not sure if this (powering down
the preamp) is an option in the current driver.  We will need to look at
the command set for the Ampteks and see if this is already available or if
it can be added.

Tom Regier, PhD.
Beamline Scientist, SGM Beamline
Canadian Light Source, Inc.
tom.regier@lightsource.ca
(306) 657 - 3733

**Comment by davidChevrier** [comment]
Waiting on chamber venting automation which is no in Clean Up milestone.
