### ISSUE TITLE
19) Diagnostic Ladder Controls

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1689]
There are new diagnostic ladders which have been added to the beamline as part of the upgrade. These will need control interfaces (AMPseudoMotors?) which can easily be worked with inside Acquaman.

**Comment by regiert** [comment]
The ladders are all on CLS motors (no feedback).  The should have their
velocity PV's (:divisor) set to 1 so they move as fast as possible - this
has been tested and their is no problem running at these velocities.  All
of these motors have been calibrated using the CCW limit switch as a zero
reference.  This means that the calibration procedure should be that you
run the motors to the CCW and put a 1 to the :isCalib PV.  The calibration
should not have to be run regularily as these motors do not appear to lose
steps during normal operation.  When the motor crate/IOC is power cycled,
the calibration will have to be performed.  Acquaman should have a way of
recognizing that the calibration is void and either notify the operator or
automatically run the calibration procedure.

XAS diagnostic ladder (upstream of KB) SMTR16114I1014- just use centre
positions

0 - Upper limit - Vanadium filter
6700 to 14400 - Photodiode
17600 to 23600 - Au Mesh
31200 to 37200 - Pinhole
43000 to 49500 - Passthrough
68000 - Phosphor

XPS diagnostic ladder (upstream of EA1) SMTR16114I1012

0 - 3400 Upper limit - Photodiode
10000 - 14000 - Vanadium Filter
18000 - 24000 - Au Mesh
26000 and higher - Retracted from beam

Bypass diagnostic ladder SMTR16114I1013

0 - Upper limit - Slit
12000 - Passthrough
27000 - Phosphor

Note that the values provided for the different positions may need to be
adjusted and should be allowed to be reconfigured by beamline staff.  This
would suggest that a configuration screen is required for each ladder that
contains the step values for the different positions and an option to
recalibrate (drive to CCW limit and set :isCalib).


Tom Regier, PhD.
Beamline Scientist, SGM Beamline
Canadian Light Source, Inc.
tom.regier@lightsource.ca
(306) 657 - 3733

**Comment by helfrij** [comment]
Initial implementation completed in #1707.
Time Estimate: 5 hours
