### ISSUE TITLE
9) Data Recorder/ Scalar Pulse Alignment

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1691]
Using the TTL signal acquired from the scalar, and the data recorder information acquired from the hexapod driver server, there needs to be some work done aligning the beginning and end of a motion with the data within the data recorder in such a way that the position at a given time can be known correctly.

**Comment by davidChevrier** [comment]
@iainworkman what was your time estimate on this one?
Because I added the necessary interpolation algorithms into this one, it kind of exploded in terms of time. Also really had to bring the 1D Line Scan along for the ride to make sure it was working.
Time Estimate: 35.5 Hours

**Comment by iainworkman** [comment]
Time Estimate: 16 Hours
