### ISSUE TITLE
13) Vacuum/Venting Automation System

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1698]
Once the questions regarding the controls work on the vacuum system is complete it will be required to implement an automated procedure for safely venting the end station chamber.

**Comment by helfrij** [comment]
Description of desired specifications in #1682.

**Comment by helfrij** [comment]
Spent time working on the automation system as a whole (#1726), and then on cleaning this code up to provide a functional view (#1773) without automation.

Time Estimate: 2 weeks
