### ISSUE TITLE
Generalize Use of AMDS clientAppController for AMAppController beamline applications

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1705]
Once #1679 is merged in, there will be an immediate need to generalize the use of the AMDS clientAppController. Right now, it's created directly in the instance of the CLSAmptekSDD123DetectorNew class, which would lead to one created for every detector instance. It really needs to be that they all share one between them (as well as the scaler and PV server eventually).

 - Need one instance of the clientAppController ... probably as a singleton paradigm
 - Hopefully the onNetworkSessionOpening(), onNetworkSessionOpened(), onNewServerConnected(), and onServerError() can be moved to that class and just have a signal for when data requests are ready
 - @XuetaoLiu-CLS can likely look over some of the weaker usages I've made of AMDS classes and fix them up

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 4 hours
