### ISSUE TITLE
Change Amptek AMDS types

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1708]
Right now it looks like the underlying type is double. The Ampteks are definitely integer types of some sort ... and I would guess likely quint16 - but we can figure that out.

The changes will need to be made on both the AM side and the AMDS side. This can wait until the cleanup phase.

**Comment by dretrex** [comment]
Something to keep in mind is that the AM side won't be able to change much as it will have to cast every value from a quint16 to double anyway as part of our single `values()` implementation for all mass data transfer.

**Comment by XuetaoLiu-CLS** [comment]
Changes for AMDS: https://github.com/acquaman/AcquamanDataServer/pull/86

@davidChevrier do I need to modify the AM side? As @dretrex pointed out, AM side might use double.

**Comment by XuetaoLiu-CLS** [comment]
refer to  #1720, which will return double vectors so that the Acquaman side will use double and don't need to worry about the underline types.

Time estimates: 5mins
