### ISSUE TITLE
Create API for Coordinated Movement Controls

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1714]
I think that we're really close to being able to do this. We know of two controls like this right now in SGM: energy and hexapod. 

The API can be done through inheritance (ie,, add something to AMControl that just returns NULL/false for existing controls and subclass) or through encapsulation (add a new class that controls can have a member variable for that does the work).

Whatever the solution, it should be fairly quick to implement with no code change for existing controls.

API features should be:
(1) bool canPerformCoordinatedMovement()
(2) AMAction* createSetParameterActions(start, end, deltaTime)
(3) AMAction* createInitializeCoordiantedMovemenActionst()
(4) AMAction* createStartCoordinatedMovementActions()
(5) AMAction* createWaitForCompletionActions()

In the case of Energy, this is basically already in AMGenericScanActionControllerAssembler::generateActionTreeForContinuousMoveAxis()

We create the action lists as below:
We assume (1). (2) is done in lines 258 to 266. (3) is lines 244 to 255. (4) is lines 271 to 274. (5) is lines 278 to 285.

**Comment by iainworkman** [comment]
Time Estimate: 90 minutes
