### ISSUE TITLE
Make convenience function for writing AMDSClientDataRequest to file

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1715]
The AMDS classes are designed to be self-packaging to writing to TCP stream. We should be able to package them up at a binary file stream to write and read them the same way. We need a really lightweight way of doing this. 

We need to test that writing and reading works.

We don't need to do this on the AMDSServer side, there the TCP stream is what we want. We'll want to do this on the AMAppController (ie,, acquaman application) side.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimates: 10 hours
