### ISSUE TITLE
Clean Up SamplePre2013 warning in upgraded SGM application

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1717]
We're not using the sample system anymore, so we should see if we can get that warning to go away.

**Comment by dretrex** [comment]
Only REIXS uses it at all if I recall correctly. All the applications have been getting this error mon for years.

Sent from my iPhone

On Nov 16, 2015, at 9:00 AM, davidChevrier <notifications@github.com<mailto:notifications@github.com>> wrote:


We're not using the sample system anymore, so we should see if we can get that warning to go away.

-

**Comment by iainworkman** [comment]
When does this error appear, as I'm not getting it on startup?

**Comment by davidChevrier** [comment]
When you run a scan.

**Comment by dretrex** [comment]
I am also unable to reproduce this.  I'm going to close this issue until it resurfaces itself.

**Comment by dretrex** [comment]
Clarification, it is only a Debug error mon so it wouldn't be noticeable to a user.
