### ISSUE TITLE
Update AMDSFlatDataArray to provide generic double vector copy function

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1720]
By design, AMDSFlatDataArray stores specifically typed data. This reduces the memory footprint and the number of bytes written to the network. However, on the receiving end it costs a function like this:

dataHolderAsGenericFlatArrayDataHolder->dataArray().constVectorDouble().constData()

Where the real problem is that you need to know to call constVectorDouble() versus constVectorQuint16(), etc.

Since the receiving side is an Acquaman appController right now (and will be for the foreseeable future), we should implement something that returns a const QVector<double> no matter which underlying type is being used. To be clear, this function would be called on the client side (the server would still store and send the right - smaller - size of data). In the case of underlying double, this would just return the existing vector. For all other underlying types, this would require a conversion to be done and a new copied vector to be made. At this work needs to be done anyway, we might as well package it up nicely in the API.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 10 mins
