### ISSUE TITLE
SXRMB: some issues with SXRMB Acquaman

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1755]
- [x] MotorGroup view using scientific format to display the values, which is not user-friendly
- [x] when loading history data (21-6752), got the following errors (same as #1717.):
```
Debug: "AMCDFDataStore: Error retrieving single value from data store. (code -107)"
Debug: "in [AMSamplePre2013]: Could not load from database, the database id is invalid. Please report this problem to the Acquaman developers. (code -277004)"
```
- [x] Acquaman crashed when doing "view" --> "See Ambiant Sample Stage Motors"
- [x] ROI counts won't update for Bruker detector 
- [x] cannot beam on after injection
- [x] Slit View range incorrect. Should be up to 16mm (fully open)
- [x] EXAFS region scan: there is glitch data for the scan data, it happens when doing the K-space scanning.

**Comment by dretrex** [comment]
Hey @XuetaoLiu-CLS, the second error is the same as #1717.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 4 hours
