### ISSUE TITLE
Misc SGM Issues after deploy

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1774]
Using this issue as a place to tally all the issues covered so far. These will probably get broken up individualy, just wanted them in one place.
- [x] Undulator not moving
- [x] Need button for chamber lights
- [x] Energy coordinator control not getting values properly.
- [x] Redirect errors when moving the undulator velocity in the coordinator

**Comment by davidChevrier** [comment]
Time Estimate: 5 hours
