### ISSUE TITLE
Adding control of Zebra to BioXAS Side Acquaman

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1780]
The Zebra has been successfully installed on Side and is ready to be implemented in Acquaman.

**Comment by dretrex** [comment]
AND1 : Inverter for the fast shutter
OUT1 TTL : Xspress3
OUT1 NIM : Scaler
OUT2 TTL : Fast shutter

**Comment by dretrex** [comment]
Time Estimate: 10 hours
@davidChevrier can you put your time in here too while it's still "fresh"ish in your memory?

**Comment by davidChevrier** [comment]
Time Estimate: 7 hours

**Comment by dretrex** [comment]
[Zebra_full_logic.pdf](https://files.zenhub.io/569675227499d9997e332963)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by dretrex** [comment]
[Zebra_full_logic.pdf](https://files.zenhub.io/56967bb57499d9997e332a06)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by dretrex** [comment]
Done in #1796.

**Comment by helfrij** [comment]
TRG1607-601:SOFT_IN:B0.HIGH -> 0.01
TRG1607-601:SOFT_IN:B2.HIGH -> 0.01
