### ISSUE TITLE
Acquaman crashed when add "2D Summing" analysis tool for EXAFS scan

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1786]
Acquaman crashed when trying to add a "2D summing" analysis tool for EXAS scan. Crash stack tracking:
```
ls/home/sxrmb/beamline/programming/acquaman/source/application/AMCrashMonitorSupport.cpp:132
sigaction.c:0
/home/sxrmb/beamline/programming/acquaman/source/analysis/AM2DSummingAB.cpp:76
/home/sxrmb/beamline/programming/acquaman/source/dataman/AMAnalysisBlock.cpp:62
/home/sxrmb/beamline/programming/acquaman/source/ui/dataman/AMDataSourcesEditor.cpp:435
/home/sxrmb/beamline/programming/acquaman/build_files/moc_AMDataSourcesEditor.cpp:94
??:0
??:0
??:0
??:0
??:0
??:0
/home/sxrmb/beamline/programming/acquaman/source/application/SXRMB/SXRMBMain.cpp:54
```

crash happened in function ```setInputDataSourcesImplementation()``` of AM2DSummingAB.cpp, when trying to disconnect `valuesChanged(AMnDIndex, AMnDIndex)` signal.
```disconnect(inputSource_->signalSource(), SIGNAL(valuesChanged(AMnDIndex,AMnDIndex)), this, SLOT(onInputSourceValuesChanged(AMnDIndex,AMnDIndex)));```

@dretrex Does this look familiar with you? Thx

**Comment by dretrex** [comment]
It's because `inputSource_` isn't being initialized in the constructor.

**Comment by dretrex** [comment]
Was this issue not fixed earlier this week @XuetaoLiu-CLS?

**Comment by XuetaoLiu-CLS** [comment]
It should be fixed. But the users didn't test it yet.

**Comment by helfrij** [comment]
Seen today on BioXAS.

**Comment by XuetaoLiu-CLS** [comment]
@helfrij Thx. I just tested on SXRMB. It still exists. It will crash when adding "2D-summing" during scan and won't crash after the scan is finished.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimates: 3 days
