### ISSUE TITLE
Create stop/abort buttons for the M1 mirror, M2 mirror, mono

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1792]
It would be really useful (and potentially equipment-saving) to have a stop button for some devices on BioXAS Side and Main that immediately aborts moves for all motors on that particular device (no retries). The devices of interest are M1 mirror, M2 mirror, and mono, for now.

This issue is related to #1660, but is for all controls instead of for an individual control in an editor.

It would be helpful too if controls could listen for clicks to the EDM 'stop' or 'kill' buttons and stop motor moves without retries, but this may be best handled in a separate issue.

**Comment by dretrex** [comment]
I don't think I understand the listening to EDM stop or kill buttons.  Strictly speaking, that's not possible, what would be the benefit of listening to the stop or kill buttons (they also, depending on their implementation, don't do anything differently)?  The stop PV's also are momentary "write 1 then auto-reset to 0".

As for the first comment, is the no retries the AM retries or the motor driver retries while in closed loop mode?  If it's the AM side, you can always just set the control actions for those motors to only have no retries rather than having to implement a stop-ignore retry mechanism.

**Comment by epengr** [comment]
Didn't @davidChevrier add some auto re-targeting type move behavior to help with sample positioning on SGM?

Are those mirror/mono motors in closed-loop at the controller level or is AM doing something like that?

Regardless, AM can have queued moves in a variety of ways, and it might be a good idea to stop everything if someone commands a stop in a lower level control.  It should be possible for AM to monitor the :stop and :kill PVs and use a value changed there to trigger a cancel action / pause workflow / etc?

**Comment by dretrex** [comment]
These controls should be stopped from AM if they are initiated from there.  I don't mean that it's impossible for the :stop and :kill PVs aren't possible to listen to, but I do think it's the wrong way to approach the problem.

**Comment by dretrex** [comment]
The auto retry was added by @davidChevrier to help with the fact that motors will report being done moving before stopping which was causing errors for all scans.

**Comment by epengr** [comment]
*should* be, yes.  I discussed this with @helfrij yesterday, and the issue is with coordinated moves.  If you have 3 mono motors moving in sync and someone hits stop on one of them on an EDM screen, it's best if AM doesn't just keep doing what it was doing - particularly if there's a collision risk.  This is a safety feature, not a feature feature...

**Comment by dretrex** [comment]
But that's the exact point.  If you are doing a coordinated move you should be stopping it from the thing doing the coordinated move.

**Comment by epengr** [comment]
In an ideal world, they would stop it from there. But when we're talking about a mouse click that can possible destroy a mono, it seems like a reasonable step to protect the equipment?

**Comment by dretrex** [comment]
But my argument is that the only people who would have the knowledge to do that stop incorrectly are the people who would know better (I.e. Beamline staff). There should be no reason a visiting scientist should have only one EDM screen open enabling them to destroy equipment.

Sent from my iPhone

On Dec 11, 2015, at 9:31 AM, David Muir <notifications@github.com<mailto:notifications@github.com>> wrote:


In an ideal world, they would stop it from there. But when we're talking about a mouse click that can possible destroy a mono, it seems like a reasonable step to protect the equipment?

-

**Comment by helfrij** [comment]
The problem was caused by member of beamline staff; they may know better, but accidents happen and there is the very real risk on BioXAS that equipment can be damaged as a consequence, particularly for the M1, mono, and M2.

What happened was that a bad value (but an allowed value, technically) was set in a control editor, and there was no way to abort the move once it began. They panicked, found the relevant EDM screens eventually, clicked the stop button for all moving motors, they stopped... but then the move retries started up and the motors started moving again. More panic. The move was not stopped successfully, but fortunately nothing was damaged.

There are many different ways to tackle this problem. Adding a big ugly stop button to the views for these devices is not my preferred solution, but is something that can be thrown together relatively quickly--a stopgap solution until maybe we can discuss as a group what some better options are.

**Comment by helfrij** [comment]
This issue about the stop buttons is handled in #1793.
Time Estimate: 1 day.
