### ISSUE TITLE
Turning off 'Launch scan in new window' during scan causes a crash.

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1800]
Whenever 'Launch scan in new window' is unchecked during a scan or workflow, acquaman will crash.  

Edit (Iain): Split desired behaviour feature into #1816

**Comment by iainworkman** [comment]
I cleared the investigation required label, as that was related to the feature request. Stopping the crash is a separate issue which needs its own estimate.

**Comment by dretrex** [comment]
Hey @iainworkman, did you get a chance to look at this?

**Comment by iainworkman** [comment]
Not yet, no.
