### ISSUE TITLE
SR570 gains are not set correctly from Acquaman

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1802]
The behaviour of the buttons that set the SR570 gains is not correct and using the advanced view for the gains does not work.  Pressing the increase or decrease gain buttons results in the gains moving toward the highest gain setting and then the gain cannot be decreased.  Trying to set specific gain values in the advanced settings results in the gains being set to seemingly odd values.  This could be a problem with Acquaman or a problem with the IOC software.  If it is working on other beamlines (SXRMB) we should check out if there are differences.

**Comment by iainworkman** [comment]
Time Estimate: 3.25 Hours
@XuetaoLiu-CLS Is this closed out now?

**Comment by XuetaoLiu-CLS** [comment]
@iainworkman yes, we should close this out since it is duplicated with #1824. And the fix is as I mentioned in #1824. I had a quick test yesterday with my suggestions. It should fix the issues.
