### ISSUE TITLE
Control editor refactor

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1809]
Refactoring the control editors is something we've discussed a little as a group. I thought I'd start a thread where we can gather together current issues related to control editors:
- #1721 
- #1660
- ...

As well, it might be useful to have a list of things that we expect a generic control editor should be able to do:
- inform user if control is not connected, or can't be measured.
- display current value, for controls that can be measured.
- allow user to set a value setpoint and initiate moves, for controls that can be moved.
- prevent user from moving control to values that are outside the value min/max range.
- display enumerated values correctly, if a control identifies itself as enumerated.
- provide a means to stop controls that are in motion and support stopping.
- inform a user of move progress, especially important for controls where moves take time.
- display control units
- ...

As @iainworkman suggested, it may be best to approach a control editor refactor as developing a collection of smaller, self-contained widgets that could be put together to build either a single generic control editor (eg. AMControlEditor) or specific editors (eg. BioXASSSRLMonochromatorRegionControlEditor), or both.

**Comment by dretrex** [comment]
Another way would be to focus on a particular aspects as their own issues.
