### ISSUE TITLE
SGM: SR570 sens_put will be forced to change to -1 when Acquaman is running

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1822]
When Acquaman is running, change the value of sens_put will force to change the value to -1, which will put the SR570 IOC app into an unrecoverable stated.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 3 hours

**Comment by iainworkman** [comment]
Time Estimate: 3.25 Hours
