### ISSUE TITLE
SGM Beamline test procedure

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1830]
The following set of scans will be considered a full stress test of the beamline.  In the future, this could be combined with a suitable sample (containing known amounts of C, Fe, Na and Si) for a QA test of both beamline performance and software.

10 x 270 to 320 eV in 30 seconds (slew) on LEG
10 x 270 to 320 eV in 10 seconds (slew) on LEG
2 x 270 to 320 eV by 0.1 eV (step) on LEG
2 x 690 to 740 eV in 30 seconds (slew) on LEG
2 x 690 to 740 eV in 30 seconds (slew) on MEG
2 x 1050 to 1150 eV in 30 seconds (slew) on MEG
1 x 1050 to 1150 eV in 0.5 eV (step) on MEG
2 x 1050 to 1150 in 30 seconds (slew) HEG 1st harmonic
~~1 x 1830 to 1900 in 30 seconds (slew) HEG 1st harmonic~~ Removed (See below)
10 x 1830 to 1900 in 30 seconds (slew) HEG 3rd harmonic
1 x 1830 to 2000 in 0.5 eV eV (step) HEG 3rd harmonic

**Comment by davidChevrier** [comment]
Hey @regiert and @iainworkman 
From our conversation today, is it possible to do the 
"1 x 1830 to 1900 in 30 seconds (slew) HEG 1st harmonic"
That seems like it would be beyond the energy values where the first harmonic equation gives reasonable results. Thoughts?

**Comment by iainworkman** [comment]
I can check this out today. I have a separate test application which allows me to interact with the class used to perform the energy calculations without moving anything.

**Comment by iainworkman** [comment]
Results:

 Energy | Harmonic | Grating | Resultant Undulator Position 
--- | --- | --- | ---
1830 eV | Third | High | 20.77mm
1900 eV | Third | High | 21.18mm

**Comment by davidChevrier** [comment]
Yeah, I think the more pressing matter is HEG and 1st harmonic for the 1830-1900eV range.

**Comment by iainworkman** [comment]
Here are the values for the undulator position for both harmonics across a range of energies from 200 eV to 3000 eV. As you can see there is an asymptote around 1750 eV for the first harmonic. @regiert Is the general shape for these (other than the obvious error with values > 1750 on the first) about right?
 
![undposfirstharmonic](https://cloud.githubusercontent.com/assets/7461599/12298206/8c048004-b9d6-11e5-8d68-a27249d33b4e.png)
![undposthirdharmonic](https://cloud.githubusercontent.com/assets/7461599/12298207/9366da04-b9d6-11e5-9882-4695048dbd27.png)

**Comment by regiert** [comment]
We can remove the HEG 1st harmonic scan from 1830 to 1900 eV from the test
scan list.  It is clearly not possible.  My mistake.

**Comment by davidChevrier** [comment]
We're holding onto this issue for information. It will be closed and not tracked though.
