### ISSUE TITLE
Ensure Zebra is properly calibrated on program start

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1841]
Since everything scanning related hinges on the Zebra being setup correctly, it is pertinent to make sure that a couple settings are setup as needed after AM boots up.  The various inputs, outputs, and logic blocks should be connected as found in [Zebra_full_logic.pdf](https://files.zenhub.io/5696dcf7ecfb82383415a966) and a couple extra things:

- the .HIGH field for the soft input 1 and 3 PVs should be set to 0.01
- the trigger on is set to RISING EDGE for both Pulse 1 and Pulse 3

**Comment by helfrij** [comment]
Hey @dretrex, quick question: what is the .HIGH field here exactly? What does it physically mean?

**Comment by dretrex** [comment]
It means how long, in seconds, the value should stay at a non-zero value.

**Comment by helfrij** [comment]
Done in #1905.

Time Estimate: 2 hours.
