### ISSUE TITLE
Zebra Pulse 1 module needs to be set in scan initialization

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1842]
The Pulse 1 module (which is connected to the fast shutter) needs to be set to the same value of time as the detectors.  The solution is not quite as simple as setting it in the initialization because it needs to be dynamically set when doing EXAFS regions.  Maybe tying it directly to the Ge or scaler time would be a good idea?

**Comment by dretrex** [comment]
This was done in #1853.  Time estimate @helfrij?

**Comment by helfrij** [comment]
Time Estimate: 2 hours.
