### ISSUE TITLE
Fast shutter encapsulation

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1843]
The fast shutter should be encapsulated in a standard AM way now that we have a means of changing its state and having an effective status.  This should then be added to the persistent view and anywhere else that is pertinent.

**Comment by helfrij** [comment]
The fast shutter implementation should listen to the Zebra's "AND block" for its current value (0 = open, 1 = closed), and use "Soft Input 2" to open/close the shutter (0 to close, 1 to open).

**Comment by helfrij** [comment]
Time Estimate: 1 hour.
