### ISSUE TITLE
BioXAS: Pulse 3 needs to be disconnected from the Zebra changed when 32 element detector is not being used

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1848]
If the 32 element detector isn't being used it shouldn't be part of the trigger chain.  All this means is that the input to Pulse3 needs to be set to 0 in the scan controller initialization if the 32 element isn't being used.

**Comment by helfrij** [comment]
Just checking @dretrex: once this issue is solved, XAS scans should be able to be performed on Side with the scaler in the correct mode and without the 32Ge detector?

**Comment by dretrex** [comment]
This, in conjunction with #1856, will enable XAS scans to be performed with the scaler without the 32 element.  This is merely disconnecting the input of pulse 3, which is necessary, but not as important as the other issue.

**Comment by helfrij** [comment]
Done in #1911.

Time Estimate: 2 hours.
