### ISSUE TITLE
Action Info classes don't have Q_PROPERTIES for saved values

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1851]
It looks like most action infos don't have all the necessary Q_PROPERTIES to guarantee that the action can be reloaded properly.  This should be dealt with since it means that many of these actions can't be used inside loop actions.  I believe we've been able to get away with it because we always put these actions inside of lists.

**Comment by iainworkman** [comment]
Hello master branch. Haven't seen you in a while.

**Comment by iainworkman** [comment]
Time Estimate: 2 hours
