### ISSUE TITLE
REIXS: Impliment sample stage pseudomotor control

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#1852]
#1521 give REIXS users the ability to move the sample arm in the plane of the sample plate for alignment. It's executed at a very high level, with the methods for the move buttons commanding two motors to achieve the in-plane move.

It would be desirable to handle this at a lower level, so that an in-plane move control can be made available as a workflow action.  This is frequently done to collected repeated scans on different spots on a sample to minimize beam damage.

**It occurs to me that this could also be done at a high level, with buttons in the sample alignment panel to add a two-move listAction to the workflow...

**Comment by iainworkman** [comment]
@epengr I just want to make sure I've got everything straight in my mind with regard to the REIXS sample stage:
- There are three motors, X Y and Theta
- Theta rotates about the Z axis?
- The XY coordinate system needs to be dynamically rotated about the theta value as it alters?
- I assume the existing angleOffset_ means you'd like it to be able to accept a manual value which it uses in conjunction with the theta value?

**Comment by iainworkman** [comment]
Time Estimate: 2 weeks
