### ISSUE TITLE
Pulse 1 needs to be updated when not using Ge detector

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1856]
With #1842 done and synchronizing the fast shutter to update the time with the 32 element detector, we technically have one case that is being left behind.  If the scaler is being used without the 32 element, the pulse 3 block will not be updated with new times which means that the fast shutter won't be updated either.  We need a way of setting the fast shutter time when the 32 element is not being used in a scan.

**Comment by helfrij** [comment]
It's not immediately obvious to me how to tackle this one, @dretrex. Any ideas?

**Comment by dretrex** [comment]
Something along the same lines as the pulse block synchronizer but this time with the scaler.  When this is being used, you'll want to disable the synchronization between pulse 1 and 3 if only the scaler is being used.

**Comment by helfrij** [comment]
@dretrex is this equivalent to setting the trigger control for the AMZebraDetectorTriggerSource to the scaler scan control?

**Comment by dretrex** [comment]
No, because Pulse 1 is connected to the fast shutter which is not connected to the trigger source.

**Comment by helfrij** [comment]
Should the fast shutter have a trigger source?

**Comment by dretrex** [comment]
I've thought about that, but I don't think that would be a good path to go down because then it would likely need to be an AMDetector as well.

**Comment by helfrij** [comment]
Hokay. This is what I remember about our discussion yesterday, @dretrex.
- For scans with Ge detector: pulse 1 and pulse 3 need to be synchronized to make sure the Ge detector gets the updated dwell times.
- For scans without the Ge detector: pulse 1 and pulse 3 need to be un-synchronized,  pulse 1/fast shutter pulse time needs to be synchronized to the scaler dwell time.
- For scaler single-shot measurements: pulse 1 and pulse 3 need to be un-synchronized, opening/closing the fast shutter will be done manually by the user as part of the measurement procedure.

It seems maybe like pulse 1 and pulse 3 should be un-synchronized by default, and synchronized/un-synchronized as part of scan initialization/cleanup?

**Comment by dretrex** [comment]
Yup!  That's exactly how I remember it too! ;)

**Comment by helfrij** [comment]
@dretrex, another question. The fast shutter pulse is synchronized to the Ge detector pulse by default on application startup, and then 'synchronized' to the scaler dwell time in the special case where a scan is being run without the Ge detector. Does this mean that two Acquaman applications cannot be run at the same time, if one is scanning in this special case?

**Comment by dretrex** [comment]
Yes.

Sent from my iPhone

On Jan 29, 2016, at 9:47 AM, helfrij <notifications@github.com<mailto:notifications@github.com>> wrote:


@dretrex<https://github.com/dretrex>, another question. The fast shutter pulse is synchronized to the Ge detector pulse by default on application startup, and then 'synchronized' to the scaler dwell time in the special case where a scan is being run without the Ge detector. Does this mean that two Acquaman applications cannot be run at the same time, if one is scanning in this special case?

-

**Comment by helfrij** [comment]
On hold, while we figure out a solution for the fast shutter mechanical delay.

**Comment by helfrij** [comment]
It appears that the fast shutter is now active in a scan whether or not the Ge detector is involved, as discussed in #2066. This solution then is no longer needed.

Time Estimate: 1 day
