### ISSUE TITLE
Pulse modules should dynamically change their Time Units if the current time is not possible

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1857]
Since the Zebra has limitations on the time, the AMXspress3XRFDetector should dynamically alter (or maybe the pulse module itself?) the time units before setting the pulse width.

As a corollary, if we are ever doing an XAS scan with an EXAFS region we should immediately set the time units to be 10 seconds because EXAFS regions have maximum times of >6.5 seconds.  (In general, the pulse modules should probably default to 10s since that will offer the most time options for the time scales we care about.)

**Comment by helfrij** [comment]
Done in #1866.

Time Estimate: 1 day.
