### ISSUE TITLE
Hard drive space monitor for AM applications

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1864]
Since we can collect a lot of data and the hard drives on beamline OPI's are not really large, we should make a disk space monitor that samples the disk space every N amount of minutes and have a simple GUI element for it.  There may be a slick Qt way, or if not, a simple detached process of `du -H --max-level=1 /`should do the trick.

**Comment by iainworkman** [comment]
After a bit of research it seems that Qt4 doesn't have an inbuilt way of doing so. Qt5.4 and up has a [QStorageInfo](http://doc.qt.io/qt-5/qstorageinfo.html#details) class which will do it, however.

**Comment by dretrex** [comment]
Being stuck in the past sucks. :(

**Comment by iainworkman** [comment]
I am looking at lifting the source from Qt5 into an AMStorageInfo class. I have a build in place that I'm about to test. It will need work to make it work with OSX, I think (unsurprisingly it contains a lot of OS specific calls which are conditionally compiled). I'll let you know how the initial test works with linux.

**Comment by iainworkman** [comment]
Time Estimate: 9.25 Hours
