### ISSUE TITLE
Initialize Zebra time units as part of scan initialization

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1873]
We won't be able to dynamically update the Zebra time units during a scan, as the 32-Ge detector will get conflicting dwell time values. Instead, we could check that the Zebra is at the correct time units setting for the longest scan dwell time at scan initialization.

**Comment by helfrij** [comment]
Perhaps a different way to solve this problem is to write a pseudomotor control that handles resolving the pulse width control value and the time units control values into a single time value, always in seconds. This control would contain some of the logic introduced in #1857, and could be set as the acquireTimeControl_ in BioXAS32ElementGeDetector. This way, the detector is always guaranteed to get its acquire time in seconds.

**Comment by dretrex** [comment]
Interesting.  That is a good idea.

**Comment by helfrij** [comment]
I believe this is handled in #1898.

Time Estimate: 2 days.
