### ISSUE TITLE
Workflow crash when cancelling a non scan or non list action

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1882]
To reproduce:
- Add any non scan or non list action to the workflow (wait action works)
- Start it
- While it is still running cancel it.

It seems to be caused by the following lines in AMActionRunnerCurrentViewBase
```c++
AMScanAction *scanAction = qobject_cast<AMScanAction *>(actionRunner_->currentAction());
AMListAction3 *listAction = qobject_cast<AMListAction3 *>(actionRunner_->currentAction());

bool scanActionRunning = (scanAction != 0) || (qobject_cast<AMScanAction *>(listAction->currentSubAction()) != 0);
```
In cases where the current action is not a scan action or a list action then the boolean check will fail for ```(scanAction != 0)``` and proceed on to ```qobject_cast<AMScanAction*>(listAction->currentSubAction()) != 0```.  
If the current action is also not a list action the dereference to obtain the currentSubAction() causes a segfault.

**Comment by dretrex** [comment]
Interesting.  At least this should be pretty straightforward to fix.

**Comment by iainworkman** [comment]
Yeah, I found it while testing something else, so I ended up going right to it.

**Comment by iainworkman** [comment]
Time Estimate: 15 minutes
