### ISSUE TITLE
Build a spectrum with periodic table view

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1886]
After working on #1604, there is now a lot of duplicate code between the XRF detector views and the single spectrum view used by the scan views.  I think there is some room now to have a nice, generic "Spectrum view with a periodic table that lets you click on elements to inspect them" kind of thing.  

The main, obvious benefit is that as it stands now, if one of the classes gets updated but nobody thinks to update the other then we'll get into bad states where the functionality of the two isn't the same.

**Comment by mButlerDM** [comment]
Time Estimate: 1 Week

#2433
