### ISSUE TITLE
60 second scan time limitation

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1887]
There needs to be some clarification on the 60 second scan length limitation in SGMAcquaman.  I don't know the reason for this maximum length and I am occasionally asked by users.  If there is a real hard limit, we need to prevent users from running scans with longer duration than is possible.

**Comment by dretrex** [comment]
@iainworkman, @davidChevrier we handled this with some of the changes to other pieces didn't we?

**Comment by iainworkman** [comment]
Not sure. I believe this requires a change to the scaler to calculate the
correct buffer size, but not sure if this has been done in the amds
repository.

**Comment by iainworkman** [comment]
Handled in acquaman/AcquamanDataServer#135.
Time Estimate: 2 minutes
