### ISSUE TITLE
SGM Energy Axis not consistent between scans and detectors

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1894]
There are problems with the scan to scan stability of the energy axis.  A few weeks ago a user observed a shift in energy of several eV in the peak position of one amptek in a single scan (the other three detectors all line up).  This data was from the Al K edge at 1540 eV.  This problem seemed sporadic - it went away for the next scan.  This past week, the users have reported general inconsistency with the energy axis of their amptek data.  The attached data, taken at the Co L edge (780 eV) shows this effect.  The Ni L edge data shows a shift of several eV depending on scan direction.

The problem needs some more investigation to determine how repeatable the offsets are and how they vary between the individual detectors.  Right now it would appear to be unlikely to be a hardware problem.  We didn't observe this issue in the first weeks of operation (primarily at the C K-edge) but it is possible that it was happening then but not being noticed.  Note that a small energy offset was observed in the some of the C data that I processed from December but the effect was small (around 0.3 eV) and seemed consistent.  I thought that this may have been some type of mechanical backlash at the time but wanted to do more investigation.

[Energy_axis_worse_issue.pdf](https://github.com/acquaman/acquaman/files/103400/Energy_axis_worse_issue.pdf)
[Energy_axis_TEY_vs_PFY_scan_comparison.pdf](https://github.com/acquaman/acquaman/files/103401/Energy_axis_TEY_vs_PFY_scan_comparison.pdf)

**Comment by iainworkman** [comment]
Time Estimate: 18 Hours

**Comment by iainworkman** [comment]
@davidChevrier I imagine this would want a time estimate from you too?

**Comment by davidChevrier** [comment]
Time Estimate: 10 Hours
