### ISSUE TITLE
Unusual first point acquired for scans on BioXAS Side

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1895]
The first point acquired for scans sometimes appears to be erroneous. Ian C. reports that the anomalous point is not always present, seems to be only visible for scans where scaler initialization is handled by Acquaman. He suggests the point may be the last reading from the previous scan. Likely related to scaler initialization in BioXASXASScanActionController.

**Comment by dretrex** [comment]
This is still triggered by the Zebra, but it is a problem with the scaler only.  The 32-element doesn't appear to have this problem.

**Comment by helfrij** [comment]
Handled in #1932.
