### ISSUE TITLE
AMCurrentAmplifierView: Propagate custom context menu signal even if clicking on the combo box in the advanced view

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1912]

**Comment by dretrex** [comment]
Can you provide more details @XuetaoLiu-CLS?  Because I saw this working on VESPERS earlier today.

**Comment by dretrex** [comment]
This is actually working, but @XuetaoLiu-CLS did find that it's not obvious that it is working if you right click on the combo box rather than the widget in general.  This issue will become propagating the context menu event to the combo box.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 1 hour
