### ISSUE TITLE
SXRMB: saved fluorescence detector choice not preserved on copy

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#1919]
When the user setup the configuration, he chose no bruker detector (disconnected) and then start scan. 

We are still trying to access bruker detector and give warning message that the bruker is not connected

**Comment by dretrex** [comment]
Can you put in a description @XuetaoLiu-CLS?  I don't think I understand what this issue is saying.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 10 minutes
