### ISSUE TITLE
Warnings generated from onCustomContextMenuActionImplementation() in AMCurrentAmplifierView

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1930]
This is a small code cleanup that should be done because it generates a bunch of warnings.  I'm mostly making this an issue because it's the kind of thing that we should try to avoid coding ourselves and also to try and be diligent in our code review to spot these as well.

@XuetaoLiu-CLS, I'm going to assign this one to you since it is in the code you wrote.  Mostly because something I didn't notice before was now there are two context menu slots:

```c++
void onCustomContextMenuRequested(QPoint position);
virtual void onCustomContextMenuActionImplementation(QMenu *contextMenu);
```

Yours is the `QMenu *` and we should stick with that one, but could you make sure that only the `onCustomContextMenuActionImplementation()` version is being used and remove the other one?  Thanks!

**Comment by XuetaoLiu-CLS** [comment]
Time estimate: 10 minutes

**Comment by XuetaoLiu-CLS** [comment]
Both functions are required. One is the slot itself, the other is for customized implementation of the subclasses.
