### ISSUE TITLE
Wrong data sources are normalized in generic scan controller

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1935]
An indexing bug in AMGenericStepScanController means that the wrong data sources are normalized when some of the data sources are hidden.

https://github.com/acquaman/acquaman/blob/master/source/acquaman/AMGenericStepScanController.cpp#L144

should be:
```C++
AMDataSource *source = scan_->dataSourceAt(sourceIndexes.at(i));
```

**Comment by dretrex** [comment]
Done in #1936.
Time Estimate: 5 minutes
