### ISSUE TITLE
BioXASSIS3820Scaler does not trigger when in SingleShot from Scaler View.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1939]
Due to the extra triggering step through using the Zebra, the "Start" button in the CLS scaler view will not cause the scaler to acquire.

**Comment by dretrex** [comment]
@helfrij, I think the stop button _should_ be as easy as disarming the scaler.  This is the same as the old version of setting the `startToggle_` control to 0.

**Comment by helfrij** [comment]
Done in #1944.

Time Estimate: 1.5 hours.
