### ISSUE TITLE
BioXAS scaler can use Zebra OR2 to listen for changes to scanning state.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1952]
A funny, small detail. But. If a second Acquaman application is opened, the scaler view won't correctly display the scaler's scanning state when the scaler is in SingleShot mode.

@dretrex says:

This is due to the fact that the scanning state is being set when the trigger source is triggered. The trigger source will only live in the application that's running. If we want that light to be representative more generally, we'll need to listen to the arming and possibly the OR2 gate of the Zebra.

So. If the scaler is armed + detects a value change from Zebra OR2 control, it is scanning.

**Comment by helfrij** [comment]
@dretrex and I tested a potential solution yesterday, and found that the Zebra OR block doesn't keep up with the scaler scanning toggle or the Zebra soft input control. The current solution in #1997 only detects the scaler's scanning state some of the time, missing other triggers.

**Comment by dretrex** [comment]
Hey @helfrij, since the EPICS layer of the Zebra can't be trusted, do we want to close this issue and keep the solution I had in place from #1946?

**Comment by helfrij** [comment]
I was just thinking about this. Hmmm. Yes, I think that's a good idea. If it ends up being a problem in the future, we can deal with it then.

**Comment by helfrij** [comment]
Time Estimate: 1 day.
