### ISSUE TITLE
Create a SGMContinuousScanController

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1964]
At the moment AMContinuousScanActionController has a dependency on CLSAMDSScalerChannelDetector and CLSAmptekSDD123DetectorNew - which causes issues when attempting to build any project which includes acquamanCommon.pri, but not clsCommon.pri.

This dependency exists in order that the continuous scan action controller can perform actions which are, in essence, specific to the SGM's continuous scan setup. In order to get around this the code specific to SGM (which makes use of the above CLS classes) needs to be moved into a new SGMContinuousScanController, which will be the common ancestor of SGMXASScanController, SGMLineScanController and SGMMapScanController.

**Comment by dretrex** [comment]
Since this is done in #1966 I'm going to close this out.

**Comment by iainworkman** [comment]
I'm not sure why project tracking is disabled on this. This was the issue, and #1966 was the pull request.

**Comment by iainworkman** [comment]
Time Estimate: 4 Hours

**Comment by dretrex** [comment]
Hmm. Not sure either.  Weird that we didn't give it an estimate too.
