### ISSUE TITLE
SGM scaler data and Amptek data not aligned in maps

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1972]
It looks as though the first column (on the left) of an image made using the scaler data contains the data that should appear in the last column.  This is not the case for the Ampteks.  This causes a problem with normalization of the Amptek data with the I0.  See attached image.
![snapshot1](https://cloud.githubusercontent.com/assets/793926/12879238/d01c1f80-cdf5-11e5-8b97-d36c36980095.png)

**Comment by dretrex** [comment]
This looks like each pixel is getting the previous point.  Must not be waiting for all the channels to finish.
