### ISSUE TITLE
SGM Detectors Reporting Not Ready to Acquire

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1983]
Occasionally step scans on the SGM will fail, with an error monitor reporting that one of the scaler channels or amptek detectors is not ready to acquire. This seems to be a periodic error, happening frequently for periods, then less frequently. At the moment, due to the large number of successive acquisitions required, this is making running map scans untenable.

**Comment by iainworkman** [comment]
A similar issue was encountered when testing the merged SGMUpgrade branch on IDEAS. Darren and I spent some time investigating the cause and found the changes in the following commit were a solution: 1a22e0f0ab1d64eb0370c96c0a4a8cf78cedfdb3
This still needs testing on SGM, and there will also need to be some effort to ensure that similar state transitions are applied in all the detectors (most notably the scalar ones).

**Comment by dretrex** [comment]
@iainworkman and I spent about 2 hours on this.
Time Estimate: 4 hours

**Comment by iainworkman** [comment]
Investigation done on this issue indicates that the problem is to be found in CLSAMDSScaler::onDwellStateControlValueChanged(double state)

which does not perform sufficient checks on the dwell state incoming, and sets the trigger source to the finished state too early. The check should probably include a check on the incoming state value also.
