### ISSUE TITLE
BioXASBeamlineComponent to inherit from AMConnectedControl

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1992]
BioXASBeamlineComponent is the ancestor of almost all BioXAS-specific beamline components. It provides a default stop implementation, and additionally manages the connected state as a function of the states of the child controls. The connected aspect of it can be removed if this class inherits from the new AMConnectedControl, instead of AMControl.

Will wait for SGMUpgrade to be merged in first, that's where AMConnectedControl lives right now.

**Comment by dretrex** [comment]
Should be good to go on this issue now, @helfrij :)

**Comment by helfrij** [comment]
:) :) :)

**Comment by helfrij** [comment]
Done in #2082.

Time Estimate: 10 minutes.
