### ISSUE TITLE
BioXAS Side and Main crash when starting an XAS scan with no detectors selected

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1993]
When there are no detectors selected, the application crashes when starting an XAS scan. There are at least two things we can do to prevent these crashes:
- prevent a scan from being started with no detectors (disable 'start scan' button?)
- add I0, I1, and I2 detectors by default. This could require the app controller to listen to their connected states.

I'd like to wait until SGMUpgrade is merged in before beginning, so that I can use the scientific detectors added to AMBeamline there.

**Comment by dretrex** [comment]
The first point is definitely a framework-wide issue.

**Comment by helfrij** [comment]
Added detectors to the configuration by default as part of #2054.

Time Estimate: 2 hours.
