### ISSUE TITLE
BioXAS Side DB crash

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2015]
BioXAS Side application is running in gdb, to get more information about potential crashes on starting new scans. The application crashed this morning, and this is the last few lines of the resulting trace:

Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Not
Ready For Acquisition. Detector name: Ge32Element. Current state: Not Ready For
Acquisition. (code 470010)"
Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Init
ialization Required. Detector name: Ge32Element. Current state: Initialization R
equired. (code 470003)"
Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Not
Ready For Acquisition. Detector name: Ge32Element. Current state: Not Ready For
Acquisition. (code 470010)"
Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Init
ialization Required. Detector name: Ge32Element. Current state: Initialization R
equired. (code 470003)"
Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Not
Ready For Acquisition. Detector name: Ge32Element. Current state: Not Ready For
Acquisition. (code 470010)"
Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Init
ialization Required. Detector name: Ge32Element. Current state: Initialization R
equired. (code 470003)"
Debug: "in [BioXAS32ElementGeDetector]: An unexpected transition occured to Not
Ready For Acquisition. Detector name: Ge32Element. Current state: Not Ready For
Acquisition. (code 470010)"
[Thread 0x2b56f8a00940 (LWP 9422) exited]
Debug: "in [CLSBasicScalerChannelDetector]: An unexpected transition occured to
Acquiring. Detector name: I0Detector. Current state: Acquiring. (code 470004)"
Debug: "in [CLSBasicScalerChannelDetector]: An unexpected transition occured to
Acquiring. Detector name: I1Detector. Current state: Acquiring. (code 470004)"
Debug: "in [CLSBasicScalerChannelDetector]: An unexpected transition occured to
Acquiring. Detector name: I2Detector. Current state: Acquiring. (code 470004)"
Alert: "in [AMScanAction]: Could not find the database associated with this scan
. (code 103110)"
Alert: "in [AMControlMoveAction3]: There was an error moving the control 'JJSlit
sLowerBlade' into position (Retry Yes, attempt 1 of 2). Target: -2.202 mm. Actua
l position: -2.196 mm. Tolerance 0.005. Reason: The required tolerance was not m
et... Please report this problem to the beamline staff. (code 13002)"
Alert: "in [AMControlMoveAction3]: There was an error moving the control 'JJSlit
sUpperBlade' into position (Retry Yes, attempt 1 of 2). Target: -2.402 mm. Actua
l position: -2.41 mm. Tolerance 0.005. Reason: The required tolerance was not me
t... Please report this problem to the beamline staff. (code 13002)"
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT O
R REPLACE INTO AMLoopActionInfo3_table (id, AMDbObjectType, name, shortDescripti
on, longDescription, iconFileName, expectedDuration, canCopy, loopCount, thumbna
ilCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to op
en database file Unable to fetch row (code -3)"
Alert: "in [AMLoopActionInfo3]: Could not store to db (actions), the insert or u
pdate call failed. Please report this problem to the Acquaman developers. (code
-277003)"
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT O
R REPLACE INTO AMActionLog3_table (id, AMDbObjectType, name, startDateTime, endD
ateTime, finalState, info, longDescription, iconFileName, parentId, actionInheri
tedLoop, failureMessage, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (c
ode -3)"
Alert: "in [AMActionLog3]: Could not store to db (actions), the insert or update
 call failed. Please report this problem to the Acquaman developers. (code -2770
03)"
Alert: "in [AMActionRunner3]: There was a problem logging the uncompleted action
 to your database.  Please report this problem to the Acquaman developers. (code
 -200)"
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT O
R REPLACE INTO AMExporterOptionXDIFormat_table (id, AMDbObjectType, name, fileNa
me, headerText, headerIncluded, columnHeader, columnHeaderIncluded, columnHeader
Delimiter, sectionHeader, sectionHeaderIncluded, includeAllDataSources, includeH
igherDimensionSources, firstColumnOnly, separateHigherDimensionalSources, higher
DimensionsInRows, dataSources, dataSourceOrganizeModes, dataSourceIsRequired, da
taSourceOmitAxisValueColumns, separateSectionFileName, columnDelimiter, newlineD
elimiter, elementSymbol, elementEdge, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was:
 unable to open database file Unable to fetch row (code -3)"
Alert: "in [AMExporterOptionXDIFormat]: Could not store to db (user), the insert
 or update call failed. Please report this problem to the Acquaman developers. (
code -277003)"
Serious: "AMCDFDataStore: Could not create file '/AcquamanLocalData/bioxas-s/Acq          uamanSideData/users/21-7270/userData/2016/02/Thu_02_11_11_20_33_3667.cdf' for th          e CDF data store. Maybe the file exists already? The CDF data store is now inval          id. (code -101)"
Debug: "AMCDFDataStore: Could not create axis values CDF variable for axis 'BioX          ASSideMonochromatorStepEnergy'. The CDF error was: -2053 (code -724)"
Debug: "AMCDFDataStore: could not set attribute Axis::Name for axis info. (code           -1003)"
[New Thread 0x2b56f8a00940 (LWP 10005)]
Debug: "AMCDFDataStore: Could not create CDF variable for measurement 'I0Detecto          r'. The CDF error was: -2053. (code -102)"
Debug: "AMCDFDataStore: Could not create CDF variable for measurement 'I1Detecto          r'. The CDF error was: -2053. (code -102)"
Debug: "AMCDFDataStore: Could not create CDF variable for measurement 'I2Detecto          r'. The CDF error was: -2053. (code -102)"

GLib-ERROR **: Cannot create pipe main loop wake-up: Too many open files

aborting...

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2b56f8a00940 (LWP 10005)]
0x0000003f16a2ffc5 in raise () from /lib64/libc.so.6

**Comment by davidChevrier** [comment]
Hey @helfrij @dretrex @iainworkman @epengr @XuetaoLiu-CLS 
I'm betting this and #2014 are the same issue and may be the same issue that's causing a daily crash on SXRMB.

I think the key line is actually at the bottom
`GLib-ERROR **: Cannot create pipe main loop wake-up: Too many open files`

This happens when some process has opened too many files and hasn't closed them. To my knowledge, this happens in two ways. Either when files are opened for reading or writing and aren't closed OR when threads are created and not destroyed.

It looks like this is likely affecting all of the beamlines, so I think it should be a high priority to sort out. @helfrij @iainworkman is there any chance the two of you could get together on BioXAS and do some testing? We've been it with this before, so I'll see if I can find the emails I have from the first time which had some handy command line stuff to spot the number of open file descriptors. Hit me back and let me know.

**Comment by helfrij** [comment]
Just deployed #2016 on BioXAS Side.

**Comment by helfrij** [comment]
Done in #2016.

**Comment by davidChevrier** [comment]
Time Estimate: 4 hours
