### ISSUE TITLE
Scaler dark current

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2022]
Ian C. noticed yesterday that the dark current measurements don't appear to update with the latest values. To reproduce in AM:
- set scaler to SingleShot.
- set scaler dwell time 1000ms.
- take dark current measurement (using dark current view widgets).
- set scaler dwell time to 10,000ms.
- take dark current measurement.

The dark current counts/sec value that is displayed in the BioXAS scaler view matches the ion chamber readings from the first measurement (like they've just been shifted over) instead of the new readings.

Some further investigation is likely required.

**Comment by helfrij** [comment]
I think I've been able to reproduce what Ian C. has seen, but it doesn't appear to have anything to do with changing the dwell time. It looks to me like all dark current measurements use the scaler's previously measured values--ie. the measurement taken before the dark current measurement. 

This could happen for the following reason: the dark current measurement action waits for the dwell action to finish before processing the measurement information, not for the scaler channels to report a new value. It's possible that when the scaler channels are asked for their latest value, what's returned is still the 'old' value. The value is updated to the new value after the dark current processing is complete.

**Comment by dretrex** [comment]
You may need to implement something similar to what I implemented for #1941

**Comment by dretrex** [comment]
Also #1895.

**Comment by helfrij** [comment]
Looking over #1895, the solution implemented was to add an extra scaler acquisition to the start of XAS scans on BioXAS. Just checking, is the solution to this problem as simple as adding an extra acquisition to each dark current measurement?

**Comment by helfrij** [comment]
Done in #2023.

Time Estimate: 2 days.
