### ISSUE TITLE
Modify AMControl::addChildControl(...) and removeChildControl(...) to return a success status bool

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2030]
These methods currently return nothing but, as @XuetaoLiu-CLS noticed in #2010, there can be some simplifications made in AMPseudoMotorControl subclasses when they return true on success, false otherwise.

Will wait for #2030 to be merged in before beginning.

**Comment by mButlerDM** [comment]
I will be addressing this in my refactoring in issue #2271

**Comment by mButlerDM** [comment]
Addressed in #2271 and related sub issues.
