### ISSUE TITLE
Add cryostat temperature PVs and view

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2034]
Ian C. would like to have the cryostat temperature PVs added to Acquaman and displayed in the Side persistent view. I don't have access to the PV names yet, will ask David B.

**Comment by dretrex** [comment]
Does this involve temperature control or just display?

**Comment by helfrij** [comment]
Just display.

**Comment by helfrij** [comment]
Cryo system PVs are now available for Side:
TMP1607-6-01:pressure
TC1607-6-01:READ_TEMP_SIG_TEMP:1

**Comment by helfrij** [comment]
Done in #2086.

Time Estimate: 30 minutes.
