### ISSUE TITLE
Create beam status-like view for the BioXAS utilities

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2041]
The beam status view is currently a main editor displaying the beam status with a row of styled buttons underneath, one for each beamline component. The button is green or red, depending on the status for that particular component, and clicking on a button causes some editors related to that component to display. I like the general idea of this view, and think it would be a cool way to visualize utilities information.

It's best to begin this issue once #2045 is merged in.

**Comment by mButlerDM** [comment]
@helfrij Was this still a feature requiring attention?

**Comment by helfrij** [comment]
I don't think so. I'll close it out.
