### ISSUE TITLE
Bad First Point 3

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2043]
It continues. The bad first points seen earlier in #1941, #1895 seem to have come back. A couple of possibilities come to mind:
- It's possible that the wait added to arming the scaler in BioXASSIS3820Scaler isn't always long enough. Although if that's true, we'd expect the points to be interspersed throughout a scan; the bad points we see only affect the first point.
- The bad points seem to appear only in scans that involve the Ge detector, which makes me suspect they may have something to do with setting up the Zebra or some other aspect of triggering that's Ge detector related. I'm not sure if they happen in all Ge detector scans.
- I don't think there have been recent changes to the scaler, detector, or zebra in master recently. If that's true, it's unlikely that the points would be caused by any changes made between now and the earlier solutions.
- Ian C. hasn't been running scans with the Ge detector frequently. It's possible this has been a problem for a little while and it hasn't been noticed?

If the points are caused by some timing issue, they may be solved with the trigger action being worked on in #2022. But thought I'd make a note of it here, and investigate separately.

**Comment by dretrex** [comment]
So this is fundamentally different because it _only_ happens with the 32 element and not the scaler, right?  Before it was _only_ the scaler and not the 32 element.

**Comment by helfrij** [comment]
That's the way it looks, though I'd like to do more testing to confirm.

**Comment by helfrij** [comment]
Ian C. confirmed in the meeting this morning that the bad point only appears to affect scans with the Ge detector, and it seems to impact about 30-40% of scans with the detector.

**Comment by helfrij** [comment]
I just ran 15 scans on Side and have been unable to reproduce this bug. I would guess there's more to the problem than just running scans with the Ge detector. Waiting on discussion with Ian C.

**Comment by helfrij** [comment]
I have a thought. The zebra pulse 1 width isn't set during scan initialization. It's possible that it's not the value that's bad, it's the dwell time.

**Comment by epengr** [comment]
Good point.  I'll investigate.

I have no users scheduled Thr/Fri, I hope to work on some of these issues then.

**Comment by helfrij** [comment]
First tentative solution done in #2113. Investigation to be continued in #2123.

Time Estimate: 2 days.
