### ISSUE TITLE
Problems with commissioning tool

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2053]
Emilio H. today noticed that he couldn't start a commissioning scan on BioXAS attempting to move the JJ slits.
- First error related to the scaler being in Continuous mode, but scaler initialization is not supported using the generic scan.
- With scaler in single shot, the scan appeared to initialize (the controls moved to the start position) but the scan stalled from there. The timer kept progressing, but no further motor movement.

**Comment by dretrex** [comment]
Is it possible that all the initialization stuff we've done with the Zebra for the XAS scans is missing from the generic scan?

**Comment by helfrij** [comment]
Yup, I would guess that's what's happening here. I was thinking, it would really suck to have a BioXAS-specific commissioning tool, but there are beamline specific initialization and cleanup actions that have to happen for all scans. What do you think about having beamline classes provide the initialization and cleanup actions? The commissioning tool could access and perform these actions through the general AMBeamline interface, without sacrificing generality.

**Comment by dretrex** [comment]
I think that's a great idea.  I thought of doing that a long time ago, but probably didn't write it into an issue.  Probably something in AMBeamline like, ```virtual AMAction3 *AMBeamline::createStandardScanInitializationActions();```?  What do you think?

**Comment by helfrij** [comment]
Yup, that's it! Could do the same thing with cleanup as well.

**Comment by helfrij** [comment]
I think this problem is entirely solved in #2057.
