### ISSUE TITLE
Include values for each enabled 32Ge detector element in XAS scan data

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2054]
Right now, only a single value is stored for the Ge detector in scan data that represents readings for all detector elements. The BioXAS team would like to have the scan have the output from each detector element separate in the scan data file instead.

Additionally, would like to include the incoming count rate (ICR) for each element as well.

**Comment by dretrex** [comment]
I don't think I understand this one.  Do you mean the individual spectra data or something else?

**Comment by dretrex** [comment]
Do we know what the ICR is?  I didn't think that was an available PV.  I could definitely be wrong on that.

**Comment by helfrij** [comment]
I think what they want is something that looks like this:

... I0 I1 I2 Ge1 Ge2 Ge4...

One column for each detector element, for elements used in the scan. There is an ICR value for each detector element too, but it's called something else--the AllGood value or something like that. Would have to ask Ru about it, I think.

**Comment by dretrex** [comment]
Okay.  I think it is important to keep this code a bit separate mentally from other code for the scans.  This kind of code would not typically be in a data file that a user would take home, but is probably useful for commissioning.  Could you double check that this is the case?

**Comment by helfrij** [comment]
Just checked with Gosia, she thinks it would be useful for all users.

**Comment by dretrex** [comment]
Really?  I don't think I've ever heard of any user wanting that kind of information.

**Comment by helfrij** [comment]
I don't really know enough about what users need to weigh in here. Maybe a compromise could be having it as an option?

**Comment by dretrex** [comment]
I'll probably just need to have a chat with Gosia when I get back.  I'm curious about the use case she's thinking about.

**Comment by helfrij** [comment]
The use case may start with G.

**Comment by dretrex** [comment]
But then that still is limited to a single person.  Not a general user community.

**Comment by helfrij** [comment]
I agree that further investigation is likely required.

**Comment by helfrij** [comment]
I'm having trouble getting started on this, @dretrex. Where should I look for an option to export the ROIs as a separate file?

**Comment by helfrij** [comment]
Done in #2120.

Time estimate: 4 hours.
