### ISSUE TITLE
Add power on/off controls to the detector stage screen

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2058]
Ian C. says users will be required to periodically power on and off the lateral detector stage motor, and right now they would have to go to the motor EDM screen to do this. If this is a necessary task that most users would have to perform, it would be a better idea to have this control in Acquaman.
- Off = off
- On = autosoftware

**Comment by dretrex** [comment]
Is something wrong with the motor?

**Comment by helfrij** [comment]
No, it sounds like this is supposed to be more of a safety measure to prevent users from accidentally moving the motor. If this is the case, though, any user could defeat this safety by forgetting turn off the power.

**Comment by dretrex** [comment]
I agree. This idea needs a bit more investigation before spending too much time on it.

Sent from my iPhone

On Feb 25, 2016, at 11:15 AM, helfrij <notifications@github.com<mailto:notifications@github.com>> wrote:


No, it sounds like this is supposed to be more of a safety measure to prevent users from accidentally moving the motor. If this is the case, though, any user could defeat this safety by forgetting turn off the power.

-
