### ISSUE TITLE
Control editors to pay attention to AMControl's minimum and maximum value change signals

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2060]
AMControl's can now report changes to their minimum and maximum values via signals. This issue will address adding connect statements to control editors so they also get that information.
- [x] AMExtendedControlEditor
- [x] BioXASControlEditor

Potentially solves some problems in #2059.

**Comment by dretrex** [comment]
Remember that AMControl will only emit these signals if `enableLimitsMonitoring()` is true.  Otherwise, they should behave like normal.

**Comment by helfrij** [comment]
Done in #2061.

Time Estimate: 2 hours.
