### ISSUE TITLE
Binning noise in Amptek XRF maps

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#2064]
XRF maps have random noise that appears to be associated with the binning of the data.  The noise can be removed by dividing on ROI map by another ROI map from the same detector.  It seems like some pixels are getting one additional MCA added to them.  We tested at 0.2, 0.3 and 1s integration time and the noise effects were diminished for longer acquisition times but did not go away.

The uploaded pictures show data before and after 'self normalization'.

![image](https://cloud.githubusercontent.com/assets/793926/13359264/dd9713f4-dc78-11e5-94a4-601b826477b6.png)

![image](https://cloud.githubusercontent.com/assets/793926/13359281/fcae36b4-dc78-11e5-853c-24b0d0c974c8.png)

**Comment by dretrex** [comment]
Does the image get cleaned up if you collect an I0 at the same time and normalize by that?

**Comment by regiert** [comment]
No.  The noise is slightly different on all ampteks.  You can only get rid
of it by the 'self normalization'.

**Comment by regiert** [comment]
I've just been watching the amptek XRF spectra on the detectors page.  You can see that the acquisition times (real and live) periodically jump to larger values than what are set in the requested dwell time.  A possible workaround to this issue would be to record a map of the real time acquisition for each detector so that this effect could be normalized out.

**Comment by regiert** [comment]
I've been working at a work around for this bug but I've been unsuccessful.  There are a few viable options but all require changes to the Acquaman code:

-Actually fix the problem with the ampteks
-Add a data channel to the file that shows the real time for each acquisition on each of the four detectors.  This could then be used for normalization.
-Set up the acquisition to run with extremely short dwell times so that the data client never gets more than one 50ms dwell period.
-Operate the ampteks in the old way with triggered dwell.

The user starts at 4pm on Tuesday and it would be great if someone with the right expertise could look into this before then.
