### ISSUE TITLE
Organize exported file based on AMRuns

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2065]
Currently, all the scans will be exported to the root directory of the ExportedFiles. As we organize the scans based on the AMRuns the users created, it will be nicer if we can organize the exported files in the same way, so that user will only need to copy the files of a given runs.

**Comment by dretrex** [comment]
Hey @XuetaoLiu-CLS, I already created an issue for this in #2029.

**Comment by XuetaoLiu-CLS** [comment]
@dretrex Sorry. I just recalled that I should create one since Quanfeng mentioned it the day before yesterday :). Thx

**Comment by dretrex** [comment]
No worries :)
