### ISSUE TITLE
Remove fast shutter from Zebra chain

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2066]
This doesn't need to be attended to right away. But. Right now, the fast shutter is triggered in some cases (scans with Ge32) and isn't in other cases (any other scan). I think. The BioXAS team hasn't decided yet whether or not they want to trigger the shutter for every acquisition on Side. Because LOI users are coming soon, it may be prudent to start thinking about removing the fast shutter from the trigger chain entirely, until the team decides having the shutter will help.

**Comment by helfrij** [comment]
Hey @dretrex, I just ran a scan without the Ge detector on Side and it looks like the fast shutter was triggering with every acquisition point. I thought this shouldn't be possible, since we haven't implemented a solution for #1856 yet. Do you happen to know why that might be?

If it is triggering successfully and we're happy with the mechanism, I'll close out this issue.

**Comment by dretrex** [comment]
No, we fixed that in an earlier issue.  Removing the fast shutter from the Zebra chain is more because it requires a pulse block and may only really be wasting time.

**Comment by helfrij** [comment]
Okay. I'll close out this issue.
