### ISSUE TITLE
Increase precision for the cursor position tool in the AMScanView

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2074]
Right now, the default precision is 2 decimal places, and it isn't enough when a scan plot is zoomed in. It would be useful to have the default set to 3 places.
- the desired precision may actually be plot scale-dependent, or data source-dependent?

**Comment by dretrex** [comment]
Is the format 'g'?  If it is, then when the numbers get small it should switch to scientific notation.

**Comment by helfrij** [comment]
Done in #2269.

Time Estimate: 20 minutes.
