### ISSUE TITLE
Enable Diode, PIPS, Lytle detectors on Main

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2076]
The 'extra' scaler channel detectors were implemented for Side in #2044. This issue would address making them general BioXAS features.
- Would they be used on Imaging as well?
- Need to check if the extra scaler channel is enabled. Not sure it is right now.

**Comment by dretrex** [comment]
They may have a subset, but a couple of those detectors are primarily for Ge32 detector and EXAFS scans if I recall correctly.

**Comment by helfrij** [comment]
Done in #2138.

Time Estimate: 1 day.
