### ISSUE TITLE
Acquaman update application

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2079]
The process of updating Acquaman software is something that could eventually be scripted/automated. It might be handy sometime in the future for beamline staff to be able to run this script/application to update their own software. The script/app could abort an update and return to a previous tagged version if there are merge conflicts or if a build fails, and refer users to the Acquaman group. The application could handle updates across multiple repositories too, so the latest version of everything is what's always used.

**Comment by iainworkman** [comment]
Yes, deployment strategies is pretty high on my priority list after the transition period is over, and some of the dust has settled. What you describe would be incredibly useful, even if it is only used by us. Doing a full deploy of SGM can take the best part of a day if things don't go to plan and leveraging some tools to mitigate this would be very useful in speeding things up and making the process less error prone.
