### ISSUE TITLE
Add mono temperature monitors to Side and Main applications

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2083]
The mono temperature monitors are important readings to have, and aren't displayed in Beamline Master (where I got the utilities PV names previously). This issue will address adding the missing monitors to the appropriate BioXASBeamline subclass.

**Comment by mButlerDM** [comment]
@helfrij Did this still require attention?

**Comment by helfrij** [comment]
No. I went through the list of the "new" PVs and they are added already.
