### ISSUE TITLE
BioXAS Ge detector flooded with ROIs on startup

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2091]
On startup, the Cu K alpha ROI should be added to the Ge detector by default in BioXASAppController. If a user clicks on 'Edit ROIs' on the main detector view, several identical ROIs appear there--more than fit on the monitor screen. This has happened at least once for me today, while trying to set up scans to investigate #2043. I think the desired behavior is to have just one Cu K alpha ROI added by default.

**Comment by dretrex** [comment]
That is correct, you should only have one added by default.

**Comment by helfrij** [comment]
It appears that on startup, my user configuration has 65 ROIs. In `BioXASAppController::onConfigurationLoadedFromDb()`, every one is added to the detector and XAS scan configuration. Why that particular number, I'm not sure. 

We could stop the duplicates from being added to the detector on startup by adding (==) operator implementation for AMRegionOfInterest, so we have a way of identifying duplicate ROIs. Could then add checks for duplicate ROIs to BioXASAppController (and maybe AMXRFDetector?). This would be useful if there is never a case where we'd _want_ duplicate ROIs.

The user configuration is a database object, right, @dretrex? That means that only applications with an affected user configuration would experience this problem? It's still not clear to be how it got into that state to begin with.

**Comment by helfrij** [comment]
Done in #2092.

Time Estimate: 1 hour.
