### ISSUE TITLE
Beam status indicators not working

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2110]
Since updating, both IDEAS and REIXS beam status indicators in the sidebars are not working.

I looked briefly into this and it _seems_ that signals are not being emitted by the shutter `CLSExclusiveStatesControl`'s.

I'm wondering if this is related to #2060?

**Comment by dretrex** [comment]
Hey @helfrij, do you have any suggestions for this?

**Comment by helfrij** [comment]
The beam status indicators are related to just the open/closed status of your shutters, right? Which signals do you think aren't being emitted, @epengr?

**Comment by epengr** [comment]
The `IDEASBeamline::onShutterStatusChanged()` signal is not being emitted, which is connected to `stateChanged(int)` from safetyShutter_, safetyShutter2_ and photonShutter2_.  I don't _believe_ that these signals are being emitted.

**Comment by helfrij** [comment]
Ah, okay! I'll take a look.

**Comment by helfrij** [comment]
Hey @epengr, I think those signals in the connect statement should be for `valueChanged(double)` instead of `stateChanged(int)`. Try the changes I've made in #2112, and let me know if that helps.

**Comment by epengr** [comment]
@helfrij Thanks!  I'll test this tomorrow.  I added corrections to the REIXS shutters to this commit as well.   If it does fix IDEAS, it should work there too.

**Comment by helfrij** [comment]
Np! Hopefully this helps, as it's a simple fix :)

**Comment by epengr** [comment]
Hotfix tagged on to #2059

**Comment by epengr** [comment]
How is tracking supposed to work for Hotfixes?  Whatever time @helfrij spent on this is it, I just watched...

**Comment by dretrex** [comment]
Between all of us, lets say...
Time Estimate: 20 minutes
