### ISSUE TITLE
Remove 'modes' from BioXAS scaler view

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2119]
The modes option in the BioXAS scaler view is useful now because Side and Main operate in different scaler modes (eg. software triggered vs hardware triggered). Once the zebra is implemented for Main, though, viewing those PVs will no longer be necessary, and could be confusing for users. Once #2046 is addressed, this view option should be removed.

**Comment by mButlerDM** [comment]
Time Estimate: 30 Minutes
