### ISSUE TITLE
Check for duplicate ROIs

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2121]
BioXAS user configurations seems to have a ton of Cu Ka ROIs by default, which prior to #2092 would all be loaded into AM at startup. The detector would appear to have a ton of duplicate ROIs, which wasn't good. It would probably be a good idea to see if this happens on other beamlines, and maybe come up with a more general fix.

**Comment by dretrex** [comment]
This will become a moot point after #2375 is done.
