### ISSUE TITLE
Add button to scanDataView that opens exportData folder

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2126]
Just an ideas, it should be pretty simple to add a button beside the export button that launches a system file browser pointed at the users export data folder.  Would be very convenient, I think.

I could even take a crack at this one?

**Comment by dretrex** [comment]
@epengr there should be something called QFileBrowser or something similar.  I'd start there.

**Comment by epengr** [comment]
Completed in  #2272

Time Estimate: 1 hour
