### ISSUE TITLE
Create BioXAS-specific commissioning tool

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2143]

**Comment by dretrex** [comment]
Hey @helfrij, I'm assuming this is because it's just way easier to implement the Zebra characteristics this way for the time being?

**Comment by helfrij** [comment]
Yes. It's my hope that this won't be necessary forever, but is the quickest route to restoring the generic scan tool for BioXAS.

**Comment by dretrex** [comment]
I agree with both points.

Sent from my iPhone

On Mar 16, 2016, at 6:06 PM, helfrij <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. It's my hope that this won't be necessary forever, but is the quickest route to restoring the generic scan tool for BioXAS.

-

**Comment by helfrij** [comment]
Done in #2147.

Time Estimate: 1 day.
