### ISSUE TITLE
Bad first point 5

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2151]
The Main inboard detector was implemented recently in #2046. The bad first point appears now for this detector, even with the fix implemented in #2043. For scans that are executed "normally" (to completion) a bad first point always appears. 

The bad first point is not scaled by the acquisition time of the previous point. Eg. Acquiring a 10s measurement with the detector before starting a scan doesn't seem to affect whether the point shows up, or its value. This makes the problem seem fundamentally different than the problem being addressed in #2043 and #2123.

Stopping a scan partway through, though, yields some interesting results. If the scan is stopped in the pre-edge area (the value is still low) and another scan is started, the bad first point doesn't seem to appear. If the scan is stopped later on (value is higher than background), the bad first point appears in the next scan.

When the bad point appears, it always seems to have the same/similar value (~0.3).

**Comment by helfrij** [comment]
Done in #2158.

Time Estimate: 8 hours.

@dretrex?

**Comment by dretrex** [comment]
For both of us.  I'll double it.
