### ISSUE TITLE
Crash between scans

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2155]
Ian C. reported this morning that he experienced a crash sometime over the past week. The crash happened somewhere between scans (in a loop?). He says all data for the first scan appears to have been saved properly and is recoverable. He thinks it may be related to #2154. I don't have a good sense yet of what exactly would cause the crash, further investigation likely required.

**Comment by epengr** [comment]
@helfrij, this may not be Zebra related...  I started a XANES scan with a large number of iterations Friday evening and it crashed after during (or just before?) the 6th one.  I have it running scans in debug now, hoping to catch it again.

**Comment by helfrij** [comment]
That's interesting, @epengr, keep us posted.

Asked Ian C. some more followup questions. The scans were XANES scans being executed in a loop. The previous scan was exported successfully, the crash appeared to happen in the initialization of the next scan.

**Comment by dretrex** [comment]
VESPERS has reported a similar issue as well.  I'll look into whether they were running XANES in a loop or if it was maps.

**Comment by helfrij** [comment]
@epengr just pointed out that the problem may not have anything to do with XANES scans specifically, they are short and are run in loops the most often. But, if that's the case, we would expect the 'rate of crashes' to be the same, though, regardless of what kind of scan was being run. Right?

**Comment by dretrex** [comment]
I followed up with Peter and he mentioned that the crashes happened with both XAS and mapping.  So there might be some correlaton, but not necessarily :(

**Comment by dretrex** [comment]
Hey @helfrij, has there been any more comments about crashing recently?

**Comment by helfrij** [comment]
Not recently. For a while there, the application was running through gdb. That could play a part in how often the crash happens. Because of the recent power outage, I can't say for certain that all scans run on Side last week were using the Zebra, though those kinks should be ironed out now. It might be an interesting experiment to run the application outside of gdb this week, and see if the crashes start happening again.

**Comment by dretrex** [comment]
Indeed!

**Comment by helfrij** [comment]
I haven't heard of this happening recently. I'll open a new issue and reference this one if I hear of it happening again.
