### ISSUE TITLE
Detector ROIs don't seem to be saved properly when changed

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2161]
@dretrex and I ran many scans to test for #2151 and we noticed that the ROI information for the Ge detector was not continuous between Acquaman instances/sessions. We had to modify the ROIs to be just the Se Ka edge every time we started the application up.

Edit:

If I start a brand new application with no previous data/configuration information, add an ROI to the detector in the detector view, close the application, and open it again, the ROI is not saved. This suggests to me that there is a problem in pushing ROIs to the user configuration. Inspecting the user configuration ROIs table for this application in a database viewer confirms that the table exists and is empty. The user configuration table has one entry.

If I complete a scan, then the AMRegionOfInterest, BioXASXASScanConfiguration_regionsOfInterest, and BioXASUserConfiguration_regionsOfInterest tables update, as confirmed with a database viewer. If I then close and open that application again, the ROI appears in the detector view as we would expect.

Things to check:
- ROIs are tied to scans. It doesn't mean anything to set an ROI in the XRF detector view, but never run a scan.
- ~~The application where this problem was noticed may have more than one entry in the user configuration table (?). The user configuration that's read on startup isn't the one associated with the updated ROIs.~~ There only appears to be one entry in the user config table, for the application where the bad behavior is noticed.

**Comment by XuetaoLiu-CLS** [comment]
@helfrij 
The userConfiguration has a copy of ROIs, which should be updated/saved when the ROIs of XRF detector ROIs are changed. When application is loaded, ROIs of the userConfiguration will be loaded and populated to the XRF detector.

Are you ok if I took this issue to have a look?

**Comment by helfrij** [comment]
Sure!

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 1 hour
