### ISSUE TITLE
PGM Components - Energy

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2162]
Components need a PV representation and be controlled by an editor.

**Comment by dleacock** [comment]
fcbaf5e470a8faf9b

**Comment by dretrex** [comment]
Hey @davidChevrier, make sure you push up your changes so that when you paste in your commit stub like that it properly links.

**Comment by davidChevrier** [comment]
Me or @dleacock ?

**Comment by dretrex** [comment]
Well, it's a good thing for you to remember too :P 
But yeah, I meant @dleacock.

**Comment by dleacock** [comment]
That's what I wanted to talk to you about.

**Comment by dleacock** [comment]
218d56470039

**Comment by dretrex** [comment]
Done in #2212.
Time Estimate: 10 minutes
