### ISSUE TITLE
PGM Components - VAM

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2163]
I forgot what this is :(  It is likely still something that a straight forward PV/editor combo should suffice.

**Comment by helfrij** [comment]
Top blade:
SMTR16113I2001:step
:enc:fbk
:status
:stop

Bottom blade:
SMTR16113I2002:step

Outboard blade:
SMTR16113I2003:step

Inboard
SMTR16113I2004:step

**Comment by helfrij** [comment]
Done in #2379.

Time Estimate: 1 hour.
