### ISSUE TITLE
PGM Components - Shutters and Valves

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2164]
All the important valves and shutters will need to be added using CLSExclusiveStateControls.

**Comment by dleacock** [comment]
@dretrex How would you like me to proceed on this issue? All valves and shutters are added but untested and I'm unsure if I've added ones that won't be needed or not.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 4 hours

@dleacock can you add your estimated time on this issue? Thanks.

**Comment by dleacock** [comment]
Time Estimate: 4 Hours.
