### ISSUE TITLE
PGM Components - Exit slits

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2166]
Needs controls and editor.

**Comment by XuetaoLiu-CLS** [comment]
Slit Position"
   Exit poistion: Branch A: PSL16114I2101:X:mm:fbk
   Exit poistion: Branch B: PSL16114I2201:X:mm:fbk

Slit Width
   Exit Slit, Branch A: PSL16114I2101:Y:mm:fbk (?? PSL16113I2001:Y:mm:fbk)
   Exit Slit, Branch B: PSL16114I2201:Y:mm:fbk

Entrance Slit:
   Entrance Slit: PSL16113I2001:Y:mm:fbk (?? PSL16114I2101:Y:mm:fbk)

**Comment by dleacock** [comment]
What's the difference between the PSL and SMTR version of the same pv? For example,  PSL16114I2101:X:mm (I pulled this off their EDM screen) and  SMTR16114I2104:mm. Both give the same value.

**Comment by XuetaoLiu-CLS** [comment]
SMTR should be the real motor control, and PSL ones are the calculated version.

**Comment by iainworkman** [comment]
Time Estimate: 2 hours
