### ISSUE TITLE
PGM Scanning - XAS

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2171]
Need to be able to do an XAS scan.  Needs all the regular fixings with a configuration, view, and controller.

**Comment by dretrex** [comment]
This requires #1399 to be completed.

**Comment by iainworkman** [comment]
I would like to at least observe this one. I missed out a little on really getting into the scanning system during the last month push on SGM.

**Comment by dretrex** [comment]
Sure thing. I was planning on tackling it pretty early tomorrow.



Sent from my iPhone

On Jun 1, 2016, at 12:37 PM, iainworkman <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to at least observe this one. I missed out a little on really getting into the scanning system during the last month push on SGM.

-

**Comment by dretrex** [comment]
Done in #2376.
Time Estimate: 5 hours
