### ISSUE TITLE
Name not updating correctly on BioXAS XAS scan configurations

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2182]
The name of the scan doesn't appear to update with the chosen scan name in the configuration view.

**Comment by helfrij** [comment]
It looks like the scan configuration view correctly modifies/displays the user scan name variable as the scan's name. Is this the correct way to handle the scan name?

**Comment by dretrex** [comment]
Unfortunately, no :(  The user scan name is useless in almost every regard.  Just use `AMDbObject::name()`.

**Comment by helfrij** [comment]
Done in #2186.

Time Estimate: 20 minutes.

**Comment by helfrij** [comment]
Hey @dretrex, I did a quick check to see if `setUserScanName()` is used elsewhere in the framework, maybe someone else made the same mistake as I did. It looks like there are a lot of usages in various scan configuration views. I guess I'm asking if these are correct, and if I should take care of these usages as well.

**Comment by dretrex** [comment]
If there are used elsewhere it's probably as the following?

```c++
setName(name);
setUserScanName(name);
```

If that's the case, then yeah, may as well remove them too.
