### ISSUE TITLE
Don't export MCA spectra by default

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2185]
Although the data is collected, the MCA spectra should not be exported by default since the ROIs are much more important for EXAFS users.

**Comment by helfrij** [comment]
Is there a setting I should look for here that you know of, @dretrex?

**Comment by dretrex** [comment]
All you should need is the `AMExporterOptionGeneral::setIncludeHigherDimensionSources(false);`.

**Comment by helfrij** [comment]
I'm guessing there should be some way to turn this on when desired, an option in the scan configuration view maybe?

**Comment by dretrex** [comment]
Yeah, probably.  You may want to add it to the BioXASScanConfigurationDbObject.  Probably default it to false based on recent discussions.

**Comment by helfrij** [comment]
Kk makes sense. Thanks!

**Comment by helfrij** [comment]
Should this flag be a function of whether or not there is an XRF detector added to the configuration? I'm thinking it may not make sense for something like `bool exportMCAs_` to be true if there isn't a Ge detector added to the configuration.

**Comment by dretrex** [comment]
Potentially.  It doesn't really matter because if there are no 1D sources then the exporter won't export it anyway.

**Comment by helfrij** [comment]
That's true. I was thinking more of how this could be visualized, likely as a checkbox in the scan configuration view. It may not make sense for the box to be checked and look like it's going to export MCAs, if there would be no data to export.

**Comment by dretrex** [comment]
It's visibility could be tied to the 32 element detector being checked?

**Comment by helfrij** [comment]
Done in #2190.

Time Estimate: 1 day.
