### ISSUE TITLE
Further investigate SSRL mono settling time.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2195]
The settling time for the monos was increased from 0.01s to 0.1s as part of #2181. The number 0.1s was chosen because it was large enough that the 'jagged' data observed with the smaller settling time no longer appeared. Why the jagged data appears at all, however, is poorly understood.

If we perform an XAS scan and the bragg motor's :moving, :status, and setpoint PVs are camonitored, we see that for virtually all points in a scan the output reads something like:

...
SMTR1607-5-I21-12:deg:sp  XXX
SMTR1607-5-I21-12:moving  STEP-CCW
SMTR1607-5-I21-12:moving  STOPPED
SMTR1607-5-I21-12:status   MOVE ACTIVE
SMTR1607-5-I21-12:status   MOVE DONE
SMTR1607-5-I21-12:deg:sp  XXX
SMTR1607-5-I21-12:moving  STEP-CCW
SMTR1607-5-I21-12:moving  STOPPED
SMTR1607-5-I21-12:status   MOVE ACTIVE
SMTR1607-5-I21-12:status   MOVE DONE
...

For the jagged points, the output instead reads something like:

...
SMTR1607-5-I21-12:status   MOVE ACTIVE
SMTR1607-5-I21-12:deg:sp  XXX
SMTR1607-5-I21-12:status   MOVE DONE
SMTR1607-5-I21-12:moving  STEP-CCW
SMTR1607-5-I21-12:moving  STOPPED
...

This seems to suggest that in scans, we are actually offset by a certain amount with most points and the offset is occasionally 'corrected' at some points throughout a scan. When this happens could be the result of which PVs happen to update first.

We know the mono is running in "open loop" mode right now, and we expect this to mean that all mono moves succeed as a consequence (ie. there are no bragg motor move retries--check this).

We know that move retries are used in AM to make sure that a motor gets to a setpoint within a certain deadband. Retries are also used because we know that a motor move may report as MOVE DONE before the motor feedback PV updates with the new motor position--the retry would allow us to get the updated value if the difference is big enough.

Some things to investigate:
- What exactly does "open loop" mean, and how does this impact motor moves?
- Would implementing something in AM that forces a control to wait for the MOVE DONE and the feedback PV update fix the problem? It has been suggested that this might work in "open loop" but not for "closed loop".
- If this is purely a timing issue, the 0.1s settling time is generous. Changing the settling time to 0.02s should achieve the same effect.

**Comment by helfrij** [comment]
The BioXAS and AM groups discussed this at the meeting this morning. The agreed solution for right now is to change the settling time from 0.01 to 0.1, which was done in #2184. @dretrex is this issue closable?

**Comment by dretrex** [comment]
I would say so.  But we should create an issue that deals with the event ordering.

**Comment by helfrij** [comment]
The issue of motor status ordering to be addressed in #2207.

**Comment by davidChevrier** [comment]
Time Estimate: 1 hour
