### ISSUE TITLE
Perform dark current measurement in scan initialization, if needed.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2202]
I spoke with Gosia today. It would be a good idea for scans to perform a dark current measurement as part of scan initialization, if the current dark current values for the scaler channel detectors are invalid (ie. if a user forgets to take a measurement).

**Comment by helfrij** [comment]
Done in #2204.

Time Estimate: 1 hour.

**Comment by dretrex** [comment]
One question about the change to not opening the shutter if it wasn't originally open, if it was part of scan initializations and the shutter was closed for some reason, is there another action that handles ensuring the shutter is open?

**Comment by helfrij** [comment]
Haha, nope. Not yet. The beam status control was originally built for this purpose, but is presently incomplete: we don't have setpoints for the mirror mask and the mono mask yet, that's why the beam status is read-only right now. That's also why it was important to have the beam status bar added to the persistent panel, so users could see right away if there was a problem with shutters (and, unfortunately, fix it themselves for now). 

I don't think we always want to run scans with the shutters open, however, I think a good solution may be a little more complex than just opening the shutters automatically. I'm open to suggestions if you see a better way of doing this, as it's something that could certainly stand to be improved.

**Comment by dretrex** [comment]
Good point.  I don't have any suggestions at the moment though.  Something to ponder!

**Comment by helfrij** [comment]
Hey @dretrex, have you seen this Epic issue thing??
