### ISSUE TITLE
IDEAS "Beam On" button won't open PSH2

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2238]
EDM can open it no problem.

in [AMControlMoveAction3]: There was an error moving the control 'Photon Shutter 2' into position, because the control reported it cannot move.. Please report this problem to the beamline staff.

**Comment by helfrij** [comment]
Hey @dretrex, could this be related to #2089?

**Comment by dretrex** [comment]
I'd bet money on it.

**Comment by epengr** [comment]
Indeed, thanks!

Shall I close out this one as duplicate?

**Comment by dretrex** [comment]
Probably a good idea.  I'll close this one and mark the other one as a framework issue seeing as it is no longer VESPERS specific.

**Comment by epengr** [comment]
I can't replicate the issue the user tried to explain to me over the phone, but I did notice that AM is trying to open SSH1 and PSH2 at the same time.  PSH2 protects SSH1, so SSH1 must be open first.  The PSH2 open request is therefore being ignored.  

This doesn't result in an error message though, so there could be two issues at play here.

**Comment by dretrex** [comment]
The original issue you mentioned only happens over an injection.  It behaves correctly for all other cases.
As for your other issue, are they in a sequential list or a parallel list?

**Comment by epengr** [comment]
I was looking at this today.  That error only appeared for that user (after an injection), I'll try after the injection tomorrow morning to see if there's an error.

However, if I close all the shutters myself, AM doesn't open the frontend shutters properly (but doesn't give an error).  It is a sequential list, but it's not waiting for the open to succeed before moving on, it seems?

**Comment by epengr** [comment]
@dretrex, I can't reproduce the error, after injection or not.  I'll chalk it up to a transient CA communication loss and just go ahead and fix the time issue.  

@helfrij, does the CLSExclusiveStatesControl behave differently than the CLSBiStatesControl in term of how it determines/reports completion of the action?   This issue seems to be that it's instantly done and doesn't wait for the SSH to finish opening before it tries to open the PSH.

**Comment by epengr** [comment]
Time Estimate: 10 minutes
