### ISSUE TITLE
Rename move method in SGMEnergyCoordinator

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2242]
In an effort to keep warnings down, I'd like to rename:

```c++
virtual FailureExplanation move(double targetSetpoint, double time);
```

to something else.  I understand the desire to keep the same name for the behaviour, but I think this could do with a renaming.  Maybe `coordinatedMove()`?

Warning message:

> AMPseudoMotorControl.h:69: 
> hidden overloaded virtual function 'AMPseudoMotorControl::move' declared here: different number of parameters (1 vs 2)

**Comment by iainworkman** [comment]
Time Estimate: 10 minutes
