### ISSUE TITLE
Acquaman crash Issue

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2253]
The user reported that SXRMB Acquaman crashed several times in the past weekend. In the crash reports, there are four crashes. But only one of it has some stack information.

/home/acquaman/AcquamanApplicationCrashReports/SXRMB/2016/report_SXRMBAcquaman_OPI1606-602_04162016_144134_23696.txt

**Comment by XuetaoLiu-CLS** [comment]
This looks like a framework issue. I saw similar stack trace on the other beamlines as well.
file:///home/acquaman/AcquamanApplicationCrashReports/VESPERS/2016/report_VESPERSAcquaman_OPI1607-003_04202016_093646_8132.txt

**Comment by XuetaoLiu-CLS** [comment]
Both crashes happened when the exporter is trying to generate the ROI header strings.

:thought_balloon: My guess for the root cause is that when a scan was going, the user/staff changed the ROI of the XRF detector. After the scan is done, we tried to loop through the ROIs for header string. Unfortunately, the ROIs were changed and caused a crash.

I need to verify the hypothesis though :game_die:

**Comment by dretrex** [comment]
That shouldn't be a problem, but it could be possible that something has already deleted the regions of interest associated with the scan configuration (since the regions of interest on the detector are not relevant).

**Comment by XuetaoLiu-CLS** [comment]
@dretrex I just verified this on SXRMB. This crash will happen when you add/remove ROI during a scan. I think this is a good candidate to introduce Michael our system, since we need to touch detector, scan configuration, scans, exports. I will work with Michael tomorrow.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimates: 3 days.
