### ISSUE TITLE
Implement "safe" limits for select controls on Side

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2264]
Ian C. requests that some controls on Side have minimum and maximum limits implemented, preventing users from mistakenly entering bad/nonsensical values and sending controls to undesired positions. The desired behavior in AM is that bad input values are rejected, the control does not move.

This issue will address adding limits for the following controls:
- [x] M1 mask upper blade
- [x] M1 upstream bender
- [x] M1 downstream bender
- [x] M1 height
- [x]  M1 lateral
- [x]  M1 pitch
- [x]  M1 roll
- [x]  M1 yaw
- [x]  Mono height
- [x]  Mono mask upper blade
- [x]  Mono mask lower blade
- [x]  M2 upstream bender
- [x]  M2 downstream bender
- [x]  M2 height
- [x]  M2 lateral
- [x]  M2 pitch
- [x]  M2 roll
- [x]  M2 yaw
- [x]  Be window height

The M1 and M2 mirror bend radius pseudomotors also have desired limits, but they will likely be handled separately in #2049.

**Comment by helfrij** [comment]
Hey @dretrex. About half of these controls are PV controls, and there isn't really a mechanism for setting the min/max limits for PV controls yet (#2052). The effect that Ian C. wants could still be achieved right now by setting the min/max limits on the editors instead of the AMPVControls, but it's less "safe". Is this an acceptable alternative for now? Or should I tackle trying to find a way to set control limits first?

**Comment by epengr** [comment]
if they are PVs, then you can use the PVs .DRVL and .DRVH fields to set soft limits at the EPICS level.

**Comment by epengr** [comment]
Ignore my suggestion.   DRVL and DRVH will drive to the min/max value if you request a move outside that range.  Even worse, it seems that you can use relative moves to go beyond that values even still!

**Comment by helfrij** [comment]
Done in #2264.

Time Estimate: 0.5 days.
