### ISSUE TITLE
IDEAS camera views lost after pulling in master

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2279]
The sample alignment panels are still there, but the camera views are gone...

**Comment by helfrij** [comment]
Hey @epengr. It looks like the camera widgets in IDEASSampleCameraPanel may not appear if AM_MOBILITY_VIDEO_ENABLED isn't set up--could that be the problem?

**Comment by epengr** [comment]
I was playing with that last week.  Removing that ifdef resulted in build errors (I wasn't sure how to debug pre-processor statements like that), so something with QTMobility might be messed up?  

Do you know of any changes to any of that recently?  

It would be great to get this working before Science Odyssey starting Friday...

**Comment by epengr** [comment]
@dretrex 

We solved this!

in AMMobility.pro 
```equals($$USE_MOBILITY_QT, 1) {```
should be 
```equals(USE_MOBILITY_QT, 1) {```

equals needs a variable, not a value, for the first argument.

We also noticed that
```equals($$AM_ENABLE_BOUNDS_CHECKING, 1)```
in AMCommon.pri has the same typo, but we didn't want to change it not knowing what all would be effected.

I just made the change to AMMobility in the rangdom branch I am on for the moment, let me know how you want to proceed with this issue.

@helfrij is really good at this stuff!

**Comment by helfrij** [comment]
REIXS will likely have a similar problem, as they may not have their own AMBuildConfig.pri settings set.

**Comment by epengr** [comment]
Hotfix merged in with #2292 

Time Estimate: 3 hours

@helfrij, you spent 3 hours on it with me, I believe?

**Comment by dretrex** [comment]
Nice work, @helfrij!
