### ISSUE TITLE
XRF detector view to show dead time buttons for enabled and disabled elements

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2285]
Right now, disabled detector elements are excluded from the XRF detector view entirely for the Ge detectors on BioXAS--the controls corresponding to disabled elements aren't created at all. It would be handy to be able to have visualizations for all of the Ge detector elements in the XRF detector view, so that the position of the dead time buttons mirrors the way the elements are physically arranged. In certain situations, knowing the 'geography' of the elements can be helpful, particularly in identifying 'hot spots'.

**Comment by dretrex** [comment]
I'm assuming these hot spots will be elements they wish to discard since they are probably getting some diffraction peaks?

**Comment by helfrij** [comment]
I expect that's something that they will maybe want to do eventually. But right now, they seem to be just interested in having the buttons reflect element arrangement.

**Comment by helfrij** [comment]
Done in #2286.

Time Estimate: 1 day.
