### ISSUE TITLE
Make BioXASBeamlineStatus/view a CLS general class so that the other beamline (PGM) can use it

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2342]

**Comment by helfrij** [comment]
Do you mean the BioXASBeamStatusView? If so, I'm not sure it's ready for that yet, until a fairly significant refactor is complete (#2127).

**Comment by XuetaoLiu-CLS** [comment]
yes... along with the corresponding BioXASBeamStatus class,

**Comment by helfrij** [comment]
Okay, good luck! Let me know if you have any questions.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 1 day
