### ISSUE TITLE
Facilities combobox is blank

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2345]
When starting a new run using BioXAS Main application, there is an option to enter a run name and select a facility. The facility combobox appears to be empty.

There may not be facility options to display anymore, given the recent refactor in #2225. If that's the case, the box should be removed.

**Comment by XuetaoLiu-CLS** [comment]
Time estimate: 2 hours

**Comment by helfrij** [comment]
Just tried creating a new run again on a branch up-to-date with master, and I see the same problem.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 4 hours
