### ISSUE TITLE
Refactor REIXS/CLS to use AMControl child control methods with bool returns.

### ISSUE THREAD

**Issue by mButlerDM** [acquaman/acquaman#2351]
Refactor code logic to take advantage of changes to addChildControl() removeChildControl() and clearChildControls() in AMControl and inherited classes in AM.

**Comment by mButlerDM** [comment]
Time Estimate: 1 hour

**Comment by XuetaoLiu-CLS** [comment]
@mButlerDM remember to change the AM related classes as well.
