### ISSUE TITLE
Minor ROIs refactor -- checking for duplicates

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2375]
BioXAS and PGM applications both check whether the user configurations and the XRF detectors have an ROI before adding them to each class, in the app controller. This was added to BioXAS because there was a problem there where duplicate ROIs were being added to the detector, and PGM got that change as well. It would probably be a good idea to check whether this is something we can add to the user configuration/app controller and XRF detector at a more general level, just in case this happens in other beamline applications.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 1 hour
