### ISSUE TITLE
Polish up the XAS scan configuration

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2377]
Now that scanning is working and once we implement the scan axis view we will need to add some polish to ensure that selections and configurations are possible.  Such selecting whether you are using the Ocean Optics spectrometer or other standard options.  We also need to incorporate the Ocean Optics Spectrometer into the scan configuration and controller in a similar way as is used on other beamlines.

**Comment by mButlerDM** [comment]
Time Estimate: 1 day
