### ISSUE TITLE
Occasional crashes in QSortFilterProxyModel::parent() on startup.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2389]
The BioXAS Side application appears to crash sometimes on startup, and gdb cites `QSortFilterProxyModel::parent()` as the problematic method. Since the proxy model is part of AMMainWindow, I would bet other applications have/will experience this too. 

This class has a few implementations of `parent()`: one that returns the model's parent, and one that returns the parent of an item with a particular QModelIndex. My feeling is that it's more likely a problem related to the latter option.

The crashes seem to have started recently, so they may be related to changes in #2380. Because they only happen sometimes, it's possible the problem may have been present in the (also recent) introduction of the proxy model in #2356.

Update:
When the application starts up successfully, debug messages sometimes appear in the terminal window: "QSortFilterProxyModel: index from wrong model passed to mapFromSource." If an incorrect or invalid index is used, I could see this potentially causing a "parent" type problem.

**Comment by dretrex** [comment]
VESPERS has mentioned that sometimes the app crashes on startup too!  Great catch!

**Comment by helfrij** [comment]
Done in #2398.

Time Estimate: 1.5 days.
