### ISSUE TITLE
Side UI too tall

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#2416]
Running an updated BioXAS Side Acquaman application causes the normal main window to be displayed, but it now extends totally beyond screen boundaries (bottom bar not visible). This issue will likely involve investigating what caused this change, as there haven't been any new additions to the Side UI recently.

This could also be a good opportunity to take a look at refactoring the application's tallest view (the XRF detector view) or investigating ways of making the main window more flexible.

**Comment by mButlerDM** [comment]
Time Estimate: 1 Day
