### ISSUE TITLE
PGM XAS Scan configuration view

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2443]
There are three issues with PGM XAS Scan configuration view:
- [x] There is no estimation information as the other beamlines 
- [x] There should be a label "Scan name" on the left of the scan name edit box.
- [x] The edit box is too big. Along with the estimation information label, they might be able to nest in the left layout.

**Comment by mButlerDM** [comment]
Time Estimate: 1 Day
