### ISSUE TITLE
PGM launch issues

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2444]
Issues we found/fixed when testing PGM Acquaman:
- [x] finalize PGM data folder
- [x] app crashed when launching for the first time
- [x] There no connected detectors in XAS Scan configuration
- [x] App crashed when checking/unchecking the detectors in the scan configuration

**Comment by helfrij** [comment]
The checking/unchecking of detectors in the scan configuration sounds like a problem I encountered on BioXAS too. It may be fixed already in the pull request #2409.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 1 hour

**Comment by XuetaoLiu-CLS** [comment]
@helfrij yes, I saw you add protection of the usage of configuration_. That issue is because of the uninitialized configuration_
