### ISSUE TITLE
Hide HV values

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2452]
Lucia only wants users to have the ability to turn the high voltage on or off.  We either need to hide the spin box or make it so you can only see the feedback value (which is probably still necessary I'd imagine).

**Comment by davidChevrier** [comment]
Yeah, let's make sure to be careful - literally and figuratively - with the HV. Even if On/Off is sufficient, it's probably good to have some feedback.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 30 minutes
