### ISSUE TITLE
Energy grating choice is wrong

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2454]
When showing it to Lucia yesterday, it seemed like the energy grating choice thought it was on the medium grating when it actually was on the high energy grating.  It then couldn't move off the medium grating with a tolerance error and then it would also, for some reason, cause the energy to be not connected.

@helfrij, you have had a little bit of experience with controls being disconnected with some of your more sophisticated pseudo-motor controls in the past, right?  Do you have any thoughts?

**Comment by helfrij** [comment]
Time Estimate: 1 hour.
