### ISSUE TITLE
Add branch based slit control to persistent view

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2455]
Lucia would like the current branch (A/B) slits to be displayed in the persistent view.  They should only display the slits of the current branch.  The entrance slit should also be displayed on the persistent view.

There is a quirk with the branch selection PV.  When the branch is moved (particularly to branch A), it uses a limit switch to know when it is finished moving.  Each branch is at a limit (A is at the positive stepped CW limit and B is at the negative stepped CCW limit).  Unfortunately, the motor loses steps at the A branch and the limit stops and the state will then be "Between".  Therefore, we can't really use that value PV as the definitive state of the branch selection and will have to rely on the sign of the step value to ensure we are in the correct position.

**Comment by helfrij** [comment]
Do we have feedback on whether the motor is at each limit? Could that be used to report the branch selection instead of monitoring steps?

**Comment by dretrex** [comment]
Yes, but that was the second part of my monologue in there.  It gets to the limit (that's how it knows how it's done) but then gravity pulls it off the limit.

**Comment by dretrex** [comment]
Time Estimate: 45 minutes

**Comment by dretrex** [comment]
Still need to test it on the beamline and also come up with some logic for handling the terrible drift when on Branch A.  However I am going to wait until I'm on the beamline to work on that part.

**Comment by dretrex** [comment]
@helfrij helped me out and tested tested the branch part.  It seems like the motor is behaving better today and we'll need to more time to determine if the extra piece I added actually keeps it in Branch A even if it slips a bit.

**Comment by dretrex** [comment]
Want to leave an estimate of how long you spent testing @helfrij?

**Comment by dretrex** [comment]
Done in #2485.
