### ISSUE TITLE
Auto-export is pointing to local folder rather than remote

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2457]
While showing Lucia how scans work I noticed that exported data is going to AcquamanLocalData rather than the remote location we setup.  This needs to be fixed.

**Comment by mButlerDM** [comment]
@dretrex This may be due to a file system permission error.

**Comment by dretrex** [comment]
Interesting.  Thanks, @mButlerDM!

**Comment by XuetaoLiu-CLS** [comment]
This happens because we overwrite the remote data folder with the local data folder after the first time wizard. As a result, in the Acquaman.ini, both the remote and local path are the same. 

Time Estimate: 1 hours
