### ISSUE TITLE
TEY and FLY should be preset in XAS scan configuration

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2458]
The TEY and FLY detectors should be set by default in the XAS scan configuration.

**Comment by helfrij** [comment]
I see there is commented out code in PGMAppController::setupScanConfigurations() that seems to address this issue. Do we know why that code was commented out?

**Comment by dretrex** [comment]
Probably something that was done during the initial tests and then forgotten.

**Comment by mButlerDM** [comment]
Time Estimate: 5 Minutes
