### ISSUE TITLE
Extra detectors added to PGM scans

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#2459]
It has been requested that the ring current and the undulator gap be added as detector emulators to XAS scans.  They should be in every scan and not visible or interactable.

**Comment by helfrij** [comment]
Hey @dretrex. Just to clarify, what do you mean by not visible or interactable?

**Comment by dretrex** [comment]
`visible=false` and `hiddenFromUsers=true`

**Comment by helfrij** [comment]
Ah okay. They don't need to be hidden in the XAS scan configuration view, then.

**Comment by helfrij** [comment]
Done in #2474.

Time Estimate: 1 hour.
