### ISSUE TITLE
AMSpectrumAndPeriodicTableView can't edit/change ROIs

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2470]
The selected elements will always display Fe

**Comment by XuetaoLiu-CLS** [comment]
#2464 kind of related

**Comment by mButlerDM** [comment]
Should be fixed in #2465

**Comment by XuetaoLiu-CLS** [comment]
@mButlerDM you can close this one when you finish testing with #2465

**Comment by mButlerDM** [comment]
Done in #2465
