### ISSUE TITLE
Removing a scan region from the PGM scan configuration view results in a crash.

### ISSUE THREAD

**Issue by mButlerDM** [acquaman/acquaman#2477]
Removing any scan region gives a segfault.

> 1	QLayout::removeItem(QLayoutItem *)			0x7ffff623da78	
> 2	AMStepScanAxisView::onDeleteButtonClicked	AMStepScanAxisView.cpp	292	0x852a02	
> 3	AMStepScanAxisView::qt_metacall	moc_AMStepScanAxisView.cpp	186	0x9cb295	
> 4	QMetaObject::activate(QObject *, QMetaObject const *, int, void * *)			0x7ffff59bec5a	
> 5	QButtonGroup::buttonClicked(QAbstractButton *)			0x7ffff68381ef	
> 6	??			0x7ffff65a52d7	
> 7	??			0x7ffff65a6493	
> 8	QAbstractButton::mouseReleaseEvent(QMouseEvent *)			0x7ffff65a657c	
> 9	QToolButton::mouseReleaseEvent(QMouseEvent *)			0x7ffff665b6ca	
> 10	QWidget::event(QEvent *)			0x7ffff62647b0	
> 11	QApplicationPrivate::notify_helper(QObject *, QEvent *)			0x7ffff6214b8c	
> 12	QApplication::notify(QObject *, QEvent *)			0x7ffff621b06d	
> 13	QCoreApplication::notifyInternal(QObject *, QEvent *)			0x7ffff59ac3dd	
> 14	QApplicationPrivate::sendMouseEvent(QWidget *, QMouseEvent *, QWidget *, QWidget *, QWidget * *, QPointer<QWidget>&, bool)			0x7ffff621a7f3	
> 15	??			0x7ffff628c9d8	
> 16	QApplication::x11ProcessEvent(_XEvent *)			0x7ffff628adac	
> 17	??			0x7ffff62b0b02	
> 18	g_main_context_dispatch			0x7ffff2fb47aa	
> 19	g_main_context_iterate.isra.24			0x7ffff2fb4af8	
> 20	g_main_context_iteration			0x7ffff2fb4bac	
> 21	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)			0x7ffff59d4ac5	
> 22	??			0x7ffff62b0b96	
> 23	QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)			0x7ffff59ab7cf	
> 24	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)			0x7ffff59aba2d	
> 25	QCoreApplication::exec()			0x7ffff59afde9	
> 26	main	PGMMain.cpp	56	0x94e771

**Comment by XuetaoLiu-CLS** [comment]
@mButlerDM nice catch. 

I did a quick look. The following changes will fix the crash:
ln292 `	scanAxisViewLayout_->removeItem(layoutMap_.value(button));`

**Comment by XuetaoLiu-CLS** [comment]
As mentioned, the popup menu also has a location issue. We might need to compare with the implementation of `AMEXAFSScanAxisView`

**Comment by mButlerDM** [comment]
Time Estimate: 1 Hour

Done in #2499
