### ISSUE TITLE
unique AMRun name

### ISSUE THREAD

**Issue by XuetaoLiu-CLS** [acquaman/acquaman#2479]
the name of AMRun is not unique, which makes it possible to have multiple runs with the same name. This make the choose Run dialog unfriendly.

It might be better to add a restriction to the AMRun table that the AMRun names should be unique

**Comment by dretrex** [comment]
I don't think that is necessary.  Names are meant to be chosen by users and if they really wanted to have two "My Science" runs then it's not really our job to stop them.
