### ISSUE TITLE
IDEAS: Investigate missing slot

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2534]
Noticed this while running put of QtCreator, I imagine ti should be looked into:

`Object::connect: No such slot IDEASXASScanConfigurationView::updateFluorescenceDetectorComboBox(int) in ../acquaman/source/ui/IDEAS/IDEASXASScanConfigurationView.cpp:75`

**Comment by epengr** [comment]
Also:

Object::connect: No such slot IDEASAppController::onActionImportAcquamanDatabase()

**Comment by iainworkman** [comment]
psst.
I think you might be looking for [here](https://github.clsi.ca)

**Comment by epengr** [comment]
@iainworkman,

Actually, I thought I'd found it [here](http://www.ibuyoldslots.com/): 

But I eventually sorted it out [here](https://github.clsi.ca/SystemsTechnology/acquaman/issues/2674).

**Comment by epengr** [comment]
Damned browser history...
