### ISSUE TITLE
Bug in combined behaviour of exporting and workflow/actions/controls

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#293]
This is a very behaviour-specific bug that happens when auto-exporting a large scan while using the workflow.

The exact line of code that is the culprit is in AMExportController::start():

```QTimer::singleShot(0, this, SLOT(continueScanExport()));```

Since the exporting of the scan isn't immediately put on the function stack, the scan continues on it's merry way and tells the workflow to start the next scan.  It does so and during the initialization of the next scan the continueScanExport slot is evoked.  Since writing the spectra files takes a very long time, the move start/move finished timeout happens in AMControl notifying that the control has not reached its destination in time.  Thus notifying the action that it failed, then the initialization actions fails, then the scan fails, and the workflow stops.

As a solution, maybe we should invest the time to make the exporter write the file in a separate thread?

As an interim solution, I would like to change the start method to the following:

```AMExportController::start(bool autoExport = false)```

and replace the culprit code with:

```
if (autoExport)
	continueScanExport();
else
	QTimer::singleShot(0, this, SLOT(continueScanExport()));
```

Thoughts?  Suggestions?

**Comment by davidChevrier** [comment]
Time Estimate: 1 day
