### ISSUE TITLE
Implement Continuous, Buffered Data Collection

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#566]
Need to create buttons and some logic, the guts are already done on the server side.

**Comment by dretrex** [comment]
Since this is going to be associated with the new data server, can we just close this @iainworkman @davidChevrier ?

**Comment by iainworkman** [comment]
Yes, I imagine there will probably be new issues created for the data
server in relation to the SGM upgrade.

**Comment by dretrex** [comment]
@davidChevrier, this is a moot issue now because of the data server, right?

**Comment by dretrex** [comment]
This will be handled by the new data server.
