### ISSUE TITLE
SGM Visible Light Valves

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#631]
The creation of the visible light on actions should move from SGMSideBar::onVisibleLightClicked() to the SGMBeamline class (maybe SGMBeamline::createVisibleLightOnActions() ) and that should be called in the SGMSideBar function. Also, that actions list should start by calling SGMBeamline::createBeamOnActions() and prepending that to the list of visible light on actions.

**Comment by dretrex** [comment]
@davidChevrier do you want to keep this issue open or do you want to close it like you did the pull request?

**Comment by dretrex** [comment]
@davidChevrier, you had your chance :P

**Comment by davidChevrier** [comment]
Yes. Yes I did. This is a shame of me. ;P
