### ISSUE TITLE
Potential memory bug with QPixmap and Xorg

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#663]
There may be a bug where memory used for writing pixmaps is not properly released when no longer in use.  Unfortunately, this bug manifests itself as a memory leak in Xorg.  Over the weekend, the memory on one of the VESPERS OPI's had Xorg taking up 2.5 GB even when everything is closed.

**Comment by dretrex** [comment]
@davidChevrier, considering what we've all collectively learned about how memory is managed and that we are going to have diagnostics to monitor this stuff in the end.  I am in favor of closing this - primarily because it hasn't really manifested itself again.  Thoughts?

**Comment by davidChevrier** [comment]
I agree. Between memory improvements we've made and asking qt to do the draw using the -graphicssystem raster in the runAcquaman.sh script I think we've made progress. I'll close it and we can link against it in the future if we need to.
