### ISSUE TITLE
REIXS Rebuild REIXSSidebar without UI elements

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#668]
Manually build a sidebar GUI for REIXS that doesn't use the UI editor so I don't have to pull out hair every time I need to modify it.
Possibly re-imagine it at the same time as it's getting crowded.

**Comment by dretrex** [comment]
This is going to be done in #1374.  Closing here but flagged for reference.  Just for reference, do you remember how much time you spent on this issue @epengr?

**Comment by epengr** [comment]
All the time I spent on it was in changes made in #662, and the hours are reported there.
