### ISSUE TITLE
Glitch data points in REIXS scans

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#674]
Data points the seem to have the same or very similar values the previous point when they really shouldn't.  Needs exploration - likely a real (physical) mono issue, but there could be other explanations.

![scan glitch](https://cloud.githubusercontent.com/assets/677939/3317540/59b4d464-f70e-11e3-9882-ff2ae8ba5ab6.jpg)
![scan glitch2](https://cloud.githubusercontent.com/assets/677939/3317545/5c8c8ac4-f70e-11e3-9806-7a2357174ccf.jpg)

Oh, and these are not on region boundaries.

**Comment by dretrex** [comment]
I'm having this issue now too.

**Comment by dretrex** [comment]
@davidChevrier and I came up with a fix for this.  We have another issue for a possible better solution to the problem, but the problem as described in this issue should now be completely fixed.  I'm going to close it out for the time being.

Took both @davidChevrier and myself about 6 hours for everything including testing.
