### ISSUE TITLE
REIXS: Numerous energy move/tolerance issues

### ISSUE THREAD

**Issue by AcquamanIssues** [acquaman/acquaman#678]
13007 in [AMControlMoveAction3]: There was an error moving the control 'beamlineEV' into position. Target: 858 eV. Actual position: 858.033 eV. Tolerance 1.79769e+308. Reason: An undocumented failure happened.. Please report this problem to the beamline staff.

**Comment by XuetaoLiu-CLS** [comment]
The tolerance is defined as `1000` not `1.79769e+308`. Need some test for this one.

AMPVwStatusControl* directEnergy = new AMPVwStatusControl("beamlineEV", "REIXS:MONO1610-I20-01:user:energy:fbk", "REIXS:user:energy", "REIXS:status", "REIXS:energy:stop", 0, 1000);

**Comment by XuetaoLiu-CLS** [comment]
This actually happens clicking "Stop" when moving energy

**Comment by dretrex** [comment]
That's likely because when you stop it will change the status away from "Move Active" and then it will check to see if it is within tolerance.

**Comment by XuetaoLiu-CLS** [comment]
Took about 1 hr

**Comment by dretrex** [comment]
Done in #1405.
