### ISSUE TITLE
Replace SGM Ready.db System

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#686]
The SGM's ready.db EPICS softIOC is starting to show it's age. We should move to a newer system like the AmptekCoordinator or AddOnsCoordinator to take control of some of these features.
* Mass valve control - Beam On / Beam Off
* Visible Light Control
* Endstation selection
* Status reporting for beam availability and problems that occur.

@regiert can you think of other features you want included?

**Comment by iainworkman** [comment]
This no longer applies to the upgraded version of SGM Acquaman. Closing out.
