### ISSUE TITLE
Implement Generic File Repair for CDF Files

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#717]
We are backing up the CDF files with an ASCII file. We need a way to do the repair on a corrupted CDF file.

**Comment by dretrex** [comment]
This has turned into a really proven technology and we have never had to repair a CDF file once we figured out how to properly use the CDF files.  I'm going to remove the bad fixCDF code that I implemented a long time ago.  If such a thing becomes necessary in the future, we will deal with it then.

**Comment by dretrex** [comment]
Done in #1871.
Time Estimate: 20 minutes
