### ISSUE TITLE
FCApp 

### ISSUE THREAD

**Issue by dleacock** [acquaman/acquaman#731]
Rob has inquired about about the potential to create a bit of software that displays certain PV's. I have a basic working app that displays ring current as well as PSH1, PSH2 and SSH status.  

July 23rd - Re-writing code to make it adhere to the principles of OOP.  Creating BeamlineShutter Class which will contain the name of the beamline as well as PV name.

**Comment by dleacock** [comment]
@dretrex This is outdated and no longer required.  Can I close this?

**Comment by dretrex** [comment]
Yup.

Sent from my iPhone

On Jun 6, 2015, at 3:01 PM, David Leacock <notifications@github.com<mailto:notifications@github.com>> wrote:


@dretrex<https://github.com/dretrex> This is outdated and no longer required. Can I close this?
