### ISSUE TITLE
Create prototype for BioXAS side mono controls

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#737]
BioXAS beamline development is at a point where we can begin to build a monochromator class and design its display/controls. Because alignment work is ongoing on BioXAS-Side, we will be using BioXAS-Main pvs for this project.

**Comment by dretrex** [comment]
You've finished these monochromator issues (aside from those hardware issues), right @helfrij?  Or was there more to them that you wanted to do?

**Comment by helfrij** [comment]
Handled in #1118.

**Comment by dretrex** [comment]
Time estimate?
