### ISSUE TITLE
REIXS XAS scans occasionally stall while starting

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#761]
A user reported this with no details last weekend, and I think I've just observed the same thing.

Started and XAS scan (restarted the exact same scan a second time, if that maters, but from the XAS scan panel, not copying the configuration)

The scan appears to start doing it's thing, but the mono never moves, it just sits there in [Running], timer counting, nothing happening.

Scan Actions show that it completed both stages of the initialization actions, and nothing else.

As I was writing this, it seems to have "completed successfully", but with no data points...
 
Stared the scan again, the same as before, worked fine.

Should be a fun one to track down...

**Comment by epengr** [comment]
Further reports of this problem:

"I noticed on several occasions that AM froze up at the start of absorption scans. I was able to get around this temporarily by skipping the frozen scan and starting a new one. AM also seemed to get hung up on absorption scans when the beamline energy was already at the starting energy of the scan. If there is anything else, just let me know."

**Comment by epengr** [comment]
So the first occurrence of this behavior predates #1142 by a long ways...  It does *seem* that this is more common now - but it could just be that there's another, similar issue that's cropped up (#1217).

**Comment by epengr** [comment]
@dretrex, @davidChevrier, Could this be related to the crash bug that we found in scan initialization?  Some kind of transient timing issue?  Maybe even a different expression of the same bug?

**Comment by dretrex** [comment]
After chatting with @epengr, this has not happened in a long time and we are going to close it for the time being.
