### ISSUE TITLE
REIXSAppController should have code rearranged to match current App controller conventions

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#813]
While perusing through the REIXSAppController to add some code, I found that it looks and is implemented VERY differently from how every other app controller is made.  We should probably look into and spend some time getting it to match all the others for future ease.

**Comment by iainworkman** [comment]
Looking over this briefly there seems to be two paradigms at play here. 
REIXS and SGM both seem to use a similar paradigm, in which most of the startup work is done in reimplemented virtual functions inherited from AMAppController (startupRegisterDatabases(), startupCreateUserInterface(), startupAfterEverything() etc.). BIOXAS main, side, VESPERS, SXRMB and IDEAS all nominally just use a reimplemented startup() function to do their work (passing it off to functions they define themselves such as registerClasses(), setupUserInterface() etc.)

Should this issue then be extended to SGM too - or is the REIXS and SGM method preferable and should be extended out to the others?

**Comment by dretrex** [comment]
@davidChevrier can correct me if I'm wrong, but the SGM application in its entirety will likely be redone.  I think we'll probably be better off starting from scratch rather than worrying about adding/removing code.

**Comment by iainworkman** [comment]
Sounds good to me.

Thanks Darren.

**Comment by dretrex** [comment]
Done in #1383.  Time estimate?

**Comment by iainworkman** [comment]
Time Estimate: 3 hours
