### ISSUE TITLE
Clean up IDEASXRFDetailedDetectorViewWithSave & IDEASBeamline detector references

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#824]
Move ketek peaking time and gain out of IDEADBeamline and in to IDEASKetekDetector

Remove Ketek specific references in IDEASXRFDetailedDetectorViewWithSave and generalize it for use with any XRF detector.

**Comment by dretrex** [comment]
Hey @dleacock, I believe you are doing this as part of one of the other issues, right?  Which one was it?

**Comment by dretrex** [comment]
I think it's #1159.  I'm going to close this issue out since you are already handling it in #1441.
