### ISSUE TITLE
SR570 sensitivity PV: sens_put, sens_num and sens_unit are out of synch

### ISSUE THREAD

**Issue by XuetaoLiu-S** [acquaman/acquaman#842]
On SR570, when we set values for sens_put PV, the sens_num and sens_unit PVs are not updated automatically. We need to manually change the values of sens_num and sens_unit to the proper ones.

We should also disable these sensors from populating the changes to sens_put PV via changing DISV and DISA value.

**Comment by XuetaoLiu-CLS** [comment]
Time Estimate: 5 days
