### ISSUE TITLE
Remove UI Files for AMSamplePlateSelector

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#874]
Incorporate generated code from AMSamplePlateSelector.ui into AMSamplePlatePre2013View.h and AMSamplePlatePre2013View.cpp.

Part of the super issue #830

**Comment by dretrex** [comment]
Bump.  Maybe we can get this tested sometime in the near future?

**Comment by iainworkman** [comment]
I'd left this too long to test, so I've had to torch the branch and re-do the changes. Luckily this was a small change.

**Comment by iainworkman** [comment]
Altered:

- AMSamplePlatePre2013View ~ Moved across all the member widgets and initialization code from ui.h file

8b8a62e445b05e76d446225b6f61d86763385da3

**Comment by iainworkman** [comment]
Removed .ui file for AMSamplePlateSelector

a3ac26e3a85375cf77eb6474e191a75cdf912b45

**Comment by dretrex** [comment]
This was merged in with #1199.  Time estimate @iainworkman?

**Comment by iainworkman** [comment]
About 2 hours

-----Original Message-----
