### ISSUE TITLE
IDEAS Scans try to create XRF ABs when they shouldn't

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#875]
If a user chooses an XRF detector and region, but deselects "XRF scan", the the scan complains that it can't create the normalized AB because the 2D sum AB is missing.

Just need to clean up the UI to resolve this, I think.

**Comment by dretrex** [comment]
@dleacock, this would probably be a nice issue for you to tackle.

**Comment by dretrex** [comment]
... aaaaannnnddddd on second thought.  I'm going to do this as part of #1094 since the XRF scan piece will get torched in the process.  Thanks bud!
