### ISSUE TITLE
Drag & drop unavailable in data view

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#909]
Regardless of view mode, or where the initial click is, click-dragging marque selects and never allows scans to be dragged. 

I think that drag/drop is only of use for populate the "experiments", if anyone actually uses those - their now broken by this bug.

**Comment by iainworkman** [comment]
Altered:
- AMBrowseScansView::addChildView(...) ~ Now enables drag and drop in the added child view

Added:
 - AMLightweightScanInfoModel::flags(...) ~ Sets the flags to enable dragging if the index refers to a valid scan (is default for thumbs)
- AMLightweightScanInfoModel::mimeData(...) ~ Builds a mimedata object for the passed list of model indices which contain QUrls that point to the database, table and row which represents the scan.

Note:
Also includes some changes to AMLightweightScanInfo which was handling the relationship between scans and experiments incorrectly. The changes to fix this issue are not fully complete.

3d287747040925e74a78566748d434d321663bd2

**Comment by iainworkman** [comment]
Closed as rolled into general refactor #1214 

(note I'm leaving this branch for reference, so I can remember the stuff required for getting d 'n' d working in the views - Will delete it after #1214 is done)
