### ISSUE TITLE
Setup auto export for REIXS XAS scans

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#917]
Might as well have REIXS scans auto export as well.  Unless and until there's some kind of automatic/default curvature correction for XES scan, auto export is useless there.

**Comment by XuetaoLiu-CLS** [comment]
@dretrex Darren, I noticed that all beamline set XRF scan auto export false. The XAS scans should be auto-exported. If this is the case, then this can be closed.

Pls correct me if I'm wrong. Thanks.

**Comment by dretrex** [comment]
The XAS scans are not auto-exported because there hasn't been any scan configurations registered to an exporter and exporter option.  Take a look at ```VESPERSAppController::setupExporterOptions()``` for the code necessary to get auto-export up and running.

**Comment by XuetaoLiu-CLS** [comment]
took about 2hrs

**Comment by dretrex** [comment]
Done in #1391.
