### ISSUE TITLE
memcpy may not be safe to call on objects

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#922]
I'm getting a warning of type dynamic-class-memaccess on the line:

memcpy(outputValues, (axisValues_.at(axisId).constData()+axisStartIndex), (axisEndIndex-axisStartIndex+1)*sizeof(AMNumber));

Basically, this is happening because it's not necessarily safe to memcpy an object. So, the likely solution is to use doubles or ints rather than AMNumbers.

**Comment by dretrex** [comment]
Implemented the fix for the problem without refactoring the ```axisValues()``` code.  Done in #1201.  Took 5 minutes.
