### ISSUE TITLE
Implement dark current correction.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#923]
Implement dark current scaler channel views in BioXASSideScalerView. Use existing dark current-related analysis blocks to correct scan data in real-time, as its collected. Make sure that dark current correction amount and dwell time are available to the user via appropriate view widgets and are recorded/saved with scan data.

**Comment by dretrex** [comment]
This was done as part of #1264.  It has been tested and appears to work.  I'm going to close this out.  @helfrij, feel free to add some comments here if you'd like if it wasn't entirely covered in #1264.
