### ISSUE TITLE
Make a convenience static getter for AMControlMoveAction3

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#942]
Since using move actions is so common, it would be nice to have a convenient getter that builds them in a clean and succinct way.

**Comment by dleacock** [comment]
Added:
     -Changed line 906 in VESPERSBeamline.cpp
     -Added AMActionSupport.h to AMCrashMonitorSupport
     -Added <unistd.h> where needed

d063633ea62370

**Comment by dleacock** [comment]
Added:
- AMActionSupport::buildControlMoveAction()

**Comment by dleacock** [comment]
Added:
- AMActionSupport::buildControlMoveAction to SGMXASScanActionController.cpp

0c044867b7213fc6a9d

**Comment by dleacock** [comment]
Added:
- AMActionSupport::buildControlMoveAction() to VESPERSBeamline.cpp,
    VESPERSCCDDetector.cpp, VESPERSMonochromator.cpp,
    VESPERSPIDLoopControl.cpp

@dretrex : Should I remove "actions3/actions/AMControlMoveAction3.h" now that it has "AMActionSupport.h"?

89d21a010765cc26748b30ea5ceb0425abf87cd3

**Comment by davidChevrier** [comment]
Done in 5569ebe

@dleacock time estimate?

**Comment by dleacock** [comment]
Once I figured out what needed to be done it took about 6 hours.

**Comment by davidChevrier** [comment]
Thanks @dleacock much appreciated.
