### ISSUE TITLE
Cleanup BioXASSideBeamline class.

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#957]
The BioXASSideBeamline class is a little confusing and disorganized. I'd like to go through the class and neaten it up a bit. The biggest change will likely be migrating mono specific information to the BioXASSideMonochromator class.

**Comment by davidChevrier** [comment]
@helfrij can this be closed. It looks like it has a resolved pull request in #980

**Comment by helfrij** [comment]
Time estimate: 1 day.
