### ISSUE TITLE
SGM Sample Management Drawing

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#976]
While we've managed to make this more memory efficient in the last little while, the sample drawing still takes up quite a bit of processor. This makes sense, there's a lot of math going on to do it. However, we do this whether the sample management window is visible or not. I want to see if I can optimize this a little by not doing the drawing when the window isn't visible.

**Comment by iainworkman** [comment]
This no longer applies to the upgraded version of SGM Acquaman. Closing out.
