### ISSUE TITLE
Remove UI Files for AMImportControllerWidget

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#982]
Incorporate generated code from AMImportControllerWidget.ui into AMImportControllerWidget.h and AMImportControllerWidget.cpp.

Part of the super issue #830

**Comment by iainworkman** [comment]
Removed this from widget constructors in AMImportControllerWidget.cpp

a7b50f2b8b8534e47d90590c9b78261bace43905

**Comment by dretrex** [comment]
Finished in #995.  Time estimate?

**Comment by iainworkman** [comment]
About 6 hours
