### ISSUE TITLE
Remove UI Files for AMTopFrame2

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#996]
Incorporate generated code from AMTopFrame2.ui into AMTopFrame2.h and AMTopFrame2.cpp.

Part of the super issue #830

**Comment by iainworkman** [comment]
Removed this from widget constructors in AMTopFrame2

dd32310702bf2012ac8c941e1ce50ffbe9cd63ed

**Comment by iainworkman** [comment]
Set top level layout of 'this' in AMTopFrame2 constructor

2327cf6984075056f3fb18ed61198beddc42a28e

**Comment by dretrex** [comment]
Is this all done now?

**Comment by iainworkman** [comment]
Again, bringing this one up to date with current master by rebranching.

**Comment by iainworkman** [comment]
Altered:
- AMTopFrame2 ~ Moved in member variables and initialization code from ui_TopFrame2.h

3193bfc304288519a99404922edc949f6d911256

**Comment by iainworkman** [comment]
Removed:
- AMTopFrame2.ui

e83b591e12c8fb1432e04f38571c89393663322b

**Comment by iainworkman** [comment]
Altered:
- AMTopFrame2::setupUi() ~ Set top frames layout to verticalLayout_

33d5c4836142669e951212ff02f59d32829d7021

**Comment by dretrex** [comment]
Done in #1198.  Time estimate @iainworkman?

**Comment by iainworkman** [comment]
About 2 hours. We hadn't been doing complexity estimates for these individually as they're all related to one super issue #830 I think.

-----Original Message-----
