### ISSUE TITLE
Remove UI Files for AMImagePropertyEditor

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#997]
Incorporate generated code from AMImagePropertyEditor.ui into AMImagePropertyEditor.h and AMImagePropertyEditor.cpp.

Part of the super issue #830

**Comment by iainworkman** [comment]
Removed this from widget constructors in AMImagePropertyEditor

**Comment by dretrex** [comment]
Is this one done now too?

**Comment by iainworkman** [comment]
Found a few more constructors with 'this' in AMImagePropertyEditor ~ removed them.

59f905cc5c921a46e3d763dd3dedde68034e1e55

**Comment by iainworkman** [comment]
I've checked for usage on the three classes for the three changes awaiting testing (#874 #996 and #997) and they seem to be mostly be used in REIXS. Will try and find @epengr this morning to see if it's free.

**Comment by dretrex** [comment]
@epengr can we do these couple tests?  It would be nice to clear up these issues since they are just waiting in code to be merged in.

**Comment by iainworkman** [comment]
Again, redid these on an up to date master branch.

**Comment by iainworkman** [comment]
Altered:

- Moved member widgets and initialization from ui_AMImagePropertyEditor.h to AMImagePropertyEditor.h and .cpp

7d60ca3672e225bbbe29b8c816be1ee6b13efa93

**Comment by iainworkman** [comment]
Removed:
- AMImagePropertyEditor.ui

8d9feab42cfdb27690bfcdc6d1710db1eb6712f1

**Comment by iainworkman** [comment]
Okay, so I tested this and while it appears to recreate the old version reliably the old version isn't designed particularly well (black text, black background - at least on SL5.4) so I'll just fix up the appearance here before the merge.

**Comment by dretrex** [comment]
Done in #1207.  Time estimate?

**Comment by iainworkman** [comment]
About 4 hours
